In [1]:
import os
import pandas as pd
import time
import numpy as np
pd.set_option('display.max_columns', None) # so we can see all columns in a wide DataFrame

import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

## Loading the combined_stats.csv file

In [2]:
stats_df = pd.read_csv("C:/Users/User/Dropbox/RU45-Sussex OneDrive/NBA Games Prediction Model/data/preprocessed_cleaned_csv/fullGame_stats.csv", index_col=0)
stats_df

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,orb,drb,trb,ast,stl,blk,tov,pf,ts%,efg%,3par,ftr,orb%,drb%,trb%,ast%,stl%,blk%,tov%,usg%,ortg,drtg,fg_max,fga_max,fg%_max,3p_max,3pa_max,3p%_max,ft_max,fta_max,ft%_max,orb_max,drb_max,trb_max,ast_max,stl_max,blk_max,tov_max,pf_max,pts_max,+/-_max,ts%_max,efg%_max,3par_max,ftr_max,orb%_max,drb%_max,trb%_max,ast%_max,stl%_max,blk%_max,tov%_max,usg%_max,ortg_max,drtg_max,team,total,home,mp_opp,fg_opp,fga_opp,fg%_opp,3p_opp,3pa_opp,3p%_opp,ft_opp,fta_opp,ft%_opp,orb_opp,drb_opp,trb_opp,ast_opp,stl_opp,blk_opp,tov_opp,pf_opp,ts%_opp,efg%_opp,3par_opp,ftr_opp,orb%_opp,drb%_opp,trb%_opp,ast%_opp,stl%_opp,blk%_opp,tov%_opp,usg%_opp,ortg_opp,drtg_opp,fg_max_opp,fga_max_opp,fg%_max_opp,3p_max_opp,3pa_max_opp,3p%_max_opp,ft_max_opp,fta_max_opp,ft%_max_opp,orb_max_opp,drb_max_opp,trb_max_opp,ast_max_opp,stl_max_opp,blk_max_opp,tov_max_opp,pf_max_opp,pts_max_opp,+/-_max_opp,ts%_max_opp,efg%_max_opp,3par_max_opp,ftr_max_opp,orb%_max_opp,drb%_max_opp,trb%_max_opp,ast%_max_opp,stl%_max_opp,blk%_max_opp,tov%_max_opp,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won,PER_Combined,PER_Combined_opp
0,240.0,36.0,93.0,0.387,9.0,19.0,0.474,6.0,10.0,0.600,13.0,26.0,39.0,17.0,10.0,6.0,17.0,26.0,0.447,0.435,0.204,0.108,27.7,72.2,47.0,47.2,10.5,11.1,14.9,100.0,91.6,102.1,8.0,14.0,0.800,3.0,7.0,1.000,3.0,5.0,1.000,5.0,5.0,10.0,7.0,2.0,3.0,5.0,4.0,18.0,10.0,0.900,0.900,0.538,0.455,19.0,37.1,21.6,54.9,3.9,18.5,31.3,30.1,151.0,111.0,ORL,87.0,0,240.0,34.0,71.0,0.479,7.0,17.0,0.412,22.0,32.0,0.688,10.0,34.0,44.0,17.0,4.0,18.0,20.0,13.0,0.570,0.528,0.239,0.451,27.8,72.3,53.0,50.0,4.2,24.3,19.0,100.0,102.1,91.6,8.0,16.0,0.750,3.0,6.0,0.667,5.0,7.0,1.0,6.0,10.0,16.0,5.0,2.0,7.0,5.0,5.0,24.0,15.0,0.922,0.875,0.800,6.000,29.7,38.0,34.4,29.0,3.3,16.9,50.0,29.2,150.0,104.0,IND,97.0,1,2014,2013-10-29,False,62.3,79.2
1,240.0,37.0,72.0,0.514,11.0,20.0,0.550,22.0,29.0,0.759,5.0,35.0,40.0,26.0,10.0,7.0,18.0,21.0,0.631,0.590,0.278,0.403,14.3,76.1,49.4,70.3,10.3,12.3,17.5,100.0,110.2,97.9,6.0,13.0,0.833,4.0,6.0,1.000,7.0,9.0,1.000,2.0,7.0,8.0,8.0,5.0,3.0,3.0,4.0,17.0,17.0,1.167,1.167,0.857,0.875,10.2,44.1,28.6,40.5,9.2,10.2,38.1,24.5,209.0,106.0,MIA,107.0,1,240.0,35.0,83.0,0.422,7.0,26.0,0.269,18.0,23.0,0.783,11.0,30.0,41.0,23.0,11.0,4.0,18.0,27.0,0.510,0.464,0.313,0.277,23.9,85.7,50.6,65.7,11.3,7.7,16.2,100.0,97.9,110.2,13.0,18.0,0.722,2.0,7.0,0.500,6.0,7.0,1.0,4.0,9.0,11.0,4.0,5.0,2.0,5.0,6.0,31.0,10.0,0.767,0.722,0.667,0.583,19.8,61.3,32.4,26.0,8.3,9.2,29.1,29.6,218.0,118.0,CHI,95.0,0,2014,2013-10-29,True,97.1,62.1
2,240.0,35.0,83.0,0.422,7.0,26.0,0.269,18.0,23.0,0.783,11.0,30.0,41.0,23.0,11.0,4.0,18.0,27.0,0.510,0.464,0.313,0.277,23.9,85.7,50.6,65.7,11.3,7.7,16.2,100.0,97.9,110.2,13.0,18.0,0.722,2.0,7.0,0.500,6.0,7.0,1.000,4.0,9.0,11.0,4.0,5.0,2.0,5.0,6.0,31.0,10.0,0.767,0.722,0.667,0.583,19.8,61.3,32.4,26.0,8.3,9.2,29.1,29.6,218.0,118.0,CHI,95.0,0,240.0,37.0,72.0,0.514,11.0,20.0,0.550,22.0,29.0,0.759,5.0,35.0,40.0,26.0,10.0,7.0,18.0,21.0,0.631,0.590,0.278,0.403,14.3,76.1,49.4,70.3,10.3,12.3,17.5,100.0,110.2,97.9,6.0,13.0,0.833,4.0,6.0,1.000,7.0,9.0,1.0,2.0,7.0,8.0,8.0,5.0,3.0,3.0,4.0,17.0,17.0,1.167,1.167,0.857,0.875,10.2,44.1,28.6,40.5,9.2,10.2,38.1,24.5,209.0,106.0,MIA,107.0,1,2014,2013-10-29,False,62.1,97.1
3,240.0,34.0,71.0,0.479,7.0,17.0,0.412,22.0,32.0,0.688,10.0,34.0,44.0,17.0,4.0,18.0,20.0,13.0,0.570,0.528,0.239,0.451,27.8,72.3,53.0,50.0,4.2,24.3,19.0,100.0,102.1,91.6,8.0,16.0,0.750,3.0,6.0,0.667,5.0,7.0,1.000,6.0,10.0,16.0,5.0,2.0,7.0,5.0,5.0,24.0,15.0,0.922,0.875,0.800,6.000,29.7,38.0,34.4,29.0,3.3,16.9,50.0,29.2,150.0,104.0,IND,97.0,1,240.0,36.0,93.0,0.387,9.0,19.0,0.474,6.0,10.0,0.600,13.0,26.0,39.0,17.0,10.0,6.0,17.0,26.0,0.447,0.435,0.204,0.108,27.7,72.2,47.0,47.2,10.5,11.1,14.9,100.0,91.6,102.1,8.0,14.0,0.800,3.0,7.0,1.000,3.0,5.0,1.0,5.0,5.0,10.0,7.0,2.0,3.0,5.0,4.0,18.0,10.0,0.900,0.900,0.538,0.455,19.0,37.1,21.6,54.9,3.9,18.5,31.3,30.1,151.0,111.0,ORL,87.0,0,2014,2013-10-29,True,79.2,62.3
4,240.0,41.0,83.0,0.494,8.0,21.0,0.381,13.0,23.0,0.565,10.0,30.0,40.0,27.0,11.0,4.0,16.0,21.0,0.553,0.542,0.253,0.277,22.7,62.5,43.5,65.9,11.0,6.3,14.7,100.0,102.6,115.6,8.0,15.0,1.000,3.0,6.0,1.000,5.0,10.0,1.000,4.0,7.0,11.0,11.0,5.0,3.0,4.0,5.0,19.0,2.0,1.000,1.000,0.667,1.000,12.3,25.3,16.2,42.8,6.6,19.0,31.8,41.2,200.0,127.0,LAC,103.0,0,240.0,42.0,93.0,0.452,14.0,29.0,0.483,18.0,28.0,0.643,18.0,34.0,52.0,23.0,8.0,6.0,19.0,23.0,0.551,0.527,0.312,0.301,37.5,77.3,56.5,54.8,8.0,9.7,15.3,100.0,115.6,102.6,8.0,13.0,0.750,3.0,6.0,1.000,6.0,8.0,1.0,7.0,12.0,13.0,6.0,1.0,2.0,5.0,5.0,22.0,19.0,1.000,1.000,0.750,0.800,38.8,53.5,27.7,33.6,3.7,12.1,50.0,29.6,210.0,110.0,LAL,116.0,1,2014,2013-10-29,False,101.9,61.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25667,240.0,34.0,92.0,0.370,11.0,35.0,0.314,15.0,19.0,0.789,10.0,23.0,33.0,20.0,7.0,3.0,4.0,22.0,0.468,0.429,0.380,0.207,18.2,63.9,36.3,58.8,7.7,4.8,3.8,100.0,103.8,120.4,11.0,24.0,0.500,3.0,6.0,0.500,8.0,10.0,0.833,6.0,11.0,17.0,5.0,2.0,1.0,2.0,4.0,28.0,4.0,0.750,0.750,1.000,0.476,74.8,35.9,45.2,31.0,3.6,3.2,11.1,95.2,134.0,129.0,MIA,94.0,1,240.0,41.0,80.0,0.513,5.0,18.0,0.278,22.0,27.0,0.815,13.0,45.0,58.0,28.0,3.0,5.0,13.0,18.0,0.593,0.544,0.225,0.338,36.1,81.8,63.7,68.3,3.3,8.8,12.4,100.0,120.4,103.8,12.0,22.0,1.000,3.0,6.0,0.500,7.0,8.0,1.0,3.0,18.0,21.0,10.0,1.0,3.0,7.0,5.0,34.0,16.0,1.000,1.000,1.000,1.000,14.0,63.1,38.1,84.6,2.8,8.8,21.5,33.4,202.0,113.0,DEN,109.0,0,2023,2023-06-07,False,71.7,97.3
25668,240.0,35.0,78.0,0.449,8.0,25.0,0.320,17.0,20.0,0.850,8.0,29.0,37.0,23.0,2.0,3.0,14.0,19.0,0.547,0.500,0.321,0.256,21.6,85.3,52.1,65.7,2.3,5.9,13.9,100.0,107.2,121.9,9.0,19.0,0.714,3.0,5.0,0.600,6.0,9.0,1.000,2.0,9.0,11.0,7.0,1.0,1.0,7.0,4.0,25.0,5.0,0.932,0.917,0.833,0.857,7.9,32.5,17.9,33.5,2.2,21.6,25.2,30.3,223.0,127.0,MIA,95.0,1,240.0,39.0,79.0,0.494,14.0,28.0,0.500,16.0,21.0,0.762,5.0,29.0,34.0,26.0,11.0,7.0,6.0,18.0,0.612,0.582,0.354,0.266,14.7,78.4,47.9,66.7,12.4,13.2,6.4,100.0,121.9,107.2,11.0,19.0,1.000,3.0,7.0,1.000,4.0,4.0,1.0,2.0,10.0,12.0,12.0,3.0,3.0,3.0,5.0,27.0,29.0,1.500,1.500,1.000,2.000,7.8,34.9,21.8,40.5,4.5,7.3,50.0,32.6,164.0,114.0,DEN,108.0,0,2023,2023-06-09,False,71.7,97.3
25669,240.0,39.0,79.0,0.494,14.0,28.0,0.500,16.0,21.0,0.762,5.0,29.0,34.0,26.0,11.0,7.0,6.0,18.0,0.612,0.582,0.354,0.266,14.7,78.4,47.9,66.7,12.4,13.2,6.4,100.0,121.9,107.2,11.0,19.0,1.000,3.0,7.0,1.000,4.0,4.0,1.000,2.0,10.0,12.0,12.0,3.0,3.0,3.0,5.0,27.0,29.0,1.500,1.500,1.000,2.000,7.8,34.9,21.8,40.5,4.5,7.3,50.0,32.6,164.0,114.0,DEN,108.0,0,240.0,35.0,78.0,0.449,8.0,25.0,0.320,17.0,20.0,0.850,8.0,29.0,37.0,23.0,2.0,3.0,14.0,19.0,0.547,0.500,0.321,0.256,21.6,85.3,52.1,65.7,2.3,5.9,13.9,100.0,107.2,121.9,9.0,19.0,0.714,3.0,5.0,0.600,6.0,9.0,1.0,2.0,9.0,11.0,7.0,1.0,1.0,7.0,4.0,25.0,5.0,0.932,0.917,0.833,0.857,7.9,32.5,17.9,33.5,2.2,21.6,25.2,30.3,223.0,127.0,MIA,95.0,1,2023,2023-06-09,True,97.3,71.7
25670,240.0,33.0,96.0,0.344,9.0,35.0,0.257,14.0,16.0,0.875,11.0,33.0,44.0,18.0,9.0,7.0,8.0,21.0,0.432,0.391,0.365,0.167,19.3,75.0,43.6,54.5,9.4,12.5,7.2,100.0,92.6,97.8,9.0,20.0,0.450,4.0,9.0,0.444,9.0,11.0,1.000,5.0,7.0,12.0,5.0,3.0,2.0,2.0,5.0,21.0,13.0,0.506,0.462,1.000,0.611,82.8,37.6,46.7,31.4,3.6,12.1,25.0,42.5,102.0,109.0,MIA,89.0,0,240.0,38.0,84.0,0.452,5.0,28.0,0.179,13.0,23.0,0.565,11.0,46.0,57.0,21.0,6.0,7.0,14.0,13.0,0.499,0.482,0.333,0.274,25.0,80.7,56.4,55.3,6.2,11.5,12.9,100.0,97.8,92.6,12.0,17.0,1.000,2.0,7.0,0.333,3.0,6.0,1.0,4.0,15.0,16.0,8.0,2.0,3.0,6.0,4.0,28.0,12.0,1.000,1.000,0.500,1.500,15.5,29.9,18.4,57.2,3.5,26.1,28.6,26.4,202.0,104.0,DEN,94.0,1,2023,2023-06-12,False,71.7,97.3
25671,240.0,38.0,84.0,0.452,5.0,28.0,0.179,13.0,23.0,0.565,11.0,46.0,57.0,21.0,6.0,7.0,14.0,13.0,0.499,0.482,0.333,0.274,25.0,80.7,56.4,55.3,6.2,11.5,12.9,100.0,97.8,92.6,12.0,17.0,1.000,2.0,7.0,0.333,3.0,6.0,1.000,4.0,15.0,16.0,8.0,2.0,3.0,6.0,4.0,28.0,12.0,1.000,1.000,0.500,1.500,15.5,29.9,18.4,57.2,3.5,26.1,28.6,26.4,202.0,104.0,DEN,94.0,1,240.0,33.0,96.0,0.344,9.0,35.0,0.257,14.0,16.0,0.875,11.0,33.0,44.0,18.0,9.0,7.0,8.0,21.0,0.432,0.391,0.365,0.167,19.3,75.0,43.6,54.5,9.4,12.5,7.2,100.0,92.6,97.8,9.0,20.0,0.450,4.0,9.0,0.444,9.0,11.0,1.0,5.0,7.0,12.0,5.0,3.0,2.0,2.0,5.0,21.0,13.0,0.506,0.462,1.000,0.611,82.8,37.6,46.7,31.4,3.6,12.1,25.0,42.5,102.0,109.0,MIA,89.0,0,2023,2023-06-12,True,97.3,71.7

In [3]:
stats_df.team_opp.unique()

array(['IND', 'CHI', 'MIA', 'ORL', 'LAL', 'LAC', 'OKC', 'UTA', 'BOS',
       'TOR', 'MEM', 'SAS', 'SAC', 'POR', 'PHO', 'PHI', 'MIL', 'NYK',
       'DEN', 'NOP', 'MIN', 'CHA', 'HOU', 'CLE', 'GSW', 'WAS', 'DET',
       'ATL', 'DAL', 'BRK'], dtype=object)

## Feature Engineering

In [4]:
"""
When working with time series data, it's recommended to use the date as index or the index should be alinged with the date
"""
stats_df = stats_df.sort_values("date")
stats_df = stats_df.reset_index(drop=True)
# stats_df

## Adding a target column
Defining a function to add a new column, that will show result of the next game

In [5]:
def add_target(group):
    group["target"] = group["won"].shift(-1)
    return group

stats_df = stats_df.groupby("team", group_keys=True).apply(add_target)
stats_df.index = stats_df.index.droplevel()
stats_df

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,orb,drb,trb,ast,stl,blk,tov,pf,ts%,efg%,3par,ftr,orb%,drb%,trb%,ast%,stl%,blk%,tov%,usg%,ortg,drtg,fg_max,fga_max,fg%_max,3p_max,3pa_max,3p%_max,ft_max,fta_max,ft%_max,orb_max,drb_max,trb_max,ast_max,stl_max,blk_max,tov_max,pf_max,pts_max,+/-_max,ts%_max,efg%_max,3par_max,ftr_max,orb%_max,drb%_max,trb%_max,ast%_max,stl%_max,blk%_max,tov%_max,usg%_max,ortg_max,drtg_max,team,total,home,mp_opp,fg_opp,fga_opp,fg%_opp,3p_opp,3pa_opp,3p%_opp,ft_opp,fta_opp,ft%_opp,orb_opp,drb_opp,trb_opp,ast_opp,stl_opp,blk_opp,tov_opp,pf_opp,ts%_opp,efg%_opp,3par_opp,ftr_opp,orb%_opp,drb%_opp,trb%_opp,ast%_opp,stl%_opp,blk%_opp,tov%_opp,usg%_opp,ortg_opp,drtg_opp,fg_max_opp,fga_max_opp,fg%_max_opp,3p_max_opp,3pa_max_opp,3p%_max_opp,ft_max_opp,fta_max_opp,ft%_max_opp,orb_max_opp,drb_max_opp,trb_max_opp,ast_max_opp,stl_max_opp,blk_max_opp,tov_max_opp,pf_max_opp,pts_max_opp,+/-_max_opp,ts%_max_opp,efg%_max_opp,3par_max_opp,ftr_max_opp,orb%_max_opp,drb%_max_opp,trb%_max_opp,ast%_max_opp,stl%_max_opp,blk%_max_opp,tov%_max_opp,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won,PER_Combined,PER_Combined_opp,target
14,240.0,37.0,76.0,0.487,8.0,24.0,0.333,27.0,35.0,0.771,5.0,28.0,33.0,27.0,16.0,5.0,17.0,20.0,0.596,0.539,0.316,0.461,12.5,80.0,44.0,73.0,15.9,9.4,15.7,100.0,108.3,117.2,9.0,15.0,0.800,3.0,7.0,0.500,9.0,12.0,1.00,2.0,6.0,7.0,9.0,5.0,4.0,6.0,4.0,24.0,11.0,1.136,0.800,1.000,1.143,7.2,35.0,16.3,61.0,7.5,11.3,66.7,31.3,239.0,128.0,ATL,109.0,0,240.0,44.0,77.0,0.571,11.0,24.0,0.458,19.0,24.0,0.792,7.0,35.0,42.0,31.0,7.0,2.0,20.0,22.0,0.674,0.643,0.312,0.312,20.0,87.5,56.0,70.5,7.0,3.8,18.6,100.0,117.2,108.3,11.0,17.0,1.000,4.0,6.0,1.000,8.0,8.0,1.0,5.0,8.0,9.0,11.0,2.0,1.0,7.0,4.0,32.0,18.0,1.500,1.500,1.000,0.500,32.5,35.7,21.4,37.0,3.5,3.4,69.4,33.4,270.0,113.0,DAL,118.0,1,2014,2013-10-30,False,86.300000,69.300000,True
48,240.0,36.0,77.0,0.468,10.0,23.0,0.435,20.0,31.0,0.645,7.0,30.0,37.0,24.0,7.0,3.0,13.0,12.0,0.563,0.532,0.299,0.403,17.9,75.0,46.8,66.7,7.5,4.6,12.5,100.0,108.9,101.4,9.0,14.0,0.643,5.0,8.0,0.667,8.0,9.0,1.00,3.0,13.0,16.0,12.0,3.0,1.0,3.0,2.0,22.0,20.0,0.708,0.750,0.750,1.000,17.2,50.2,33.9,51.7,4.6,10.3,33.3,25.7,124.0,111.0,ATL,102.0,1,240.0,40.0,88.0,0.455,7.0,23.0,0.304,8.0,14.0,0.571,10.0,32.0,42.0,15.0,5.0,6.0,12.0,25.0,0.504,0.494,0.261,0.159,25.0,82.1,53.2,37.5,5.3,11.1,11.3,100.0,101.4,108.9,14.0,23.0,0.714,3.0,5.0,1.000,3.0,6.0,1.0,3.0,6.0,9.0,4.0,2.0,2.0,4.0,4.0,31.0,14.0,0.830,0.929,1.000,0.857,15.5,31.8,23.6,47.9,3.1,10.0,50.0,37.6,157.0,117.0,TOR,95.0,0,2014,2013-11-01,True,86.300000,82.000000,False
81,240.0,40.0,90.0,0.444,9.0,22.0,0.409,14.0,26.0,0.538,10.0,42.0,52.0,26.0,9.0,3.0,11.0,22.0,0.508,0.494,0.244,0.289,17.5,87.5,49.5,65.0,8.7,4.7,9.8,100.0,99.6,101.6,8.0,18.0,0.800,6.0,6.0,1.000,6.0,10.0,0.75,3.0,13.0,16.0,4.0,2.0,1.0,4.0,4.0,22.0,12.0,1.100,1.100,0.857,1.111,19.4,39.1,23.9,28.6,6.1,2.6,22.5,31.1,206.0,109.0,ATL,103.0,0,240.0,38.0,89.0,0.427,9.0,25.0,0.360,20.0,24.0,0.833,6.0,47.0,53.0,27.0,5.0,7.0,13.0,24.0,0.527,0.478,0.281,0.270,12.5,82.5,50.5,71.1,4.8,10.3,11.5,100.0,101.6,99.6,5.0,18.0,1.000,2.0,4.0,0.500,6.0,8.0,1.0,3.0,13.0,13.0,7.0,2.0,3.0,4.0,6.0,18.0,4.0,1.042,1.000,0.800,1.000,14.3,39.5,21.5,34.9,4.9,10.1,33.3,37.1,158.0,108.0,LAL,105.0,1,2014,2013-11-03,False,86.300000,61.000000,True
117,240.0,39.0,81.0,0.481,8.0,22.0,0.364,19.0,26.0,0.731,9.0,27.0,36.0,26.0,11.0,7.0,14.0,15.0,0.568,0.531,0.272,0.321,23.7,73.0,48.0,66.7,11.7,14.3,13.2,100.0,111.6,106.3,11.0,19.0,0.750,2.0,5.0,1.000,5.0,8.0,1.00,5.0,8.0,11.0,10.0,4.0,2.0,4.0,4.0,27.0,6.0,0.922,0.875,0.750,0.667,17.9,33.8,20.9,56.0,6.1,17.0,38.1,30.2,136.0,116.0,ATL,105.0,0,240.0,35.0,80.0,0.438,10.0,31.0,0.323,20.0,21.0,0.952,10.0,29.0,39.0,22.0,10.0,4.0,18.0,26.0,0.560,0.500,0.388,0.263,27.0,76.3,52.0,62.9,10.6,6.8,16.8,100.0,106.3,111.6,8.0,17.0,0.500,3.0,7.0,0.429,9.0,9.0,1.0,2.0,8.0,9.0,5.0,3.0,2.0,4.0,5.0,26.0,4.0,0.689,0.650,0.800,1.000,11.4,32.6,18.6,39.8,8.0,5.8,37.2,39.6,133.0,117.0,SAC,100.0,1,2014,2013-11-05,True,86.300000,54.300000,False
142,240.0,43.0,94.0,0.457,8.0,26.0,0.308,13.0,19.0,0.684,13.0,33.0,46.0,31.0,11.0,9.0,11.0,23.0,0.523,0.500,0.277,0.202,27.1,76.7,50.5,72.1,11.2,14.8,9.7,100.0,109.4,111.4,10.0,21.0,0.667,2.0,5.0,0.667,7.0,11.0,1.00,3.0,8.0,10.0,11.0,3.0,4.0,4.0,4.0,29.0,13.0,0.735,0.733,1.000,0.733,16.1,53.9,33.9,46.2,6.4,9.0,21.6,30.7,155.0,123.0,ATL,107.0,0,240.0,42.0,86.0,0.488,14.0,25.0,0.560,11.0,17.0,0.647,10.0,35.0,45.0,28.0,4.0,8.0,16.0,18.0,0.583,0.570,0.291,0.198,23.3,72.9,49.5,66.7,4.1,11.8,14.6,100.0,111.4,109.4,9.0,16.0,0.750,4.0,6.0,1.000,4.0,5.0,0.8,4.0,7.0,9.0,8.0,1.0,2.0,3.0,3.0,23.0,17.0,0.806,0.786,0.714,1.250,17.0,31.5,19.0,46.4,2.4,13.3,29.1,33.1,150.0,114.0,DEN,109.0,1,2014,2013-11-07,False,86.300000,68.300000,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25348,240.0,39.0,79.0,0.494,16.0,37.0,0.432,15.0,18.0,0.833,5.0,33.0,38.0,26.0,9.0,5.0,18.0,18.0,0.627,0.595,0.468,0.228,13.5,82.5,49.4,66.7,9.1,8.9,17.2,100.0,110.8,119.9,10.0,19.0,1.000,4.0,11.0,0.800,5.0,5.0,1.00,3.0,6.0,7.0,7.0,4.0,2.0,8.0,4.0,29.0,9.0,1.042,1.000,0.667,1.000,15.9,34.1,17.8,90.1,6.2,24.4,50.0,31.7,241.0,128.0,WAS,109.0,0,240.0,46.0,88.0,0.523,13.0,32.0,0.406,13.0,18.0,0.722,7.0,32.0,39.0,31.0,12.0,4.0,11.0,17.0,0.615,0.597,0.364,0.205,17.5,86.5,50.6,67.4,12.2,9.5,10.3,100.0,119.9,110.8,11.0,20.0,0.800,6.0,11.0,0.545,4.0,5.0,1.0,4.0,7.0,11.0,8.0,3.0,1.0,5.0,5.0,27.0,19.0,0.820,0.800,1.000,0.600,18.5,38.7,26.5,30.1,4.4,5.2,66.7,31.2,192.0,120.0,NYK,118.0,1,2023,2023-04-02,False,34.246017,70.500000,False
25367,240.0,50.0,99.0,0.505,13.0,27.0,0.481,15.0,21.0,0.714,9.0,33.0,42.0,30.0,7.0,4.0,9.0,21.0,0.591,0.571,0.273,0.212,17.0,73.3,42.9,60.0,6.4,8.0,7.7,100.0,117.9,129.0,9.0,17.0,0.800,5.0,6.0,1.000,6.0,6.0,1.00,2.0,7.0,9.0,9.0,2.0,2.0,3.0,5.0,24.0,7.0,0.800,0.800,0.600,1.250,8.6,28.5,16.4,41.6,3.9,5.3,28.6,34.4,153.0,135.0,WAS,128.0,1,240.0,50.0,92.0,0.543,23.0,42.0,0.548,17.0,29.0,0.586,12.0,44.0,56.0,33.0,6.0,7.0,18.0,19.0,0.668,0.668,0.457,0.315,26.7,83.0,57.1,66.0,5.5,9.7,14.7,100.0,129.0,117.9,12.0,21.0,0.750,5.0,9.0,0.800,10.0,17.0,1.0,5.0,15.0,20.0,10.0,2.0,5.0,8.0,4.0,28.0,24.0,1.125,1.125,1.000,1.063,17.1,43.7,31.5,51.7,3.2,11.0,33.3,37.5,208.0,126.0,MIL,140.0,0,2023,2023-04-04,False,34.246017,81.200000,False
25376,240.0,45.0,94.0,0.479,6.0,28.0,0.214,20.0,26.0,0.769,12.0,27.0,39.0,23.0,10.0,9.0,14.0,26.0,0.550,0.511,0.298,0.277,25.0,69.2,44.8,51.1,9.6,16.7,11.7,100.0,111.6,129.0,8.0,18.0,0.833,2.0,8.0,0.667,9.0,9.0,1.00,4.0,7.0,10.0,6.0,4.0,3.0,4.0,4.0,25.0,2.0,1.017,1.000,0.667,0.900,17.6,32.4,24.2,25.4,6.3,9.0,50.0,29.9,179.0,139.0,WAS,116.0,0,240.0,43.0,84.0,0.512,13.0,30.0,0.433,35.0,40.0,0.875,12.0,36.0,48.0,30.0,10.0,5.0,16.0,23.0,0.659,0.589,0.357,0.476,30.8,75.0,55.2,69.8,9.6,7.6,13.6,100.0,129.0,111.6,8.0,13.0,1.000,4.0,6.0,1.000,16.0,18.0,1.0,4.0,8.0,8.0,16.0,3.0,3.0,4.0,5.0,25.0,19.0,1.031,1.000,1.000,1.800,40.8,66.3,54.9,52.4,15.3,14.4,33.3,40.6,206.0,121.0,ATL,134.0,1,2023,2023-04-05,False,34.246017,72.300000,True
25415,240.0,39.0,84.0,0.464,7.0,33.0,0.212,29.0,37.0,0.784,12.0,38.0,50.0,23.0,4.0,3.0,16.0,18.0,0.568,0.506,0.393,0.440,26.7,73.1,51.5,59.0,3.9,5.9,13.8,100.0,111.3,105.4,9.0,20.0,0.900,3.0,9.0,0.500,6.0,10.0,1.00,4.0,7.0,9.0,4.0,3.0,1.0,3.0,5.0,22.0,25.0,0.935,0.900,0.833,3.333,19.4,32.7,22.5,36.4,6.4,4.0,28.8,24.6,164.0,112.0,WAS,114.0,1,240.0,43.0,98.0,0.439,15.0,47.0,0.319,7.0,12.0,0.583,14.0,33.0,47.0,26.0,7.0,4.0,16.0,29.0,0.523,0.515,0.480,0.122,26.9,73.3,48.5,60.5,6.8,7.8,13.4,100.0,105.4,111.3,11.0,24.0,0.800,7.0,16.0,0.667,3.0,4.0,1.0,4.0,5.0,9.0,8.0,2.0,2.0,3.0,6.0,30.0,18.0,0.814,0.800,0.750,1.000,17.1,24.8,17.3,47.8,3.6,5.8,27.3,44.5,149.0,117.0,MIA,108.0,0,2023,2023-04-07,True,34.246017,34.246017,False
25459,240.0,41.0,97.0,0.423,14.0,45.0,0.311,13.0,21.0,0.619,14.0,37.0,51.0,28.0,11.0,5.0,12.0,21.0,0.513,0.495,0.464,0.216,26.9,74.0,50.0,68.3,10.7,7.2,10.1,100.0,106.5,111.4,9.0,20.0,0.750,5.0,15.0,0.714,3.0,4.0,1.00,7.0,10.0,14.0,8.0,2.0,2.0,4.0,4.0,22.0,4.0,1.066,1.063,0.875,0.500,16.9,21.1,17.3,29.0,3.2,6.4,28.8,27.9,196.0,116.0,WAS,109.0,1,240.0,44.0,90.0,0.489,6.0,21.0,0.286,20.0,28.0,0.714,13.0,38.0,51.0,24.0,8.0,6.0,15.0,15.0,0.557,0.522,0.233,0.311,26.0,73.1,50.0,54.5,7.8,11.5,12.8,100.0,111.4,106.5,6.0,12.0,0.714,2.0,3.0,1.000,7.0,8.0,1.0,3.0,9.0,12.0,6.0,2.0,2.0,4.0,3.0,20.0,10.0,0.689,0.800,0.667,0.727,22.8,35.3,24.0,34.1,4.5,7.8,40.0,27.3,136.0,117.0,HOU,114.0,0,2023,2023-04-09,False,34.246017,60.800000,NaN

In [6]:
"""
Since the next game a team would be involved in is not played yet, we have instances of NAN in our target
Also we convert the booleans to integers in the target column
"""
# Replace missing values in "target" column with 2
stats_df.loc[pd.isnull(stats_df["target"]), "target"] = 2

# Convert "target" column to integers
stats_df["target"] = stats_df["target"].astype(int, errors="ignore")

In [7]:
needed = stats_df[['team', 'total', 'team_opp', 'total_opp', 'season', 'won','target']]
needed

      team  total team_opp  total_opp  season    won  target
14     ATL  109.0      DAL      118.0    2014  False       1
48     ATL  102.0      TOR       95.0    2014   True       0
81     ATL  103.0      LAL      105.0    2014  False       1
117    ATL  105.0      SAC      100.0    2014   True       0
142    ATL  107.0      DEN      109.0    2014  False       1
...    ...    ...      ...        ...     ...    ...     ...
25348  WAS  109.0      NYK      118.0    2023  False       0
25367  WAS  128.0      MIL      140.0    2023  False       0
25376  WAS  116.0      ATL      134.0    2023  False       1
25415  WAS  114.0      MIA      108.0    2023   True       0
25459  WAS  109.0      HOU      114.0    2023  False       2

[25640 rows x 7 columns]

In [8]:
"""
This are the last games for each team where the next games are not known
"""
target_2_rows = stats_df[stats_df["target"] == 2]
target_2_rows

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,orb,drb,trb,ast,stl,blk,tov,pf,ts%,efg%,3par,ftr,orb%,drb%,trb%,ast%,stl%,blk%,tov%,usg%,ortg,drtg,fg_max,fga_max,fg%_max,3p_max,3pa_max,3p%_max,ft_max,fta_max,ft%_max,orb_max,drb_max,trb_max,ast_max,stl_max,blk_max,tov_max,pf_max,pts_max,+/-_max,ts%_max,efg%_max,3par_max,ftr_max,orb%_max,drb%_max,trb%_max,ast%_max,stl%_max,blk%_max,tov%_max,usg%_max,ortg_max,drtg_max,team,total,home,mp_opp,fg_opp,fga_opp,fg%_opp,3p_opp,3pa_opp,3p%_opp,ft_opp,fta_opp,ft%_opp,orb_opp,drb_opp,trb_opp,ast_opp,stl_opp,blk_opp,tov_opp,pf_opp,ts%_opp,efg%_opp,3par_opp,ftr_opp,orb%_opp,drb%_opp,trb%_opp,ast%_opp,stl%_opp,blk%_opp,tov%_opp,usg%_opp,ortg_opp,drtg_opp,fg_max_opp,fga_max_opp,fg%_max_opp,3p_max_opp,3pa_max_opp,3p%_max_opp,ft_max_opp,fta_max_opp,ft%_max_opp,orb_max_opp,drb_max_opp,trb_max_opp,ast_max_opp,stl_max_opp,blk_max_opp,tov_max_opp,pf_max_opp,pts_max_opp,+/-_max_opp,ts%_max_opp,efg%_max_opp,3par_max_opp,ftr_max_opp,orb%_max_opp,drb%_max_opp,trb%_max_opp,ast%_max_opp,stl%_max_opp,blk%_max_opp,tov%_max_opp,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won,PER_Combined,PER_Combined_opp,target
25551,240.0,44.0,94.0,0.468,15.0,35.0,0.429,17.0,22.0,0.773,12.0,33.0,45.0,28.0,5.0,7.0,10.0,15.0,0.579,0.548,0.372,0.234,25.0,75.0,48.9,63.6,5.1,13.5,8.8,100.0,123.3,131.5,9.0,28.0,1.000,4.0,12.0,1.000,8.0,8.0,1.000,5.0,8.0,11.0,11.0,1.0,2.0,5.0,4.0,30.0,8.0,1.250,1.250,0.500,0.750,18.0,44.6,29.3,37.4,2.2,9.4,19.2,38.2,250.0,141.0,ATL,120.0,1,240.0,47.0,94.0,0.500,18.0,42.0,0.429,16.0,17.0,0.941,11.0,36.0,47.0,24.0,7.0,10.0,7.0,16.0,0.631,0.596,0.447,0.181,25.0,75.0,51.1,51.1,7.2,16.9,6.5,100.0,131.5,123.3,13.0,25.0,1.000,6.0,10.0,1.000,8.0,9.0,1.00,3.0,12.0,14.0,7.0,2.0,3.0,2.0,4.0,32.0,11.0,1.500,1.500,1.000,0.750,10.9,36.2,20.9,25.0,5.9,14.7,33.3,30.2,300.0,133.0,BOS,128.0,0,2023,2023-04-27,False,86.500000,90.200000,2
25629,240.0,32.0,82.0,0.390,9.0,42.0,0.214,11.0,13.0,0.846,10.0,30.0,40.0,18.0,6.0,4.0,15.0,13.0,0.479,0.445,0.512,0.159,22.2,81.1,48.8,56.3,6.6,6.9,14.6,100.0,92.4,113.3,8.0,23.0,1.000,2.0,9.0,1.000,6.0,7.0,1.000,3.0,9.0,11.0,5.0,1.0,2.0,8.0,5.0,19.0,3.0,1.500,1.500,1.000,0.583,48.1,28.1,26.4,24.1,3.3,11.7,25.1,35.6,264.0,121.0,BOS,84.0,1,240.0,42.0,86.0,0.488,14.0,28.0,0.500,5.0,6.0,0.833,7.0,35.0,42.0,26.0,7.0,2.0,12.0,15.0,0.581,0.570,0.326,0.070,18.9,77.8,51.2,61.9,7.7,5.0,11.9,100.0,113.3,92.4,12.0,28.0,0.688,4.0,7.0,0.667,4.0,4.0,1.00,3.0,9.0,10.0,7.0,3.0,1.0,4.0,3.0,28.0,26.0,0.833,0.833,0.750,0.400,8.7,30.7,16.9,27.4,5.6,6.0,33.3,32.9,154.0,103.0,MIA,103.0,0,2023,2023-05-29,False,90.200000,71.700000,2
25516,240.0,33.0,80.0,0.413,9.0,37.0,0.243,13.0,19.0,0.684,5.0,33.0,38.0,20.0,3.0,6.0,10.0,14.0,0.498,0.469,0.463,0.238,11.4,68.8,41.3,60.6,3.4,9.0,10.2,100.0,98.4,107.3,8.0,18.0,0.800,3.0,6.0,0.500,3.0,6.0,1.000,3.0,9.0,12.0,6.0,1.0,4.0,4.0,3.0,20.0,5.0,0.779,0.800,1.000,0.500,8.6,23.7,16.5,29.7,2.8,7.6,21.3,27.3,134.0,119.0,BRK,88.0,1,240.0,36.0,91.0,0.396,9.0,24.0,0.375,15.0,16.0,0.938,15.0,39.0,54.0,19.0,7.0,3.0,8.0,19.0,0.490,0.445,0.264,0.176,31.3,88.6,58.7,52.8,7.8,7.0,7.5,100.0,107.3,98.4,11.0,20.0,1.000,3.0,7.0,0.500,7.0,8.0,1.00,8.0,10.0,15.0,11.0,2.0,1.0,3.0,4.0,25.0,15.0,1.000,1.000,0.667,2.000,25.1,53.4,25.6,41.9,3.6,3.5,33.3,28.1,203.0,106.0,PHI,96.0,0,2023,2023-04-22,False,70.700000,53.400000,2
25444,240.0,37.0,81.0,0.457,6.0,32.0,0.188,26.0,30.0,0.867,10.0,39.0,49.0,23.0,8.0,5.0,18.0,14.0,0.563,0.494,0.395,0.370,23.3,78.0,52.7,62.2,8.1,9.6,16.0,100.0,106.7,95.6,9.0,18.0,0.900,2.0,10.0,0.250,9.0,10.0,1.000,4.0,9.0,10.0,6.0,2.0,3.0,4.0,3.0,22.0,17.0,0.887,0.900,1.000,1.250,13.7,32.8,23.5,47.9,3.0,15.8,32.6,26.7,142.0,105.0,CHA,106.0,0,240.0,35.0,89.0,0.393,10.0,37.0,0.270,15.0,16.0,0.938,11.0,33.0,44.0,27.0,9.0,5.0,16.0,24.0,0.495,0.449,0.416,0.180,22.0,76.7,47.3,77.1,9.1,10.2,14.3,100.0,95.6,106.7,6.0,12.0,0.667,3.0,10.0,0.750,5.0,5.0,1.00,2.0,4.0,6.0,7.0,3.0,1.0,3.0,5.0,17.0,8.0,0.750,0.750,0.833,1.000,16.0,37.2,25.8,51.1,6.1,8.2,31.6,29.5,129.0,112.0,CLE,95.0,1,2023,2023-04-09,True,34.246017,37.800000,2
25469,240.0,36.0,82.0,0.439,8.0,28.0,0.286,11.0,15.0,0.733,5.0,32.0,37.0,24.0,5.0,3.0,11.0,25.0,0.514,0.488,0.341,0.183,10.9,76.2,42.0,66.7,5.4,6.3,11.0,100.0,98.0,109.8,9.0,21.0,0.750,4.0,8.0,0.667,8.0,9.0,0.889,3.0,9.0,9.0,9.0,1.0,1.0,5.0,6.0,26.0,8.0,0.727,0.750,1.000,0.474,30.6,55.8,42.6,41.9,3.0,9.8,25.0,33.1,144.0,119.0,CHI,91.0,0,240.0,32.0,78.0,0.410,10.0,30.0,0.333,28.0,32.0,0.875,10.0,41.0,51.0,19.0,7.0,2.0,13.0,20.0,0.554,0.474,0.385,0.410,23.8,89.1,58.0,59.4,7.5,3.7,12.4,100.0,109.8,98.0,11.0,24.0,0.500,7.0,12.0,0.583,9.0,10.0,1.00,4.0,13.0,17.0,7.0,2.0,1.0,4.0,4.0,31.0,27.0,0.794,0.719,1.000,0.889,12.2,36.3,24.8,49.0,4.9,2.4,50.0,32.4,152.0,103.0,MIA,102.0,1,2023,2023-04-14,False,78.800000,87.000000,2
25548,240.0,35.0,75.0,0.467,13.0,33.0,0.394,12.0,15.0,0.800,4.0,26.0,30.0,24.0,5.0,2.0,13.0,22.0,0.582,0.553,0.440,0.200,11.4,60.5,38.5,68.6,5.7,3.6,13.7,100.0,108.3,120.9,11.0,26.0,1.000,4.0,12.0,1.000,6.0,6.0,1.000,2.0,8.0,9.0,5.0,2.0,1.0,6.0,6.0,28.0,1.0,1.500,1.500,1.000,0.667,7.6,26.3,14.5,23.6,5.5,2.2,100.0,34.9,300.0,131.0,CLE,95.0,1,240.0,37.0,85.0,0.435,9.0,29.0,0.310,23.0,29.0,0.793,17.0,31.0,48.0,21.0,6.0,5.0,10.0,17.0,0.542,0.488,0.341,0.341,39.5,88.6,61.5,56.8,6.8,11.9,9.3,100.0,120.9,108.3,8.0,22.0,0.667,3.0,10.0,0.500,6.0,6.0,1.00,11.0,9.0,18.0,6.0,2.0,3.0,4.0,4.0,23.0,21.0,0.671,0.667,0.667,2.000,33.9,26.5,30.6,70.6,3.0,9.7,20.4,34.7,139.0,116.0,NYK,106.0,0,2023,2023-04-26,False,91.900000,90.800000,2
25442,240.0,46.0,108.0,0.426,17.0,53.0,0.321,8.0,16.0,0.500,8.0,38.0,46.0,28.0,4.0,3.0,2.0,21.0,0.509,0.505,0.491,0.148,12.5,74.5,40.0,60.9,3.6,4.5,1.7,100.0,105.6,124.5,11.0,23.0,0.538,5.0,11.0,0.500,2.0,5.0,1.000,2.0,11.0,13.0,12.0,1.0,2.0,2.0,4.0,25.0,-5.0,0.731,0.731,0.846,0.556,5.3,25.6,13.4,39.0,1.9,5.1,13.6,34.8,153.0,128.0,DAL,117.0,1,240.0,51.0,104.0,0.490,15.0,38.0,0.395,21.0,30.0,0.700,13.0,56.0,69.0,31.0,2.0,3.0,12.0,13.0,0.589,0.563,0.365,0.288,25.5,87.5,60.0,60.8,1.8,5.5,9.3,100.0,124.5,105.6,8.0,17.0,0.727,4.0,10.0,0.667,5.0,7.0,1.00,6.0,13.0,19.0,9.0,1.0,1.0,3.0,5.0,23.0,27.0,0.746,0.727,0.750,1.000,16.6,29.1,23.3,43.9,1.8,3.8,23.5,27.7,166.0,112.0,SAS,138.0,0,2023,2023-04-09,False,34.246017,34.246017,2
25639,240.0,38.0,84.0,0.452,5.0,28.0,0.179,13.0,23.0,0.565,11.0,46.0,57.0,21.0,6.0,7.0,14.0,13.0,0.499,0.482,0.333,0.274,25.0,80.7,56.4,55.3,6.2,11.5,12.9,100.0,97.8,92.6,12.0,17.0,1.000,2.0,7.0,0.333,3.0,6.0,1.000,4.0,15.0,16.0,8.0,2.0,3.0,6.0,4.0,28.0,12.0,1.000,1.000,0.500,1.500,15.5,29.9,18.4,57.2,3.5,26.1,28.6,26.4,202.0,104.0,DEN,94.0,1,240.0,33.0,96.0,0.344,9.0,35.0,0.257,14.0,16.0,0.875,11.0,33.0,44.0,18.0,9.0,7.0,8.0,21.0,0.432,0.391,0.365,0.167,19.3,75.0,43.6,54.5,9.4,12.5,7.2,100.0,92.6,97.8,9.0,20.0,0.450,4.0,9.0,0.444,9.0,11.0,1.00,5.0,7.0,12.0,5.0,3.0,2.0,2.0,5.0,21.0,13.0,0.506,0.462,1.000,0.611,82.8,37.6,46.7,31.4,3.6,12.1,25.0,42.5,102.0,109.0,MIA,89.0,0,2023,2023-06-12,True,97.300000,71.700000,2
25443,240.0,31.0,85.0,0.365,9.0,33.0,0.273,10.0,13.0,0.769,15.0,44.0,59.0,20.0,1.0,3.0,24.0,16.0,0.446,0.418,0.388,0.153,28.8,80.0,55.1,64.5,1.0,4.6,20.9,100.0,84.1,107.0,8.0,20.0,0.444,3.0,8.0,0.500,7.0,8.0,0.875,6.0,15.0,18.0,9.0,1.0,1.0,6.0,6.0,26.0,3.0,0.604,0.528,1.000,0.444,22.3,37.8,23.3,41.0,2.6,3.0,54.5,30.8,111.0,114.0,DET,81.0,0,240.0,40.0,95.0,0.421,6.0,30.0,0.200,17.0,22.0,0.773,11.0,37.0,48.0,21.0,15.0,7.0,3.0,16.0,0.492,0.453,0.316,0.232,20.0,71.2,44.9,52.5,15.6,13.5,2.8,100.0,107.0,84.1,7.0,15.0,0.667,1.0,5.0,0.500,4.0,4.0,1.00,5.0,7.0,10.0,5.0,3.0,2.0,1.0,4.0,17.0,20.0,0.709,0.667,0.667,0.667,34.4,38.3,35.4,42.9,9.9,12.1,20.0,34.3,156.0,94.0,CHI,103.0,1,2023,2023-04-09,False,34.246017,78.800000,2
25604,240.0,39.0,103.0,0.379,13.0,48.0,0.271,10.0,14.0,0.714,20.0,33.0,53.0,25.0,3.0,2.0,10.0,30.0,0.463,0.442,0.466,0.136,33.3,84.6,53.5,64.1,3.2,4.1,8.4,100.0,107.6,130.0,11.0,28.0,1.000,4.0,14.0,0.667,6.0,6.0,1.000,8.0,10.0,18.0,5.0,1.0,1.0,4.0,5.0,32.0,10.0,1.000,1.000,1.000,0.500,24.5,65.6,33.4,48.9,2.0,4.1,20.0,35.8,208.0,135.0,GSW,101.0,0,240.0,39.0,75.0,0.520,13.0,26.0,0.500,31.0,42.0,0.738,6.0,40.0,46.0,25.0,6.0,6.0,6.0,17.0,0.653,0.607,0.347,0.560,15.4,66.7,46.5,64.1,6.4,10.9,6.0,100.0,130.0,107.6,10.0,15.0,1.000,4.0,7.0,1.000,8.0,11.0,1.00,3.0,17.0,20.0,9.0,2.0,2.0,2.0,5.0,30.0,31.0,1.500,1.500,1.000,2.000,32.8,42.7,38.8,35.9,13.0,10.8,12.3,32.6,300.0,120.0,LAL,122.0,1,2023,2023-05-12,False,78.500000,94.400000,2
25458,240.0,44.0,90.0,0.489,6.0,21.0,0.286,20.0,28.0,0.714,13.0,38.0,51.0,24.0,8.0,6.0,15.0,15.0,0.557,0.522,0.233,0.311,26.0,73.1,50.0,54.5,7.8,11.5,12.8,100.0,111.4,106.5,6.0,12.0,0.714,2.0,3.0,1.000,7.0,8.0,1.000,3.0,9.0,12.0,6.0,2.0,2.0,4.0,3.0,20.0,10.0,0.689,0.800,0.667,0.727,22.8,35.3,24.0,34.1,4.5,7.8,40.0,27.3,136.0,117.0,HOU,114.0,0,240.0,41.0,97.0,0.423,14.0,45.0,0.311,13.0,21.0,0.619,14.0,37.0,51.0,28.0,11.0,5.0,12.0,21.0,0.513,0.495,0.464,0.216,26.9,74.0,50.0,68.3,10.7,7.2,10.1,100.0,106.5,111.4,9.0,20.0,0.750,5.0,15.0,0.714,3.0,4.0,1.00,7.0,10.0,14.0,8.0,2.0,2.0,4.0,4.0,22.0,4.0,1.066,1.063,0.875,0.500,16.9,21.1,17.3,29.0,3.2,6.4,28.8,27.9,196.0,116.0,WAS,109.0,1,2023,2023-04-09,True,60.800000,34.246017,2
25453,240.0,46.0,89.0,0.517,19.0,34.0,0.559,30.0,38.0,0.789,8.0,36.0,44.0,33.0,8.0,9.0,15.0,24.0,0.667,0.624,0.382,0.427,19.0,65.5,45.4,71.7,7.2,13.2,12.4,100.0,127.3,122.8,7.0,15.0,0.833,5.0,6.0,0.833,12.0,13.0,1.000,4.0,7.0,9.0,9.0,3.0,3.0,3.0,4.0,26.0,29.0,1.250,1.250,1.000,1.000,17.8,22.0,17.4,92.0,6.6,8.6,25.8,30.4,193.0,129.0,IND,141.0,0,240.0,52.0,108.0,0.481,15.0,40.0,0.375,17.0,22.0,0.773,19.0,34.0,53.0,29.0,8.0,8.0,15.0,24.0,0.578,0.551,0.370,0.204,34.5,81.0,54.6,55.8,7.2,14.5,11.3,100.0,122.8,127.3,13.0,23.0,0.615,5.0,11.0,0.500,9.0,9.0,1.00,14.0,9.0,20.0,7.0,2.0,7.0,5.0,6.0,34.0,18.0,0.818,0.808,0.769,0.409,44.9,35.9,36.4,27.0,2.4,22.5,20.3,30.4,175.0,135.0,NYK,136.0,1,2023,2023-04-09,True,38.500000,49.300000,2
25540,240.0,43.0,95.0,0.453,13.0,36.0,0.361,31.0,37.0,0.838,17.0,29.0,46.0,23.0,4.0,1.0,10.0,21.0,0.584,0.521,0.379,0.389,34.7,72.5,51.7,53.5,4.0,1.5,8.2,100.0,131.0,137.1,8.0,18.0,0.857,5.0,8.0,0.625,8.0,10.0,1.000,7.0,7.0,10.0,8.0,2.0,1.0,5.0,5.0,27.0,11.0,0.950,0.950,1.000,1.286,28.7,30.2,22.6,24.7,3.6,3.0,20.0,34.0,202.0,143.0,LAC,130.0,0,240.0,51.0,94.0,0.543,13.0,26.0,0.500,21.0,24.0,0.875,11.0,32.0,43.0,31.0,7.0,4.0,7.0,27.0,0.650,0.612,0.277,0.255,27.5,65.3,48.3,60.8,7.1,6.8,6.3,100.0,137.1,131.0,19.0,27.0,0.704,4.0,7.0,0.667,7.0,7.0,1.00,5.0,9.0,11.0,10.0,2.0,3.0,3.0,5.0,47.0,13.0,0.793,0.778,1.000,1.250,48.5,24.8,34.8,57.6,3.0,19.7,33.3,33.7,225.0,140.0,PHO,136.0,1,2023,2023-04-25,False,53.400000,98.800000,2
25621,240.0,40.0,86.0,0.465,8.0,20.0,0.400,23.0,26.0,0.885,8.0,30.0,38.0,20.0,5.0,4.0,6.0,19.0,0.570,0.512,0.233,0.302,21.6,73.2,48.7,50.0,5.5,7.7,5.8,100.0,122.7,124.9,15.0,25.0,0.600,4.0,7.0,0.571,9.0,10.0,1.000,2.0,12.0,14.0,9.0,2.0,3.0,1.0,4.0,40.0,6.0,0.712,0.680,0.500,0.667,13.4,35.1,21.5,36.1,2.8,6.9,33.3,28.2,150.0,133.0,LAL,111.0,1,240.0,41.0,85.0,0.482,12.0,33.0,0.364,19.0,22.0,0.864,11.0,29.0,40.0,25.0,3.0,9.0,8.0,20.0,0.597,0.553,0.388,0.259,26.8,78.4,51.3,61.0,3.3,13.6,7.8,100.0,124.9,122.7,11.0,24.0,0.667,3.0,10.0,0.600,5.0,6.0,1.00,4.0,11.0,14.0,13.0,2.0,3.0,3.0,5.0,30.0,11.0,1.136,0.750,0.700,0.667,11.5,31.5,19.0,47.0,2.5,7.3,20.5,30.6,250.0,129.0,DEN,113.0,0,2023,2023-05-22,False,94.400000,97.300000,2
25555,240.0,29.0,96.0,0.302,12.0,38.0,0.316,15.0,20.0,0.750,14.0,31.0,45.0,19.0,10.0,2.0,14.0,17.0,0.406,0.365,0.396,0.208,24.6,77.5,46.4,65.5,10.0,4.3,11.8,100.0,84.9,124.8,6.0,16.0,0.600,2.0,7.0,0.667,7.0,8.0,1.000,3.0,5.0,6.0,6.0,4.0,1.0,3.0,5.0,16.0,-7.0,0.735,0.700,0.500,0.667,14.2,51.5,25.5,34.4,10.6,8.8,33.3,29.2,132.0,133.0,MEM,85.0,0,240.0,49.0,91.0,0.538,15.0,44.0,0.341,12.0,15.0,0.800,9.0,43.0,52.0,33.0,6.0,15.0,13.0,16.0,0.640,0.621,0.484,0.165,22.5,75.4,53.6,67.3,6.0,25.9,11.8,100.0,124.8,84.9,12.0,17.0,0.706,5.0,9.0,1.000,4.0,4.0,1.00,2.0,13.0,14.0,8.0,2.0,5.0,3.0,4.0,31.0,32.0,0.833,0.853,1.000,0.667,23.2,38.4,24.3,27.2,4.1,16.0,27.3,36.7,154.0,95.0,LAL,125.0,1,2023,2023-04-28,False,64.000000,94.400000,2
25638,240.0,33.0,96.0,0.344,9.0,35.0,0.257,14.0,16.0,0.875,11.0,33.0,44.0,18.0,9.0,7.0,8.0,21.0,0.432,0.391,0.365,0.167,19.3,75.0,43.6,54.5,9.4,12.5,7.2,100.0,92.6,97.8,9.0,20.0,0.450,4.0,9.0,0.444,9.0,11.0,1.000,5.0,7.0,12.0,5.0,3.0,2.0,2.0,5.0,21.0,13.0,0.506,0.462,1.000,0.611,82.8,37.6,46.7,31.4,3.6,12.1,25.0,42.5,102.0,109.0,MIA,89.0,0,240.0,38.0,84.0,0.452,5.0,28.0,0.179,13.0,23.0,0.565,11.0,46.0,57.0,21.0,6.0,7.0,14.0,13.0,0.499,0.482,0.333,0.274,25.0,80.7,56.4,55.3,6.2,11.5,12.9,100.0,97.8,92.6,12.0,17.0,1.000,2.0,7.0,0.333,3.0,6.0,1.00,4.0,15.0,16.0,8.0,2.0,3.0,6.0,4.0,28.0,12.0,1.000,1.000,0.500,1.500,15.5,29.9,18.4,57.2,3.5,26.1,28.6,26.4,202.0,104.0,DEN,94.0,1,2023,2023-06-12,False,71.700000,97.300000,2
25543,265.0,42.0,91.0,0.462,14.0,33.0,0.424,28.0,45.0,0.622,10.0,46.0,56.0,20.0,4.0,1.0,15.0,21.0,0.569,0.538,0.363,0.495,21.7,83.6,55.4,47.6,3.5,1.5,11.9,100.0,109.6,111.4,14.0,27.0,1.000,4.0,10.0,1.000,10.0,23.0,1.000,4.0,16.0,20.0,6.0,1.0,1.0,7.0,5.0,38.0,16.0,1.167,1.167,0.714,0.852,10.9,36.6,24.9,26.7,2.8,1.9,50.0,44.1,231.0,117.0,MIL,126.0,1,265.0,50.0,110.0,0.455,17.0,45.0,0.378,11.0,17.0,0.647,9.0,36.0,45.0,25.0,6.0,5.0,11.0,31.0,0.545,0.532,0.409,0.155,16.4,78.3,44.6,50.0,5.2,8.6,8.6,100.0,111.4,109.6,17.0,33.0,1.000,5.0,12.0,0.500,5.0,9.0,0.80,5.0,12.0,12.0,10.0,2.0,2.0,5.0,6.0,42.0,17.0,1.000,1.000,1.000,0.500,12.2,43.0,19.6,34.1,26.7,4.8,33.3,37.6,206.0,117.0,MIA,128.0,0,2023,2023-04-26,False,78.900000,71.700000,2
25538,240.0,41.0,81.0,0.506,8.0,33.0,0.242,19.0,25.0,0.760,8.0,32.0,40.0,24.0,9.0,4.0,14.0,27.0,0.592,0.556,0.407,0.309,20.5,66.7,46.0,58.5,9.5,7.8,13.2,100.0,115.1,118.2,13.0,27.0,1.000,3.0,9.0,0.429,7.0,9.0,1.000,4.0,11.0,15.0,9.0,2.0,2.0,3.0,6.0,29.0,10.0,1.000,1.000,0.818,1.500,12.2,27.2,20.5,33.2,4.6,4.7,50.0,33.8,134.0,131.0,MIN,109.0,0,240.0,34.0,85.0,0.400,12.0,34.0,0.353,32.0,36.0,0.889,16.0,31.0,47.0,22.0,10.0,3.0,12.0,21.0,0.555,0.471,0.400,0.424,33.3,79.5,54.0,64.7,10.6,6.3,10.6,100.0,118.2,115.1,12.0,29.0,1.000,5.0,9.0,1.000,9.0,10.0,1.00,9.0,9.0,17.0,12.0,2.0,2.0,4.0,5.0,35.0,9.0,1.500,1.500,1.000,2.000,21.5,28.5,22.4,55.3,3.9,5.3,50.0,35.9,139.0,121.0,DEN,112.0,1,2023,2023-04-25,False,52.400000,97.300000,2
25465,240.0,42.0,87.0,0.483,9.0,28.0,0.321,25.0,30.0,0.833,14.0,34.0,48.0,27.0,5.0,4.0,11.0,23.0,0.589,0.534,0.322,0.345,35.9,72.3,55.8,64.3,5.3,7.3,9.9,100.0,124.4,129.7,10.0,19.0,1.000,4.0,10.0,1.000,9.0,11.0,1.000,6.0,12.0,18.0,7.0,2.0,1.0,4.0,5.0,30.0,10.0,1.042,1.000,0.625,1.000,26.5,40.7,33.1,36.5,3.0,5.1,25.8,31.7,166.0,138.0,NOP,118.0,1,240.0,42.0,92.0,0.457,11.0,37.0,0.297,28.0,32.0,0.875,13.0,25.0,38.0,25.0,7.0,5.0,7.0,19.0,0.580,0.516,0.402,0.348,27.7,64.1,44.2,59.5,7.4,8.5,6.2,100.0,129.7,124.4,11.0,22.0,0.667,4.0,8.0,0.500,8.0,8.0,1.00,4.0,5.0,9.0,10.0,3.0,1.0,2.0,5.0,32.0,20.0,0.810,0.714,0.778,1.000,11.3,34.1,15.5,38.4,3.7,7.5,25.0,28.2,173.0,132.0,OKC,123.0,0,2023,2023-04-12,False,62.100000,71.200000,2
25603,240.0,27.0,71.0,0.380,10.0,35.0,0.286,28.0,32.0,0.875,8.0,33.0,41.0,13.0,2.0,9.0,12.0,22.0,0.541,0.451,0.493,0.451,19.5,82.5,50.6,48.1,2.3,16.4,12.4,100.0,104.3,108.8,14.0,22.0,0.636,5.0,10.0,0.500,9.0,10.0,1.000,5.0,9.0,11.0,3.0,1.0,4.0,3.0,5.0,41.0,3.0,0.790,0.750,1.000,1.000,20.5,30.2,22.8,26.3,3.0,30.8,17.2,31.7,146.0,115.0,NYK,92.0,0,240.0,33.0,82.0,0.402,7.0,27.0,0.259,23.0,25.0,0.920,7.0,33.0,40.0,25.0,8.0,2.0,7.0,22.0,0.516,0.445,0.329,0.305,17.5,80.5,49.4,75.8,9.1,5.6,7.0,100.0,108.8,104.3,9.0,22.0,1.000,2.0,7.0,1.000,10.0,11.0,1.00,3.0,7.0,9.0,9.0,3.0,1.0,2.0,4.0,24.0,11.0,1.500,1.500,1.000,0.545,9.2,25.9,13.7,51.5,5.2,4.3,100.0,31.2,273.0,109.0,MIA,96.0,1,2023,2023-05-12,False,74.500000,71.700000,2
25468,240.0,32.0,89.0,0.360,13.0,40.0,0.325,18.0,20.0,0.900,12.0,30.0,42.0,19.0,9.0,6.0,17.0,20.0,0.486,0.433,0.449,0.225,24.0,76.9,47.2,59.4,9.1,11.8,14.8,100.0,95.5,120.7,6.0,19.0,1.000,4.0,8.0,1.000,12.0,12.0,1.000,4.0,6.0,8.0,5.0,3.0,3.0,4.0,4.0,22.0,1.0,1.500,1.500,1.000,0.632,11.8,34.3,15.1,30.1,4.5,8.3,100.0,29.4,300.0,128.0,OKC,95.0,0,240.0,43.0,83.0,0.518,13.0,32.0,0.406,21.0,26.0,0.808,9.0,38.0,47.0,29.0,11.0,8.0,16.0,15.0,0.635,0.596,0.386,0.313,23.1,76.0,52.8,67.4,11.1,16.3,14.5,100.0,120.7,95.5,11.0,19.0,1.000,3.0,8.0,1.000,9.0,14.0,1.00,4.0,9.0,11.0,6.0,3.0,3.0,3.0,5.0,28.0,25.0,1.215,1.250,0.700,1.273,15.1,49.4,27.8,28.7,12.4,10.1,100.0,32.2,250.0,110.0,MIN,120.0,1,2023,2023-04-14,False,71.200000,67.200000,2
25439,240.0,38.0,90.0,0.422,17.0,47.0,0.362,17.0,24.0,0.708,13.0,30.0,43.0,29.0,13.0,1.0,14.0,17.0,0.547,0.517,0.522,0.267,26.0,81.1,49.4,76.3,13.0,2.6,12.2,100.0,109.8,122.7,7.0,15.0,0.583,5.0,11.0,0.667,6.0,7.0,1.000,4.0,5.0,8.0,5.0,3.0,1.0,3.0,4.0,22.0,5.0,0.729,0.750,1.000,1.200,18.9,34.4,25.3,34.2,6.3,8.1,29.1,29.5,150.0,130.0,ORL,110.0,0,240.0,45.0,83.0,0.542,18.0,44.0,0.409,15.0,20.0,0.750,7.0,37.0,44.0,30.0,10.0,3.0,18.0,20.0,0.670,0.651,0.530,0.241,18.9,74.0,50.6,66.7,10.0,7.0,16.4,100.0,122.7,109.8,9.0,17.0,1.000,5.0,11.0,1.000,5.0,6.0,1.00,2.0,5.0,7.0,8.0,2.0,1.0,6.0,4.0,24.0,13.0,1.082,1.143,1.000,2.000,32.8,53.6,30.8,53.3,9.6,10.5,50.0,33.9,179.0,118.0,MIA,123.0,1,2023,2023-04-09,False,49.800000,59.400000,2
25606,240.0,31.0,83.0,0.373,8.0,37.0,0.216,18.0,19.0,0.947,7.0,30.0,37.0,15.0,4.0,7.0,12.0,14.0,0.482,0.422,0.446,0.229,16.3,81.1,46.3,48.4,4.3,13.0,11.6,100.0,94.9,120.8,7.0,18.0,1.000,3.0,7.0,0.500,5.0,6.0,1.000,3.0,7.0,8.0,7.0,2.0,2.0,5.0,3.0,19.0,6.0,1.000,1.000,1.000,1.000,23.0,53.5,37.1,40.0,13.4,23.7,29.6,40.1,200.0,129.0,PHI,88.0,0,240.0,41.0,87.0,0.471,15.0,33.0,0.455,15.0,18.0,0.833,7.0,36.0,43.0,18.0,7.0,7.0,7.0,13.0,0.590,0.557,0.379,0.207,18.9,83.7,53.8,43.9,7.6,15.2,6.9,100.0,120.8,94.9,17.0,28.0,0.607,6.0,10.0,0.600,11.0,14.0,1.00,2.0,13.0,13.0,5.0,2.0,3.0,3.0,3.0,51.0,33.0,0.746,0.714,0.833,0.500,33.6,34.8,31.0,34.6,3.1,9.2,100.0,45.6,237.0,105.0,BOS,112.0,1,2023,2023-05-14,False,84.800000,90.200000,2
25598,240.0,38.0,79.0,0.481,11.0,28.0,0.393,13.0,20.0,0.650,2.0,27.0,29.0,20.0,3.0,5.0,14.0,22.0,0.569,0.551,0.354,0.253,5.6,79.4,41.4,52.6,3.1,8.3,13.8,100.0,102.8,128.5,12.0,19.0,1.000,7.0,9.0,0.778,7.0,7.0,1.000,1.0,6.0,6.0,8.0,1.0,1.0,4.0,4.0,31.0,7.0,0.895,1.000,1.000,2.000,17.4,22.9,17.8,33.2,4.3,10.4,18.8,33.4,147.0,134.0,PHO,100.0,1,240.0,44.0,82.0,0.537,8.0,22.0,0.364,29.0,31.0,0.935,7.0,34.0,41.0,24.0,10.0,3.0,10.0,22.0,0.653,0.585,0.268,0.378,20.6,94.4,58.6,54.5,10.3,5.9,9.5,100.0,128.5,102.8,13.0,18.0,1.000,4.0,7.0,1.000,8.0,8.0,1.00,3.0,7.0,10.0,12.0,4.0,1.0,3.0,4.0,32.0,28.0,1.500,1.500,1.000,4.000,12.0,61.1,31.4,56.0,5.7,3.1,26.6,41.6,300.0,110.0,DEN,125.0,0,2023,2023-05-11,False,47.900000,97.300000,2
25455,240.0,38.0,95.0,0.400,9.0,35.0,0.257,16.0,24.0,0.667,6.0,24.0,30.0,25.0,5.0,3.0,14.0,9.0,0.478,0.447,0.368,0.253,10.9,72.7,34.1,65.8,4.6,6.4,11.7,100.0,92.6,143.9,7.0,18.0,0.667,2.0,9.0,1.000,5.0,5.0,1.000,3.0,6.0,7.0,12.0,3.0,1.0,5.0,2.0,21.0,-16.0,0.660,0.667,0.600,0.800,8.4,30.9,13.5,47.6,3.2,5.2,23.5,33.9,128.0,149.0,POR,101.0,1,240.0,58.0,96.0,0.604,27.0,49.0,0.551,14.0,16.0,0.875,9.0,49.0,58.0,47.0,13.0,6.0,15.0,18.0,0.762,0.745,0.510,0.167,27.3,89.1,65.9,81.0,11.9,10.0,12.7,100.0,143.9,92.6,10.0,15.0,1.000,6.0,11.0,1.000,3.0,4.0,1.00,3.0,6.0,8.0,8.0,5.0,2.0,3.0,4.0,26.0,39.0,1.197,1.500,1.000,2.000,20.6,27.0,21.5,38.6,10.3,8.1,30.0,31.9,222.0,100.0,GSW,157.0,0,2023,2023-04-09,False,34.246017,63.800000,2

In [9]:
"""
Checking for null values in the dataset
"""
stats_df.isnull().sum().sort_values(ascending=False)

mp          0
usg%_opp    0
drb%_opp    0
trb%_opp    0
ast%_opp    0
           ..
orb_max     0
ft%_max     0
fta_max     0
ft_max      0
target      0
Length: 142, dtype: int64

In [10]:
"""
Evaluating the unique occurances in the won column. The win and loss values are the same as expected.
"""
stats_df["won"].value_counts()

False    12820
True     12820
Name: won, dtype: int64

In [11]:
"""
Evaluating the unique occurances in the target column. There is an inbalance between the win and losses because of the 
newly introduced class (2) for the next game
"""
stats_df["target"].value_counts()

0    12806
1    12804
2       30
Name: target, dtype: int64

### We take out the PER values from the stats_df dataset to create a dataset with just the boxscore stats

In [12]:
per = stats_df[['PER_Combined', 'PER_Combined_opp']]

stats_df.drop(columns=['PER_Combined', 'PER_Combined_opp'], inplace=True)
stats_df

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,orb,drb,trb,ast,stl,blk,tov,pf,ts%,efg%,3par,ftr,orb%,drb%,trb%,ast%,stl%,blk%,tov%,usg%,ortg,drtg,fg_max,fga_max,fg%_max,3p_max,3pa_max,3p%_max,ft_max,fta_max,ft%_max,orb_max,drb_max,trb_max,ast_max,stl_max,blk_max,tov_max,pf_max,pts_max,+/-_max,ts%_max,efg%_max,3par_max,ftr_max,orb%_max,drb%_max,trb%_max,ast%_max,stl%_max,blk%_max,tov%_max,usg%_max,ortg_max,drtg_max,team,total,home,mp_opp,fg_opp,fga_opp,fg%_opp,3p_opp,3pa_opp,3p%_opp,ft_opp,fta_opp,ft%_opp,orb_opp,drb_opp,trb_opp,ast_opp,stl_opp,blk_opp,tov_opp,pf_opp,ts%_opp,efg%_opp,3par_opp,ftr_opp,orb%_opp,drb%_opp,trb%_opp,ast%_opp,stl%_opp,blk%_opp,tov%_opp,usg%_opp,ortg_opp,drtg_opp,fg_max_opp,fga_max_opp,fg%_max_opp,3p_max_opp,3pa_max_opp,3p%_max_opp,ft_max_opp,fta_max_opp,ft%_max_opp,orb_max_opp,drb_max_opp,trb_max_opp,ast_max_opp,stl_max_opp,blk_max_opp,tov_max_opp,pf_max_opp,pts_max_opp,+/-_max_opp,ts%_max_opp,efg%_max_opp,3par_max_opp,ftr_max_opp,orb%_max_opp,drb%_max_opp,trb%_max_opp,ast%_max_opp,stl%_max_opp,blk%_max_opp,tov%_max_opp,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won,target
14,240.0,37.0,76.0,0.487,8.0,24.0,0.333,27.0,35.0,0.771,5.0,28.0,33.0,27.0,16.0,5.0,17.0,20.0,0.596,0.539,0.316,0.461,12.5,80.0,44.0,73.0,15.9,9.4,15.7,100.0,108.3,117.2,9.0,15.0,0.800,3.0,7.0,0.500,9.0,12.0,1.00,2.0,6.0,7.0,9.0,5.0,4.0,6.0,4.0,24.0,11.0,1.136,0.800,1.000,1.143,7.2,35.0,16.3,61.0,7.5,11.3,66.7,31.3,239.0,128.0,ATL,109.0,0,240.0,44.0,77.0,0.571,11.0,24.0,0.458,19.0,24.0,0.792,7.0,35.0,42.0,31.0,7.0,2.0,20.0,22.0,0.674,0.643,0.312,0.312,20.0,87.5,56.0,70.5,7.0,3.8,18.6,100.0,117.2,108.3,11.0,17.0,1.000,4.0,6.0,1.000,8.0,8.0,1.0,5.0,8.0,9.0,11.0,2.0,1.0,7.0,4.0,32.0,18.0,1.500,1.500,1.000,0.500,32.5,35.7,21.4,37.0,3.5,3.4,69.4,33.4,270.0,113.0,DAL,118.0,1,2014,2013-10-30,False,1
48,240.0,36.0,77.0,0.468,10.0,23.0,0.435,20.0,31.0,0.645,7.0,30.0,37.0,24.0,7.0,3.0,13.0,12.0,0.563,0.532,0.299,0.403,17.9,75.0,46.8,66.7,7.5,4.6,12.5,100.0,108.9,101.4,9.0,14.0,0.643,5.0,8.0,0.667,8.0,9.0,1.00,3.0,13.0,16.0,12.0,3.0,1.0,3.0,2.0,22.0,20.0,0.708,0.750,0.750,1.000,17.2,50.2,33.9,51.7,4.6,10.3,33.3,25.7,124.0,111.0,ATL,102.0,1,240.0,40.0,88.0,0.455,7.0,23.0,0.304,8.0,14.0,0.571,10.0,32.0,42.0,15.0,5.0,6.0,12.0,25.0,0.504,0.494,0.261,0.159,25.0,82.1,53.2,37.5,5.3,11.1,11.3,100.0,101.4,108.9,14.0,23.0,0.714,3.0,5.0,1.000,3.0,6.0,1.0,3.0,6.0,9.0,4.0,2.0,2.0,4.0,4.0,31.0,14.0,0.830,0.929,1.000,0.857,15.5,31.8,23.6,47.9,3.1,10.0,50.0,37.6,157.0,117.0,TOR,95.0,0,2014,2013-11-01,True,0
81,240.0,40.0,90.0,0.444,9.0,22.0,0.409,14.0,26.0,0.538,10.0,42.0,52.0,26.0,9.0,3.0,11.0,22.0,0.508,0.494,0.244,0.289,17.5,87.5,49.5,65.0,8.7,4.7,9.8,100.0,99.6,101.6,8.0,18.0,0.800,6.0,6.0,1.000,6.0,10.0,0.75,3.0,13.0,16.0,4.0,2.0,1.0,4.0,4.0,22.0,12.0,1.100,1.100,0.857,1.111,19.4,39.1,23.9,28.6,6.1,2.6,22.5,31.1,206.0,109.0,ATL,103.0,0,240.0,38.0,89.0,0.427,9.0,25.0,0.360,20.0,24.0,0.833,6.0,47.0,53.0,27.0,5.0,7.0,13.0,24.0,0.527,0.478,0.281,0.270,12.5,82.5,50.5,71.1,4.8,10.3,11.5,100.0,101.6,99.6,5.0,18.0,1.000,2.0,4.0,0.500,6.0,8.0,1.0,3.0,13.0,13.0,7.0,2.0,3.0,4.0,6.0,18.0,4.0,1.042,1.000,0.800,1.000,14.3,39.5,21.5,34.9,4.9,10.1,33.3,37.1,158.0,108.0,LAL,105.0,1,2014,2013-11-03,False,1
117,240.0,39.0,81.0,0.481,8.0,22.0,0.364,19.0,26.0,0.731,9.0,27.0,36.0,26.0,11.0,7.0,14.0,15.0,0.568,0.531,0.272,0.321,23.7,73.0,48.0,66.7,11.7,14.3,13.2,100.0,111.6,106.3,11.0,19.0,0.750,2.0,5.0,1.000,5.0,8.0,1.00,5.0,8.0,11.0,10.0,4.0,2.0,4.0,4.0,27.0,6.0,0.922,0.875,0.750,0.667,17.9,33.8,20.9,56.0,6.1,17.0,38.1,30.2,136.0,116.0,ATL,105.0,0,240.0,35.0,80.0,0.438,10.0,31.0,0.323,20.0,21.0,0.952,10.0,29.0,39.0,22.0,10.0,4.0,18.0,26.0,0.560,0.500,0.388,0.263,27.0,76.3,52.0,62.9,10.6,6.8,16.8,100.0,106.3,111.6,8.0,17.0,0.500,3.0,7.0,0.429,9.0,9.0,1.0,2.0,8.0,9.0,5.0,3.0,2.0,4.0,5.0,26.0,4.0,0.689,0.650,0.800,1.000,11.4,32.6,18.6,39.8,8.0,5.8,37.2,39.6,133.0,117.0,SAC,100.0,1,2014,2013-11-05,True,0
142,240.0,43.0,94.0,0.457,8.0,26.0,0.308,13.0,19.0,0.684,13.0,33.0,46.0,31.0,11.0,9.0,11.0,23.0,0.523,0.500,0.277,0.202,27.1,76.7,50.5,72.1,11.2,14.8,9.7,100.0,109.4,111.4,10.0,21.0,0.667,2.0,5.0,0.667,7.0,11.0,1.00,3.0,8.0,10.0,11.0,3.0,4.0,4.0,4.0,29.0,13.0,0.735,0.733,1.000,0.733,16.1,53.9,33.9,46.2,6.4,9.0,21.6,30.7,155.0,123.0,ATL,107.0,0,240.0,42.0,86.0,0.488,14.0,25.0,0.560,11.0,17.0,0.647,10.0,35.0,45.0,28.0,4.0,8.0,16.0,18.0,0.583,0.570,0.291,0.198,23.3,72.9,49.5,66.7,4.1,11.8,14.6,100.0,111.4,109.4,9.0,16.0,0.750,4.0,6.0,1.000,4.0,5.0,0.8,4.0,7.0,9.0,8.0,1.0,2.0,3.0,3.0,23.0,17.0,0.806,0.786,0.714,1.250,17.0,31.5,19.0,46.4,2.4,13.3,29.1,33.1,150.0,114.0,DEN,109.0,1,2014,2013-11-07,False,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25348,240.0,39.0,79.0,0.494,16.0,37.0,0.432,15.0,18.0,0.833,5.0,33.0,38.0,26.0,9.0,5.0,18.0,18.0,0.627,0.595,0.468,0.228,13.5,82.5,49.4,66.7,9.1,8.9,17.2,100.0,110.8,119.9,10.0,19.0,1.000,4.0,11.0,0.800,5.0,5.0,1.00,3.0,6.0,7.0,7.0,4.0,2.0,8.0,4.0,29.0,9.0,1.042,1.000,0.667,1.000,15.9,34.1,17.8,90.1,6.2,24.4,50.0,31.7,241.0,128.0,WAS,109.0,0,240.0,46.0,88.0,0.523,13.0,32.0,0.406,13.0,18.0,0.722,7.0,32.0,39.0,31.0,12.0,4.0,11.0,17.0,0.615,0.597,0.364,0.205,17.5,86.5,50.6,67.4,12.2,9.5,10.3,100.0,119.9,110.8,11.0,20.0,0.800,6.0,11.0,0.545,4.0,5.0,1.0,4.0,7.0,11.0,8.0,3.0,1.0,5.0,5.0,27.0,19.0,0.820,0.800,1.000,0.600,18.5,38.7,26.5,30.1,4.4,5.2,66.7,31.2,192.0,120.0,NYK,118.0,1,2023,2023-04-02,False,0
25367,240.0,50.0,99.0,0.505,13.0,27.0,0.481,15.0,21.0,0.714,9.0,33.0,42.0,30.0,7.0,4.0,9.0,21.0,0.591,0.571,0.273,0.212,17.0,73.3,42.9,60.0,6.4,8.0,7.7,100.0,117.9,129.0,9.0,17.0,0.800,5.0,6.0,1.000,6.0,6.0,1.00,2.0,7.0,9.0,9.0,2.0,2.0,3.0,5.0,24.0,7.0,0.800,0.800,0.600,1.250,8.6,28.5,16.4,41.6,3.9,5.3,28.6,34.4,153.0,135.0,WAS,128.0,1,240.0,50.0,92.0,0.543,23.0,42.0,0.548,17.0,29.0,0.586,12.0,44.0,56.0,33.0,6.0,7.0,18.0,19.0,0.668,0.668,0.457,0.315,26.7,83.0,57.1,66.0,5.5,9.7,14.7,100.0,129.0,117.9,12.0,21.0,0.750,5.0,9.0,0.800,10.0,17.0,1.0,5.0,15.0,20.0,10.0,2.0,5.0,8.0,4.0,28.0,24.0,1.125,1.125,1.000,1.063,17.1,43.7,31.5,51.7,3.2,11.0,33.3,37.5,208.0,126.0,MIL,140.0,0,2023,2023-04-04,False,0
25376,240.0,45.0,94.0,0.479,6.0,28.0,0.214,20.0,26.0,0.769,12.0,27.0,39.0,23.0,10.0,9.0,14.0,26.0,0.550,0.511,0.298,0.277,25.0,69.2,44.8,51.1,9.6,16.7,11.7,100.0,111.6,129.0,8.0,18.0,0.833,2.0,8.0,0.667,9.0,9.0,1.00,4.0,7.0,10.0,6.0,4.0,3.0,4.0,4.0,25.0,2.0,1.017,1.000,0.667,0.900,17.6,32.4,24.2,25.4,6.3,9.0,50.0,29.9,179.0,139.0,WAS,116.0,0,240.0,43.0,84.0,0.512,13.0,30.0,0.433,35.0,40.0,0.875,12.0,36.0,48.0,30.0,10.0,5.0,16.0,23.0,0.659,0.589,0.357,0.476,30.8,75.0,55.2,69.8,9.6,7.6,13.6,100.0,129.0,111.6,8.0,13.0,1.000,4.0,6.0,1.000,16.0,18.0,1.0,4.0,8.0,8.0,16.0,3.0,3.0,4.0,5.0,25.0,19.0,1.031,1.000,1.000,1.800,40.8,66.3,54.9,52.4,15.3,14.4,33.3,40.6,206.0,121.0,ATL,134.0,1,2023,2023-04-05,False,1
25415,240.0,39.0,84.0,0.464,7.0,33.0,0.212,29.0,37.0,0.784,12.0,38.0,50.0,23.0,4.0,3.0,16.0,18.0,0.568,0.506,0.393,0.440,26.7,73.1,51.5,59.0,3.9,5.9,13.8,100.0,111.3,105.4,9.0,20.0,0.900,3.0,9.0,0.500,6.0,10.0,1.00,4.0,7.0,9.0,4.0,3.0,1.0,3.0,5.0,22.0,25.0,0.935,0.900,0.833,3.333,19.4,32.7,22.5,36.4,6.4,4.0,28.8,24.6,164.0,112.0,WAS,114.0,1,240.0,43.0,98.0,0.439,15.0,47.0,0.319,7.0,12.0,0.583,14.0,33.0,47.0,26.0,7.0,4.0,16.0,29.0,0.523,0.515,0.480,0.122,26.9,73.3,48.5,60.5,6.8,7.8,13.4,100.0,105.4,111.3,11.0,24.0,0.800,7.0,16.0,0.667,3.0,4.0,1.0,4.0,5.0,9.0,8.0,2.0,2.0,3.0,6.0,30.0,18.0,0.814,0.800,0.750,1.000,17.1,24.8,17.3,47.8,3.6,5.8,27.3,44.5,149.0,117.0,MIA,108.0,0,2023,2023-04-07,True,0
25459,240.0,41.0,97.0,0.423,14.0,45.0,0.311,13.0,21.0,0.619,14.0,37.0,51.0,28.0,11.0,5.0,12.0,21.0,0.513,0.495,0.464,0.216,26.9,74.0,50.0,68.3,10.7,7.2,10.1,100.0,106.5,111.4,9.0,20.0,0.750,5.0,15.0,0.714,3.0,4.0,1.00,7.0,10.0,14.0,8.0,2.0,2.0,4.0,4.0,22.0,4.0,1.066,1.063,0.875,0.500,16.9,21.1,17.3,29.0,3.2,6.4,28.8,27.9,196.0,116.0,WAS,109.0,1,240.0,44.0,90.0,0.489,6.0,21.0,0.286,20.0,28.0,0.714,13.0,38.0,51.0,24.0,8.0,6.0,15.0,15.0,0.557,0.522,0.233,0.311,26.0,73.1,50.0,54.5,7.8,11.5,12.8,100.0,111.4,106.5,6.0,12.0,0.714,2.0,3.0,1.000,7.0,8.0,1.0,3.0,9.0,12.0,6.0,2.0,2.0,4.0,3.0,20.0,10.0,0.689,0.800,0.667,0.727,22.8,35.3,24.0,34.1,4.5,7.8,40.0,27.3,136.0,117.0,HOU,114.0,0,2023,2023-04-09,False,2

## Recent Performance Metrics: 
Calculate performance metrics for each team based on their recent games, such as average points scored, average points allowed, shooting percentage, three-point percentage, free-throw percentage, and rebounding rates. This can provide insights into the current form and momentum of the teams.

In [13]:
# Assuming you have the stats_df DataFrame with 'team', 'season', 'date', 'total', 'total_opp', 'fg', 'fga', '3p', '3pa', 'ft', 'fta', 'oreb', 'dreb', and other relevant columns

# Define a function to calculate recent performance metrics for each team
def calculate_recent_performance_metrics(row, stats_df, num_recent_games=5):
    team = row['team']
    season = row['season']
    current_date = row['date']

    # Get the recent games for the team in the same season, excluding the current game
    recent_games = stats_df[(stats_df['team'] == team) & (stats_df['season'] == season) & (stats_df['date'] < current_date)].tail(num_recent_games)

    # Calculate average points scored and allowed in recent games
    if len(recent_games) > 0:
        average_points_scored = recent_games['total'].mean()
        average_points_allowed = recent_games['total_opp'].mean()
    else:
        average_points_scored = 0.0
        average_points_allowed = 0.0

    # Calculate shooting percentages in recent games
    if recent_games['fga'].sum() == 0:
        shooting_percentage = 0.0
    else:
        shooting_percentage = recent_games['fg'].sum() / recent_games['fga'].sum()

    if recent_games['3pa'].sum() == 0:
        three_point_percentage = 0.0
    else:
        three_point_percentage = recent_games['3p'].sum() / recent_games['3pa'].sum()

    if recent_games['fta'].sum() == 0:
        free_throw_percentage = 0.0
    else:
        free_throw_percentage = recent_games['ft'].sum() / recent_games['fta'].sum()

    # Calculate rebounding rates in recent games
    total_rebounds = recent_games['orb'].sum() + recent_games['drb'].sum()
    if total_rebounds == 0:
        offensive_rebound_rate = 0.0
        defensive_rebound_rate = 0.0
    else:
        offensive_rebound_rate = recent_games['orb'].sum() / total_rebounds
        defensive_rebound_rate = recent_games['drb'].sum() / total_rebounds

    return average_points_scored, average_points_allowed, shooting_percentage, three_point_percentage, free_throw_percentage, offensive_rebound_rate, defensive_rebound_rate

# Calculate recent performance metrics for each game and add them as new columns
stats_df[['avg_points_scored', 'avg_points_allowed', 'shooting_percentage', 'three_point_percentage', 'free_throw_percentage', 'offensive_rebound_rate', 'defensive_rebound_rate']] = stats_df.apply(lambda row: pd.Series(calculate_recent_performance_metrics(row, stats_df)), axis=1)

# Print the updated DataFrame with the new features
stats_df

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,orb,drb,trb,ast,stl,blk,tov,pf,ts%,efg%,3par,ftr,orb%,drb%,trb%,ast%,stl%,blk%,tov%,usg%,ortg,drtg,fg_max,fga_max,fg%_max,3p_max,3pa_max,3p%_max,ft_max,fta_max,ft%_max,orb_max,drb_max,trb_max,ast_max,stl_max,blk_max,tov_max,pf_max,pts_max,+/-_max,ts%_max,efg%_max,3par_max,ftr_max,orb%_max,drb%_max,trb%_max,ast%_max,stl%_max,blk%_max,tov%_max,usg%_max,ortg_max,drtg_max,team,total,home,mp_opp,fg_opp,fga_opp,fg%_opp,3p_opp,3pa_opp,3p%_opp,ft_opp,fta_opp,ft%_opp,orb_opp,drb_opp,trb_opp,ast_opp,stl_opp,blk_opp,tov_opp,pf_opp,ts%_opp,efg%_opp,3par_opp,ftr_opp,orb%_opp,drb%_opp,trb%_opp,ast%_opp,stl%_opp,blk%_opp,tov%_opp,usg%_opp,ortg_opp,drtg_opp,fg_max_opp,fga_max_opp,fg%_max_opp,3p_max_opp,3pa_max_opp,3p%_max_opp,ft_max_opp,fta_max_opp,ft%_max_opp,orb_max_opp,drb_max_opp,trb_max_opp,ast_max_opp,stl_max_opp,blk_max_opp,tov_max_opp,pf_max_opp,pts_max_opp,+/-_max_opp,ts%_max_opp,efg%_max_opp,3par_max_opp,ftr_max_opp,orb%_max_opp,drb%_max_opp,trb%_max_opp,ast%_max_opp,stl%_max_opp,blk%_max_opp,tov%_max_opp,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won,target,avg_points_scored,avg_points_allowed,shooting_percentage,three_point_percentage,free_throw_percentage,offensive_rebound_rate,defensive_rebound_rate
14,240.0,37.0,76.0,0.487,8.0,24.0,0.333,27.0,35.0,0.771,5.0,28.0,33.0,27.0,16.0,5.0,17.0,20.0,0.596,0.539,0.316,0.461,12.5,80.0,44.0,73.0,15.9,9.4,15.7,100.0,108.3,117.2,9.0,15.0,0.800,3.0,7.0,0.500,9.0,12.0,1.00,2.0,6.0,7.0,9.0,5.0,4.0,6.0,4.0,24.0,11.0,1.136,0.800,1.000,1.143,7.2,35.0,16.3,61.0,7.5,11.3,66.7,31.3,239.0,128.0,ATL,109.0,0,240.0,44.0,77.0,0.571,11.0,24.0,0.458,19.0,24.0,0.792,7.0,35.0,42.0,31.0,7.0,2.0,20.0,22.0,0.674,0.643,0.312,0.312,20.0,87.5,56.0,70.5,7.0,3.8,18.6,100.0,117.2,108.3,11.0,17.0,1.000,4.0,6.0,1.000,8.0,8.0,1.0,5.0,8.0,9.0,11.0,2.0,1.0,7.0,4.0,32.0,18.0,1.500,1.500,1.000,0.500,32.5,35.7,21.4,37.0,3.5,3.4,69.4,33.4,270.0,113.0,DAL,118.0,1,2014,2013-10-30,False,1,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000
48,240.0,36.0,77.0,0.468,10.0,23.0,0.435,20.0,31.0,0.645,7.0,30.0,37.0,24.0,7.0,3.0,13.0,12.0,0.563,0.532,0.299,0.403,17.9,75.0,46.8,66.7,7.5,4.6,12.5,100.0,108.9,101.4,9.0,14.0,0.643,5.0,8.0,0.667,8.0,9.0,1.00,3.0,13.0,16.0,12.0,3.0,1.0,3.0,2.0,22.0,20.0,0.708,0.750,0.750,1.000,17.2,50.2,33.9,51.7,4.6,10.3,33.3,25.7,124.0,111.0,ATL,102.0,1,240.0,40.0,88.0,0.455,7.0,23.0,0.304,8.0,14.0,0.571,10.0,32.0,42.0,15.0,5.0,6.0,12.0,25.0,0.504,0.494,0.261,0.159,25.0,82.1,53.2,37.5,5.3,11.1,11.3,100.0,101.4,108.9,14.0,23.0,0.714,3.0,5.0,1.000,3.0,6.0,1.0,3.0,6.0,9.0,4.0,2.0,2.0,4.0,4.0,31.0,14.0,0.830,0.929,1.000,0.857,15.5,31.8,23.6,47.9,3.1,10.0,50.0,37.6,157.0,117.0,TOR,95.0,0,2014,2013-11-01,True,0,109.000000,118.0,0.486842,0.333333,0.771429,0.151515,0.848485
81,240.0,40.0,90.0,0.444,9.0,22.0,0.409,14.0,26.0,0.538,10.0,42.0,52.0,26.0,9.0,3.0,11.0,22.0,0.508,0.494,0.244,0.289,17.5,87.5,49.5,65.0,8.7,4.7,9.8,100.0,99.6,101.6,8.0,18.0,0.800,6.0,6.0,1.000,6.0,10.0,0.75,3.0,13.0,16.0,4.0,2.0,1.0,4.0,4.0,22.0,12.0,1.100,1.100,0.857,1.111,19.4,39.1,23.9,28.6,6.1,2.6,22.5,31.1,206.0,109.0,ATL,103.0,0,240.0,38.0,89.0,0.427,9.0,25.0,0.360,20.0,24.0,0.833,6.0,47.0,53.0,27.0,5.0,7.0,13.0,24.0,0.527,0.478,0.281,0.270,12.5,82.5,50.5,71.1,4.8,10.3,11.5,100.0,101.6,99.6,5.0,18.0,1.000,2.0,4.0,0.500,6.0,8.0,1.0,3.0,13.0,13.0,7.0,2.0,3.0,4.0,6.0,18.0,4.0,1.042,1.000,0.800,1.000,14.3,39.5,21.5,34.9,4.9,10.1,33.3,37.1,158.0,108.0,LAL,105.0,1,2014,2013-11-03,False,1,105.500000,106.5,0.477124,0.382979,0.712121,0.171429,0.828571
117,240.0,39.0,81.0,0.481,8.0,22.0,0.364,19.0,26.0,0.731,9.0,27.0,36.0,26.0,11.0,7.0,14.0,15.0,0.568,0.531,0.272,0.321,23.7,73.0,48.0,66.7,11.7,14.3,13.2,100.0,111.6,106.3,11.0,19.0,0.750,2.0,5.0,1.000,5.0,8.0,1.00,5.0,8.0,11.0,10.0,4.0,2.0,4.0,4.0,27.0,6.0,0.922,0.875,0.750,0.667,17.9,33.8,20.9,56.0,6.1,17.0,38.1,30.2,136.0,116.0,ATL,105.0,0,240.0,35.0,80.0,0.438,10.0,31.0,0.323,20.0,21.0,0.952,10.0,29.0,39.0,22.0,10.0,4.0,18.0,26.0,0.560,0.500,0.388,0.263,27.0,76.3,52.0,62.9,10.6,6.8,16.8,100.0,106.3,111.6,8.0,17.0,0.500,3.0,7.0,0.429,9.0,9.0,1.0,2.0,8.0,9.0,5.0,3.0,2.0,4.0,5.0,26.0,4.0,0.689,0.650,0.800,1.000,11.4,32.6,18.6,39.8,8.0,5.8,37.2,39.6,133.0,117.0,SAC,100.0,1,2014,2013-11-05,True,0,104.666667,106.0,0.465021,0.391304,0.663043,0.180328,0.819672
142,240.0,43.0,94.0,0.457,8.0,26.0,0.308,13.0,19.0,0.684,13.0,33.0,46.0,31.0,11.0,9.0,11.0,23.0,0.523,0.500,0.277,0.202,27.1,76.7,50.5,72.1,11.2,14.8,9.7,100.0,109.4,111.4,10.0,21.0,0.667,2.0,5.0,0.667,7.0,11.0,1.00,3.0,8.0,10.0,11.0,3.0,4.0,4.0,4.0,29.0,13.0,0.735,0.733,1.000,0.733,16.1,53.9,33.9,46.2,6.4,9.0,21.6,30.7,155.0,123.0,ATL,107.0,0,240.0,42.0,86.0,0.488,14.0,25.0,0.560,11.0,17.0,0.647,10.0,35.0,45.0,28.0,4.0,8.0,16.0,18.0,0.583,0.570,0.291,0.198,23.3,72.9,49.5,66.7,4.1,11.8,14.6,100.0,111.4,109.4,9.0,16.0,0.750,4.0,6.0,1.000,4.0,5.0,0.8,4.0,7.0,9.0,8.0,1.0,2.0,3.0,3.0,23.0,17.0,0.806,0.786,0.714,1.250,17.0,31.5,19.0,46.4,2.4,13.3,29.1,33.1,150.0,114.0,DEN,109.0,1,2014,2013-11-07,False,1,104.750000,104.5,0.469136,0.384615,0.677966,0.196203,0.803797
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25348,240.0,39.0,79.0,0.494,16.0,37.0,0.432,15.0,18.0,0.833,5.0,33.0,38.0,26.0,9.0,5.0,18.0,18.0,0.627,0.595,0.468,0.228,13.5,82.5,49.4,66.7,9.1,8.9,17.2,100.0,110.8,119.9,10.0,19.0,1.000,4.0,11.0,0.800,5.0,5.0,1.00,3.0,6.0,7.0,7.0,4.0,2.0,8.0,4.0,29.0,9.0,1.042,1.000,0.667,1.000,15.9,34.1,17.8,90.1,6.2,24.4,50.0,31.7,241.0,128.0,WAS,109.0,0,240.0,46.0,88.0,0.523,13.0,32.0,0.406,13.0,18.0,0.722,7.0,32.0,39.0,31.0,12.0,4.0,11.0,17.0,0.615,0.597,0.364,0.205,17.5,86.5,50.6,67.4,12.2,9.5,10.3,100.0,119.9,110.8,11.0,20.0,0.800,6.0,11.0,0.545,4.0,5.0,1.0,4.0,7.0,11.0,8.0,3.0,1.0,5.0,5.0,27.0,19.0,0.820,0.800,1.000,0.600,18.5,38.7,26.5,30.1,4.4,5.2,66.7,31.2,192.0,120.0,NYK,118.0,1,2023,2023-04-02,False,0,117.200000,117.8,0.520455,0.360248,0.714286,0.189055,0.810945
25367,240.0,50.0,99.0,0.505,13.0,27.0,0.481,15.0,21.0,0.714,9.0,33.0,42.0,30.0,7.0,4.0,9.0,21.0,0.591,0.571,0.273,0.212,17.0,73.3,42.9,60.0,6.4,8.0,7.7,100.0,117.9,129.0,9.0,17.0,0.800,5.0,6.0,1.000,6.0,6.0,1.00,2.0,7.0,9.0,9.0,2.0,2.0,3.0,5.0,24.0,7.0,0.800,0.800,0.600,1.250,8.6,28.5,16.4,41.6,3.9,5.3,28.6,34.4,153.0,135.0,WAS,128.0,1,240.0,50.0,92.0,0.543,23.0,42.0,0.548,17.0,29.0,0.586,12.0,44.0,56.0,33.0,6.0,7.0,18.0,19.0,0.668,0.668,0.457,0.315,26.7,83.0,57.1,66.0,5.5,9.7,14.7,100.0,129.0,117.9,12.0,21.0,0.750,5.0,9.0,0.800,10.0,17.0,1.0,5.0,15.0,20.0,10.0,2.0,5.0,8.0,4.0,28.0,24.0,1.125,1.125,1.000,1.063,17.1,43.7,31.5,51.7,3.2,11.0,33.3,37.5,208.0,126.0,MIL,140.0,0,2023,2023-04-04,False,0,116.600000,117.0,0.518349,0.385542,0.720430,0.189320,0.810680
25376,240.0,45.0,94.0,0.479,6.0,28.0,0.214,20.0,26.0,0.769,12.0,27.0,39.0,23.0,10.0,9.0,14.0,26.0,0.550,0.511,0.298,0.277,25.0,69.2,44.8,51.1,9.6,16.7,11.7,100.0,111.6,129.0,8.0,18.0,0.833,2.0,8.0,0.667,9.0,9.0,1.00,4.0,7.0,10.0,6.0,4.0,3.0,4.0,4.0,25.0,2.0,1.017,1.000,0.667,0.900,17.6,32.4,24.2,25.4,6.3,9.0,50.0,29.9,179.0,139.0,WAS,116.0,0,240.0,43.0,84.0,0.512,13.0,30.0,0.433,35.0,40.0,0.875,12.0,36.0,48.0,30.0,10.0,5.0,16.0,23.0,0.659,0.589,0.357,0.476,30.8,75.0,55.2,69.8,9.6,7.6,13.6,100.0,129.0,111.6,8.0,13.0,1.000,4.0,6.0,1.000,16.0,18.0,1.0,4.0,8.0,8.0,16.0,3.0,3.0,4.0,5.0,25.0,19.0,1.031,1.000,1.000,1.800,40.8,66.3,54.9,52.4,15.3,14.4,33.3,40.6,206.0,121.0,ATL,134.0,1,2023,2023-04-05,False,1,121.400000,121.4,0.517857,0.437126,0.714286,0.180095,0.819905
25415,240.0,39.0,84.0,0.464,7.0,33.0,0.212,29.0,37.0,0.784,12.0,38.0,50.0,23.0,4.0,3.0,16.0,18.0,0.568,0.506,0.393,0.440,26.7,73.1,51.5,59.0,3.9,5.9,13.8,100.0,111.3,105.4,9.0,20.0,0.900,3.0,9.0,0.500,6.0,10.0,1.00,4.0,7.0,9.0,4.0,3.0,1.0,3.0,5.0,22.0,25.0,0.935,0.900,0.833,3.333,19.4,32.7,22.5,36.4,6.4,4.0,28.8,24.6,164.0,112.0,WAS,114.0,1,240.0,43.0,98.0,0.439,15.0,47.0,0.319,7.0,12.0,0.583,14.0,33.0,47.0,26.0,7.0,4.0,16.0,29.0,0.523,0.515,0.480,0.122,26.9,73.3,48.5,60.5,6.8,7.8,13.4,100.0,105.4,111.3,11.0,24.0,0.800,7.0,16.0,0.667,3.0,4.0,1.0,4.0,5.0,9.0,8.0,2.0,2.0,3.0,6.0,30.0,18.0,0.814,0.800,0.750,1.000,17.1,24.8,17.3,47.8,3.6,5.8,27.3,44.5,149.0,117.0,MIA,108.0,0,2023,2023-04-07,True,0,117.400000,123.4,0.494530,0.387879,0.724490,0.212560,0.787440
25459,240.0,41.0,97.0,0.423,14.0,45.0,0.311,13.0,21.0,0.619,14.0,37.0,51.0,28.0,11.0,5.0,12.0,21.0,0.513,0.495,0.464,0.216,26.9,74.0,50.0,68.3,10.7,7.2,10.1,100.0,106.5,111.4,9.0,20.0,0.750,5.0,15.0,0.714,3.0,4.0,1.00,7.0,10.0,14.0,8.0,2.0,2.0,4.0,4.0,22.0,4.0,1.066,1.063,0.875,0.500,16.9,21.1,17.3,29.0,3.2,6.4,28.8,27.9,196.0,116.0,WAS,109.0,1,240.0,44.0,90.0,0.489,6.0,21.0,0.286,20.0,28.0,0.714,13.0,38.0,51.0,24.0,8.0,6.0,15.0,15.0,0.557,0.522,0.233,0.311,26.0,73.1,50.0,54.5,7.8,11.5,12.8,100.0,111.4,106.5,6.0,12.0,0.714,2.0,3.0,1.000,7.0,8.0,1.0,3.0,9.0,12.0,6.0,2.0,2.0,4.0,3.0,20.0,10.0,0.689,0.800,0.667,0.727,22.8,35.3,24.0,34.1,4.5,7.8,40.0,27.3,136.0,117.0,HOU,114.0,0,2023,2023-04-09,False,2,119.400000,122.2,0.498901,0.339506,0.765217,0.207547,0.792453

## Point Differentials: 
Calculate the point differentials (score difference) for each team in previous games. Point differentials can provide insights into team strength

In [14]:
# Assuming you have the stats_df DataFrame with 'team', 'team_opp', 'season', 'total', and 'total_opp' columns

# Calculate the point differentials for each game
stats_df['point_differential'] = stats_df['total'] - stats_df['total_opp']

# Group the data by team and season
team_season_group = stats_df.groupby(['team', 'season'])

# Calculate the cumulative point differentials for each team in previous games
stats_df['cumulative_point_differential'] = team_season_group['point_differential'].cumsum()

# Print the updated DataFrame with the new features
stats_df

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,orb,drb,trb,ast,stl,blk,tov,pf,ts%,efg%,3par,ftr,orb%,drb%,trb%,ast%,stl%,blk%,tov%,usg%,ortg,drtg,fg_max,fga_max,fg%_max,3p_max,3pa_max,3p%_max,ft_max,fta_max,ft%_max,orb_max,drb_max,trb_max,ast_max,stl_max,blk_max,tov_max,pf_max,pts_max,+/-_max,ts%_max,efg%_max,3par_max,ftr_max,orb%_max,drb%_max,trb%_max,ast%_max,stl%_max,blk%_max,tov%_max,usg%_max,ortg_max,drtg_max,team,total,home,mp_opp,fg_opp,fga_opp,fg%_opp,3p_opp,3pa_opp,3p%_opp,ft_opp,fta_opp,ft%_opp,orb_opp,drb_opp,trb_opp,ast_opp,stl_opp,blk_opp,tov_opp,pf_opp,ts%_opp,efg%_opp,3par_opp,ftr_opp,orb%_opp,drb%_opp,trb%_opp,ast%_opp,stl%_opp,blk%_opp,tov%_opp,usg%_opp,ortg_opp,drtg_opp,fg_max_opp,fga_max_opp,fg%_max_opp,3p_max_opp,3pa_max_opp,3p%_max_opp,ft_max_opp,fta_max_opp,ft%_max_opp,orb_max_opp,drb_max_opp,trb_max_opp,ast_max_opp,stl_max_opp,blk_max_opp,tov_max_opp,pf_max_opp,pts_max_opp,+/-_max_opp,ts%_max_opp,efg%_max_opp,3par_max_opp,ftr_max_opp,orb%_max_opp,drb%_max_opp,trb%_max_opp,ast%_max_opp,stl%_max_opp,blk%_max_opp,tov%_max_opp,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won,target,avg_points_scored,avg_points_allowed,shooting_percentage,three_point_percentage,free_throw_percentage,offensive_rebound_rate,defensive_rebound_rate,point_differential,cumulative_point_differential
14,240.0,37.0,76.0,0.487,8.0,24.0,0.333,27.0,35.0,0.771,5.0,28.0,33.0,27.0,16.0,5.0,17.0,20.0,0.596,0.539,0.316,0.461,12.5,80.0,44.0,73.0,15.9,9.4,15.7,100.0,108.3,117.2,9.0,15.0,0.800,3.0,7.0,0.500,9.0,12.0,1.00,2.0,6.0,7.0,9.0,5.0,4.0,6.0,4.0,24.0,11.0,1.136,0.800,1.000,1.143,7.2,35.0,16.3,61.0,7.5,11.3,66.7,31.3,239.0,128.0,ATL,109.0,0,240.0,44.0,77.0,0.571,11.0,24.0,0.458,19.0,24.0,0.792,7.0,35.0,42.0,31.0,7.0,2.0,20.0,22.0,0.674,0.643,0.312,0.312,20.0,87.5,56.0,70.5,7.0,3.8,18.6,100.0,117.2,108.3,11.0,17.0,1.000,4.0,6.0,1.000,8.0,8.0,1.0,5.0,8.0,9.0,11.0,2.0,1.0,7.0,4.0,32.0,18.0,1.500,1.500,1.000,0.500,32.5,35.7,21.4,37.0,3.5,3.4,69.4,33.4,270.0,113.0,DAL,118.0,1,2014,2013-10-30,False,1,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,-9.0,-9.0
48,240.0,36.0,77.0,0.468,10.0,23.0,0.435,20.0,31.0,0.645,7.0,30.0,37.0,24.0,7.0,3.0,13.0,12.0,0.563,0.532,0.299,0.403,17.9,75.0,46.8,66.7,7.5,4.6,12.5,100.0,108.9,101.4,9.0,14.0,0.643,5.0,8.0,0.667,8.0,9.0,1.00,3.0,13.0,16.0,12.0,3.0,1.0,3.0,2.0,22.0,20.0,0.708,0.750,0.750,1.000,17.2,50.2,33.9,51.7,4.6,10.3,33.3,25.7,124.0,111.0,ATL,102.0,1,240.0,40.0,88.0,0.455,7.0,23.0,0.304,8.0,14.0,0.571,10.0,32.0,42.0,15.0,5.0,6.0,12.0,25.0,0.504,0.494,0.261,0.159,25.0,82.1,53.2,37.5,5.3,11.1,11.3,100.0,101.4,108.9,14.0,23.0,0.714,3.0,5.0,1.000,3.0,6.0,1.0,3.0,6.0,9.0,4.0,2.0,2.0,4.0,4.0,31.0,14.0,0.830,0.929,1.000,0.857,15.5,31.8,23.6,47.9,3.1,10.0,50.0,37.6,157.0,117.0,TOR,95.0,0,2014,2013-11-01,True,0,109.000000,118.0,0.486842,0.333333,0.771429,0.151515,0.848485,7.0,-2.0
81,240.0,40.0,90.0,0.444,9.0,22.0,0.409,14.0,26.0,0.538,10.0,42.0,52.0,26.0,9.0,3.0,11.0,22.0,0.508,0.494,0.244,0.289,17.5,87.5,49.5,65.0,8.7,4.7,9.8,100.0,99.6,101.6,8.0,18.0,0.800,6.0,6.0,1.000,6.0,10.0,0.75,3.0,13.0,16.0,4.0,2.0,1.0,4.0,4.0,22.0,12.0,1.100,1.100,0.857,1.111,19.4,39.1,23.9,28.6,6.1,2.6,22.5,31.1,206.0,109.0,ATL,103.0,0,240.0,38.0,89.0,0.427,9.0,25.0,0.360,20.0,24.0,0.833,6.0,47.0,53.0,27.0,5.0,7.0,13.0,24.0,0.527,0.478,0.281,0.270,12.5,82.5,50.5,71.1,4.8,10.3,11.5,100.0,101.6,99.6,5.0,18.0,1.000,2.0,4.0,0.500,6.0,8.0,1.0,3.0,13.0,13.0,7.0,2.0,3.0,4.0,6.0,18.0,4.0,1.042,1.000,0.800,1.000,14.3,39.5,21.5,34.9,4.9,10.1,33.3,37.1,158.0,108.0,LAL,105.0,1,2014,2013-11-03,False,1,105.500000,106.5,0.477124,0.382979,0.712121,0.171429,0.828571,-2.0,-4.0
117,240.0,39.0,81.0,0.481,8.0,22.0,0.364,19.0,26.0,0.731,9.0,27.0,36.0,26.0,11.0,7.0,14.0,15.0,0.568,0.531,0.272,0.321,23.7,73.0,48.0,66.7,11.7,14.3,13.2,100.0,111.6,106.3,11.0,19.0,0.750,2.0,5.0,1.000,5.0,8.0,1.00,5.0,8.0,11.0,10.0,4.0,2.0,4.0,4.0,27.0,6.0,0.922,0.875,0.750,0.667,17.9,33.8,20.9,56.0,6.1,17.0,38.1,30.2,136.0,116.0,ATL,105.0,0,240.0,35.0,80.0,0.438,10.0,31.0,0.323,20.0,21.0,0.952,10.0,29.0,39.0,22.0,10.0,4.0,18.0,26.0,0.560,0.500,0.388,0.263,27.0,76.3,52.0,62.9,10.6,6.8,16.8,100.0,106.3,111.6,8.0,17.0,0.500,3.0,7.0,0.429,9.0,9.0,1.0,2.0,8.0,9.0,5.0,3.0,2.0,4.0,5.0,26.0,4.0,0.689,0.650,0.800,1.000,11.4,32.6,18.6,39.8,8.0,5.8,37.2,39.6,133.0,117.0,SAC,100.0,1,2014,2013-11-05,True,0,104.666667,106.0,0.465021,0.391304,0.663043,0.180328,0.819672,5.0,1.0
142,240.0,43.0,94.0,0.457,8.0,26.0,0.308,13.0,19.0,0.684,13.0,33.0,46.0,31.0,11.0,9.0,11.0,23.0,0.523,0.500,0.277,0.202,27.1,76.7,50.5,72.1,11.2,14.8,9.7,100.0,109.4,111.4,10.0,21.0,0.667,2.0,5.0,0.667,7.0,11.0,1.00,3.0,8.0,10.0,11.0,3.0,4.0,4.0,4.0,29.0,13.0,0.735,0.733,1.000,0.733,16.1,53.9,33.9,46.2,6.4,9.0,21.6,30.7,155.0,123.0,ATL,107.0,0,240.0,42.0,86.0,0.488,14.0,25.0,0.560,11.0,17.0,0.647,10.0,35.0,45.0,28.0,4.0,8.0,16.0,18.0,0.583,0.570,0.291,0.198,23.3,72.9,49.5,66.7,4.1,11.8,14.6,100.0,111.4,109.4,9.0,16.0,0.750,4.0,6.0,1.000,4.0,5.0,0.8,4.0,7.0,9.0,8.0,1.0,2.0,3.0,3.0,23.0,17.0,0.806,0.786,0.714,1.250,17.0,31.5,19.0,46.4,2.4,13.3,29.1,33.1,150.0,114.0,DEN,109.0,1,2014,2013-11-07,False,1,104.750000,104.5,0.469136,0.384615,0.677966,0.196203,0.803797,-2.0,-1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25348,240.0,39.0,79.0,0.494,16.0,37.0,0.432,15.0,18.0,0.833,5.0,33.0,38.0,26.0,9.0,5.0,18.0,18.0,0.627,0.595,0.468,0.228,13.5,82.5,49.4,66.7,9.1,8.9,17.2,100.0,110.8,119.9,10.0,19.0,1.000,4.0,11.0,0.800,5.0,5.0,1.00,3.0,6.0,7.0,7.0,4.0,2.0,8.0,4.0,29.0,9.0,1.042,1.000,0.667,1.000,15.9,34.1,17.8,90.1,6.2,24.4,50.0,31.7,241.0,128.0,WAS,109.0,0,240.0,46.0,88.0,0.523,13.0,32.0,0.406,13.0,18.0,0.722,7.0,32.0,39.0,31.0,12.0,4.0,11.0,17.0,0.615,0.597,0.364,0.205,17.5,86.5,50.6,67.4,12.2,9.5,10.3,100.0,119.9,110.8,11.0,20.0,0.800,6.0,11.0,0.545,4.0,5.0,1.0,4.0,7.0,11.0,8.0,3.0,1.0,5.0,5.0,27.0,19.0,0.820,0.800,1.000,0.600,18.5,38.7,26.5,30.1,4.4,5.2,66.7,31.2,192.0,120.0,NYK,118.0,1,2023,2023-04-02,False,0,117.200000,117.8,0.520455,0.360248,0.714286,0.189055,0.810945,-9.0,-63.0
25367,240.0,50.0,99.0,0.505,13.0,27.0,0.481,15.0,21.0,0.714,9.0,33.0,42.0,30.0,7.0,4.0,9.0,21.0,0.591,0.571,0.273,0.212,17.0,73.3,42.9,60.0,6.4,8.0,7.7,100.0,117.9,129.0,9.0,17.0,0.800,5.0,6.0,1.000,6.0,6.0,1.00,2.0,7.0,9.0,9.0,2.0,2.0,3.0,5.0,24.0,7.0,0.800,0.800,0.600,1.250,8.6,28.5,16.4,41.6,3.9,5.3,28.6,34.4,153.0,135.0,WAS,128.0,1,240.0,50.0,92.0,0.543,23.0,42.0,0.548,17.0,29.0,0.586,12.0,44.0,56.0,33.0,6.0,7.0,18.0,19.0,0.668,0.668,0.457,0.315,26.7,83.0,57.1,66.0,5.5,9.7,14.7,100.0,129.0,117.9,12.0,21.0,0.750,5.0,9.0,0.800,10.0,17.0,1.0,5.0,15.0,20.0,10.0,2.0,5.0,8.0,4.0,28.0,24.0,1.125,1.125,1.000,1.063,17.1,43.7,31.5,51.7,3.2,11.0,33.3,37.5,208.0,126.0,MIL,140.0,0,2023,2023-04-04,False,0,116.600000,117.0,0.518349,0.385542,0.720430,0.189320,0.810680,-12.0,-75.0
25376,240.0,45.0,94.0,0.479,6.0,28.0,0.214,20.0,26.0,0.769,12.0,27.0,39.0,23.0,10.0,9.0,14.0,26.0,0.550,0.511,0.298,0.277,25.0,69.2,44.8,51.1,9.6,16.7,11.7,100.0,111.6,129.0,8.0,18.0,0.833,2.0,8.0,0.667,9.0,9.0,1.00,4.0,7.0,10.0,6.0,4.0,3.0,4.0,4.0,25.0,2.0,1.017,1.000,0.667,0.900,17.6,32.4,24.2,25.4,6.3,9.0,50.0,29.9,179.0,139.0,WAS,116.0,0,240.0,43.0,84.0,0.512,13.0,30.0,0.433,35.0,40.0,0.875,12.0,36.0,48.0,30.0,10.0,5.0,16.0,23.0,0.659,0.589,0.357,0.476,30.8,75.0,55.2,69.8,9.6,7.6,13.6,100.0,129.0,111.6,8.0,13.0,1.000,4.0,6.0,1.000,16.0,18.0,1.0,4.0,8.0,8.0,16.0,3.0,3.0,4.0,5.0,25.0,19.0,1.031,1.000,1.000,1.800,40.8,66.3,54.9,52.4,15.3,14.4,33.3,40.6,206.0,121.0,ATL,134.0,1,2023,2023-04-05,False,1,121.400000,121.4,0.517857,0.437126,0.714286,0.180095,0.819905,-18.0,-93.0
25415,240.0,39.0,84.0,0.464,7.0,33.0,0.212,29.0,37.0,0.784,12.0,38.0,50.0,23.0,4.0,3.0,16.0,18.0,0.568,0.506,0.393,0.440,26.7,73.1,51.5,59.0,3.9,5.9,13.8,100.0,111.3,105.4,9.0,20.0,0.900,3.0,9.0,0.500,6.0,10.0,1.00,4.0,7.0,9.0,4.0,3.0,1.0,3.0,5.0,22.0,25.0,0.935,0.900,0.833,3.333,19.4,32.7,22.5,36.4,6.4,4.0,28.8,24.6,164.0,112.0,WAS,114.0,1,240.0,43.0,98.0,0.439,15.0,47.0,0.319,7.0,12.0,0.583,14.0,33.0,47.0,26.0,7.0,4.0,16.0,29.0,0.523,0.515,0.480,0.122,26.9,73.3,48.5,60.5,6.8,7.8,13.4,100.0,105.4,111.3,11.0,24.0,0.800,7.0,16.0,0.667,3.0,4.0,1.0,4.0,5.0,9.0,8.0,2.0,2.0,3.0,6.0,30.0,18.0,0.814,0.800,0.750,1.000,17.1,24.8,17.3,47.8,3.6,5.8,27.3,44.5,149.0,117.0,MIA,108.0,0,2023,2023-04-07,True,0,117.400000,123.4,0.494530,0.387879,0.724490,0.212560,0.787440,6.0,-87.0
25459,240.0,41.0,97.0,0.423,14.0,45.0,0.311,13.0,21.0,0.619,14.0,37.0,51.0,28.0,11.0,5.0,12.0,21.0,0.513,0.495,0.464,0.216,26.9,74.0,50.0,68.3,10.7,7.2,10.1,100.0,106.5,111.4,9.0,20.0,0.750,5.0,15.0,0.714,3.0,4.0,1.00,7.0,10.0,14.0,8.0,2.0,2.0,4.0,4.0,22.0,4.0,1.066,1.063,0.875,0.500,16.9,21.1,17.3,29.0,3.2,6.4,28.8,27.9,196.0,116.0,WAS,109.0,1,240.0,44.0,90.0,0.489,6.0,21.0,0.286,20.0,28.0,0.714,13.0,38.0,51.0,24.0,8.0,6.0,15.0,15.0,0.557,0.522,0.233,0.311,26.0,73.1,50.0,54.5,7.8,11.5,12.8,100.0,111.4,106.5,6.0,12.0,0.714,2.0,3.0,1.000,7.0,8.0,1.0,3.0,9.0,12.0,6.0,2.0,2.0,4.0,3.0,20.0,10.0,0.689,0.800,0.667,0.727,22.8,35.3,24.0,34.1,4.5,7.8,40.0,27.3,136.0,117.0,HOU,114.0,0,2023,2023-04-09,False,2,119.400000,122.2,0.498901,0.339506,0.765217,0.207547,0.792453,-5.0,-92.0

## Big 5 availability in the team

In [15]:
stats_df = pd.concat([stats_df, per], axis=1)

## Win percentage

The provided code performs the following operations:

    Sort the DataFrame (stats_df) by the game date, assuming there's a column named 'date' containing the date of each 
    game. This will rearrange the rows of the DataFrame in chronological order.

    Create a new column named 'win_%' initialized with zeros (0.0). This column will be used to store the win percentage 
    for each team.

    Iterate through each row in the DataFrame using the iterrows() method. This allows the code to process each row 
    individually.

    For each row, extract the 'team' and 'season' values. These will be used to identify the team and the current season 
    for which we want to calculate the win percentage.

    Get the previous 10 games for the same team in the same season. The code filters the DataFrame (stats_df) to find the 
    10 most recent games played by the team in the current season.

    Count the number of wins in the previous 10 games. The 'won' column is assumed to be a binary column, where 1 
    indicates a win and 0 indicates a loss.

    Calculate the win percentage for the team by dividing the number of wins by the total number of games played in 
    the previous 10 games and then multiplying by 100 to express the result as a percentage.

    Update the 'win_%' column for the current row with the calculated win percentage.

    Repeat steps 4 to 8 for each row in the DataFrame to calculate the win percentage for all teams for their 
    respective previous 10 games.

The result is a DataFrame stats_df with the 'win_%' column, which represents the win percentage for each team in their last 10 games in the same season. This allows you to analyze the recent performance of each team based on their win percentages.

In [16]:
# Step 1: Sort the DataFrame by 'team', 'season', and 'date' in ascending order
stats_df = stats_df.sort_values(by=['team', 'season', 'date'])

# Step 2: Calculate the total number of wins for each team up to the current date within each season
stats_df['cumulative_wins'] = stats_df.groupby(['team', 'season'])['won'].cumsum()

# Step 3: Calculate the total number of games played by each team up to the current date within each season
stats_df['cumulative_games_played'] = stats_df.groupby(['team', 'season']).cumcount() + 1

# Step 4: Calculate the updated win percentage for each team up to the current date within each season
stats_df['win_percent'] = stats_df['cumulative_wins'] / stats_df['cumulative_games_played'] * 100

# Step 5: Fill any missing values with 0 in case there are no games played yet for a team within a season
stats_df['win_percent'] = stats_df['win_percent'].fillna(0)

# Step 6: Print the updated DataFrame with the new 'win_percent' column
print(stats_df[['date', 'team', 'season', 'won', 'win_percent']])
stats_df

             date team  season    won  win_percent
14     2013-10-30  ATL    2014  False     0.000000
48     2013-11-01  ATL    2014   True    50.000000
81     2013-11-03  ATL    2014  False    33.333333
117    2013-11-05  ATL    2014   True    50.000000
142    2013-11-07  ATL    2014  False    40.000000
...           ...  ...     ...    ...          ...
25348  2023-04-02  WAS    2023  False    44.155844
25367  2023-04-04  WAS    2023  False    43.589744
25376  2023-04-05  WAS    2023  False    43.037975
25415  2023-04-07  WAS    2023   True    43.750000
25459  2023-04-09  WAS    2023  False    43.209877

[25640 rows x 5 columns]

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,orb,drb,trb,ast,stl,blk,tov,pf,ts%,efg%,3par,ftr,orb%,drb%,trb%,ast%,stl%,blk%,tov%,usg%,ortg,drtg,fg_max,fga_max,fg%_max,3p_max,3pa_max,3p%_max,ft_max,fta_max,ft%_max,orb_max,drb_max,trb_max,ast_max,stl_max,blk_max,tov_max,pf_max,pts_max,+/-_max,ts%_max,efg%_max,3par_max,ftr_max,orb%_max,drb%_max,trb%_max,ast%_max,stl%_max,blk%_max,tov%_max,usg%_max,ortg_max,drtg_max,team,total,home,mp_opp,fg_opp,fga_opp,fg%_opp,3p_opp,3pa_opp,3p%_opp,ft_opp,fta_opp,ft%_opp,orb_opp,drb_opp,trb_opp,ast_opp,stl_opp,blk_opp,tov_opp,pf_opp,ts%_opp,efg%_opp,3par_opp,ftr_opp,orb%_opp,drb%_opp,trb%_opp,ast%_opp,stl%_opp,blk%_opp,tov%_opp,usg%_opp,ortg_opp,drtg_opp,fg_max_opp,fga_max_opp,fg%_max_opp,3p_max_opp,3pa_max_opp,3p%_max_opp,ft_max_opp,fta_max_opp,ft%_max_opp,orb_max_opp,drb_max_opp,trb_max_opp,ast_max_opp,stl_max_opp,blk_max_opp,tov_max_opp,pf_max_opp,pts_max_opp,+/-_max_opp,ts%_max_opp,efg%_max_opp,3par_max_opp,ftr_max_opp,orb%_max_opp,drb%_max_opp,trb%_max_opp,ast%_max_opp,stl%_max_opp,blk%_max_opp,tov%_max_opp,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won,target,avg_points_scored,avg_points_allowed,shooting_percentage,three_point_percentage,free_throw_percentage,offensive_rebound_rate,defensive_rebound_rate,point_differential,cumulative_point_differential,PER_Combined,PER_Combined_opp,cumulative_wins,cumulative_games_played,win_percent
14,240.0,37.0,76.0,0.487,8.0,24.0,0.333,27.0,35.0,0.771,5.0,28.0,33.0,27.0,16.0,5.0,17.0,20.0,0.596,0.539,0.316,0.461,12.5,80.0,44.0,73.0,15.9,9.4,15.7,100.0,108.3,117.2,9.0,15.0,0.800,3.0,7.0,0.500,9.0,12.0,1.00,2.0,6.0,7.0,9.0,5.0,4.0,6.0,4.0,24.0,11.0,1.136,0.800,1.000,1.143,7.2,35.0,16.3,61.0,7.5,11.3,66.7,31.3,239.0,128.0,ATL,109.0,0,240.0,44.0,77.0,0.571,11.0,24.0,0.458,19.0,24.0,0.792,7.0,35.0,42.0,31.0,7.0,2.0,20.0,22.0,0.674,0.643,0.312,0.312,20.0,87.5,56.0,70.5,7.0,3.8,18.6,100.0,117.2,108.3,11.0,17.0,1.000,4.0,6.0,1.000,8.0,8.0,1.0,5.0,8.0,9.0,11.0,2.0,1.0,7.0,4.0,32.0,18.0,1.500,1.500,1.000,0.500,32.5,35.7,21.4,37.0,3.5,3.4,69.4,33.4,270.0,113.0,DAL,118.0,1,2014,2013-10-30,False,1,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,-9.0,-9.0,86.300000,69.300000,0,1,0.000000
48,240.0,36.0,77.0,0.468,10.0,23.0,0.435,20.0,31.0,0.645,7.0,30.0,37.0,24.0,7.0,3.0,13.0,12.0,0.563,0.532,0.299,0.403,17.9,75.0,46.8,66.7,7.5,4.6,12.5,100.0,108.9,101.4,9.0,14.0,0.643,5.0,8.0,0.667,8.0,9.0,1.00,3.0,13.0,16.0,12.0,3.0,1.0,3.0,2.0,22.0,20.0,0.708,0.750,0.750,1.000,17.2,50.2,33.9,51.7,4.6,10.3,33.3,25.7,124.0,111.0,ATL,102.0,1,240.0,40.0,88.0,0.455,7.0,23.0,0.304,8.0,14.0,0.571,10.0,32.0,42.0,15.0,5.0,6.0,12.0,25.0,0.504,0.494,0.261,0.159,25.0,82.1,53.2,37.5,5.3,11.1,11.3,100.0,101.4,108.9,14.0,23.0,0.714,3.0,5.0,1.000,3.0,6.0,1.0,3.0,6.0,9.0,4.0,2.0,2.0,4.0,4.0,31.0,14.0,0.830,0.929,1.000,0.857,15.5,31.8,23.6,47.9,3.1,10.0,50.0,37.6,157.0,117.0,TOR,95.0,0,2014,2013-11-01,True,0,109.000000,118.0,0.486842,0.333333,0.771429,0.151515,0.848485,7.0,-2.0,86.300000,82.000000,1,2,50.000000
81,240.0,40.0,90.0,0.444,9.0,22.0,0.409,14.0,26.0,0.538,10.0,42.0,52.0,26.0,9.0,3.0,11.0,22.0,0.508,0.494,0.244,0.289,17.5,87.5,49.5,65.0,8.7,4.7,9.8,100.0,99.6,101.6,8.0,18.0,0.800,6.0,6.0,1.000,6.0,10.0,0.75,3.0,13.0,16.0,4.0,2.0,1.0,4.0,4.0,22.0,12.0,1.100,1.100,0.857,1.111,19.4,39.1,23.9,28.6,6.1,2.6,22.5,31.1,206.0,109.0,ATL,103.0,0,240.0,38.0,89.0,0.427,9.0,25.0,0.360,20.0,24.0,0.833,6.0,47.0,53.0,27.0,5.0,7.0,13.0,24.0,0.527,0.478,0.281,0.270,12.5,82.5,50.5,71.1,4.8,10.3,11.5,100.0,101.6,99.6,5.0,18.0,1.000,2.0,4.0,0.500,6.0,8.0,1.0,3.0,13.0,13.0,7.0,2.0,3.0,4.0,6.0,18.0,4.0,1.042,1.000,0.800,1.000,14.3,39.5,21.5,34.9,4.9,10.1,33.3,37.1,158.0,108.0,LAL,105.0,1,2014,2013-11-03,False,1,105.500000,106.5,0.477124,0.382979,0.712121,0.171429,0.828571,-2.0,-4.0,86.300000,61.000000,1,3,33.333333
117,240.0,39.0,81.0,0.481,8.0,22.0,0.364,19.0,26.0,0.731,9.0,27.0,36.0,26.0,11.0,7.0,14.0,15.0,0.568,0.531,0.272,0.321,23.7,73.0,48.0,66.7,11.7,14.3,13.2,100.0,111.6,106.3,11.0,19.0,0.750,2.0,5.0,1.000,5.0,8.0,1.00,5.0,8.0,11.0,10.0,4.0,2.0,4.0,4.0,27.0,6.0,0.922,0.875,0.750,0.667,17.9,33.8,20.9,56.0,6.1,17.0,38.1,30.2,136.0,116.0,ATL,105.0,0,240.0,35.0,80.0,0.438,10.0,31.0,0.323,20.0,21.0,0.952,10.0,29.0,39.0,22.0,10.0,4.0,18.0,26.0,0.560,0.500,0.388,0.263,27.0,76.3,52.0,62.9,10.6,6.8,16.8,100.0,106.3,111.6,8.0,17.0,0.500,3.0,7.0,0.429,9.0,9.0,1.0,2.0,8.0,9.0,5.0,3.0,2.0,4.0,5.0,26.0,4.0,0.689,0.650,0.800,1.000,11.4,32.6,18.6,39.8,8.0,5.8,37.2,39.6,133.0,117.0,SAC,100.0,1,2014,2013-11-05,True,0,104.666667,106.0,0.465021,0.391304,0.663043,0.180328,0.819672,5.0,1.0,86.300000,54.300000,2,4,50.000000
142,240.0,43.0,94.0,0.457,8.0,26.0,0.308,13.0,19.0,0.684,13.0,33.0,46.0,31.0,11.0,9.0,11.0,23.0,0.523,0.500,0.277,0.202,27.1,76.7,50.5,72.1,11.2,14.8,9.7,100.0,109.4,111.4,10.0,21.0,0.667,2.0,5.0,0.667,7.0,11.0,1.00,3.0,8.0,10.0,11.0,3.0,4.0,4.0,4.0,29.0,13.0,0.735,0.733,1.000,0.733,16.1,53.9,33.9,46.2,6.4,9.0,21.6,30.7,155.0,123.0,ATL,107.0,0,240.0,42.0,86.0,0.488,14.0,25.0,0.560,11.0,17.0,0.647,10.0,35.0,45.0,28.0,4.0,8.0,16.0,18.0,0.583,0.570,0.291,0.198,23.3,72.9,49.5,66.7,4.1,11.8,14.6,100.0,111.4,109.4,9.0,16.0,0.750,4.0,6.0,1.000,4.0,5.0,0.8,4.0,7.0,9.0,8.0,1.0,2.0,3.0,3.0,23.0,17.0,0.806,0.786,0.714,1.250,17.0,31.5,19.0,46.4,2.4,13.3,29.1,33.1,150.0,114.0,DEN,109.0,1,2014,2013-11-07,False,1,104.750000,104.5,0.469136,0.384615,0.677966,0.196203,0.803797,-2.0,-1.0,86.300000,68.300000,2,5,40.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25348,240.0,39.0,79.0,0.494,16.0,37.0,0.432,15.0,18.0,0.833,5.0,33.0,38.0,26.0,9.0,5.0,18.0,18.0,0.627,0.595,0.468,0.228,13.5,82.5,49.4,66.7,9.1,8.9,17.2,100.0,110.8,119.9,10.0,19.0,1.000,4.0,11.0,0.800,5.0,5.0,1.00,3.0,6.0,7.0,7.0,4.0,2.0,8.0,4.0,29.0,9.0,1.042,1.000,0.667,1.000,15.9,34.1,17.8,90.1,6.2,24.4,50.0,31.7,241.0,128.0,WAS,109.0,0,240.0,46.0,88.0,0.523,13.0,32.0,0.406,13.0,18.0,0.722,7.0,32.0,39.0,31.0,12.0,4.0,11.0,17.0,0.615,0.597,0.364,0.205,17.5,86.5,50.6,67.4,12.2,9.5,10.3,100.0,119.9,110.8,11.0,20.0,0.800,6.0,11.0,0.545,4.0,5.0,1.0,4.0,7.0,11.0,8.0,3.0,1.0,5.0,5.0,27.0,19.0,0.820,0.800,1.000,0.600,18.5,38.7,26.5,30.1,4.4,5.2,66.7,31.2,192.0,120.0,NYK,118.0,1,2023,2023-04-02,False,0,117.200000,117.8,0.520455,0.360248,0.714286,0.189055,0.810945,-9.0,-63.0,34.246017,70.500000,34,77,44.155844
25367,240.0,50.0,99.0,0.505,13.0,27.0,0.481,15.0,21.0,0.714,9.0,33.0,42.0,30.0,7.0,4.0,9.0,21.0,0.591,0.571,0.273,0.212,17.0,73.3,42.9,60.0,6.4,8.0,7.7,100.0,117.9,129.0,9.0,17.0,0.800,5.0,6.0,1.000,6.0,6.0,1.00,2.0,7.0,9.0,9.0,2.0,2.0,3.0,5.0,24.0,7.0,0.800,0.800,0.600,1.250,8.6,28.5,16.4,41.6,3.9,5.3,28.6,34.4,153.0,135.0,WAS,128.0,1,240.0,50.0,92.0,0.543,23.0,42.0,0.548,17.0,29.0,0.586,12.0,44.0,56.0,33.0,6.0,7.0,18.0,19.0,0.668,0.668,0.457,0.315,26.7,83.0,57.1,66.0,5.5,9.7,14.7,100.0,129.0,117.9,12.0,21.0,0.750,5.0,9.0,0.800,10.0,17.0,1.0,5.0,15.0,20.0,10.0,2.0,5.0,8.0,4.0,28.0,24.0,1.125,1.125,1.000,1.063,17.1,43.7,31.5,51.7,3.2,11.0,33.3,37.5,208.0,126.0,MIL,140.0,0,2023,2023-04-04,False,0,116.600000,117.0,0.518349,0.385542,0.720430,0.189320,0.810680,-12.0,-75.0,34.246017,81.200000,34,78,43.589744
25376,240.0,45.0,94.0,0.479,6.0,28.0,0.214,20.0,26.0,0.769,12.0,27.0,39.0,23.0,10.0,9.0,14.0,26.0,0.550,0.511,0.298,0.277,25.0,69.2,44.8,51.1,9.6,16.7,11.7,100.0,111.6,129.0,8.0,18.0,0.833,2.0,8.0,0.667,9.0,9.0,1.00,4.0,7.0,10.0,6.0,4.0,3.0,4.0,4.0,25.0,2.0,1.017,1.000,0.667,0.900,17.6,32.4,24.2,25.4,6.3,9.0,50.0,29.9,179.0,139.0,WAS,116.0,0,240.0,43.0,84.0,0.512,13.0,30.0,0.433,35.0,40.0,0.875,12.0,36.0,48.0,30.0,10.0,5.0,16.0,23.0,0.659,0.589,0.357,0.476,30.8,75.0,55.2,69.8,9.6,7.6,13.6,100.0,129.0,111.6,8.0,13.0,1.000,4.0,6.0,1.000,16.0,18.0,1.0,4.0,8.0,8.0,16.0,3.0,3.0,4.0,5.0,25.0,19.0,1.031,1.000,1.000,1.800,40.8,66.3,54.9,52.4,15.3,14.4,33.3,40.6,206.0,121.0,ATL,134.0,1,2023,2023-04-05,False,1,121.400000,121.4,0.517857,0.437126,0.714286,0.180095,0.819905,-18.0,-93.0,34.246017,72.300000,34,79,43.037975
25415,240.0,39.0,84.0,0.464,7.0,33.0,0.212,29.0,37.0,0.784,12.0,38.0,50.0,23.0,4.0,3.0,16.0,18.0,0.568,0.506,0.393,0.440,26.7,73.1,51.5,59.0,3.9,5.9,13.8,100.0,111.3,105.4,9.0,20.0,0.900,3.0,9.0,0.500,6.0,10.0,1.00,4.0,7.0,9.0,4.0,3.0,1.0,3.0,5.0,22.0,25.0,0.935,0.900,0.833,3.333,19.4,32.7,22.5,36.4,6.4,4.0,28.8,24.6,164.0,112.0,WAS,114.0,1,240.0,43.0,98.0,0.439,15.0,47.0,0.319,7.0,12.0,0.583,14.0,33.0,47.0,26.0,7.0,4.0,16.0,29.0,0.523,0.515,0.480,0.122,26.9,73.3,48.5,60.5,6.8,7.8,13.4,100.0,105.4,111.3,11.0,24.0,0.800,7.0,16.0,0.667,3.0,4.0,1.0,4.0,5.0,9.0,8.0,2.0,2.0,3.0,6.0,30.0,18.0,0.814,0.800,0.750,1.000,17.1,24.8,17.3,47.8,3.6,5.8,27.3,44.5,149.0,117.0,MIA,108.0,0,2023,2023-04-07,True,0,117.400000,123.4,0.494530,0.387879,0.724490,0.212560,0.787440,6.0,-87.0,34.246017,34.246017,35,80,43.750000
25459,240.0,41.0,97.0,0.423,14.0,45.0,0.311,13.0,21.0,0.619,14.0,37.0,51.0,28.0,11.0,5.0,12.0,21.0,0.513,0.495,0.464,0.216,26.9,74.0,50.0,68.3,10.7,7.2,10.1,100.0,106.5,111.4,9.0,20.0,0.750,5.0,15.0,0.714,3.0,4.0,1.00,7.0,10.0,14.0,8.0,2.0,2.0,4.0,4.0,22.0,4.0,1.066,1.063,0.875,0.500,16.9,21.1,17.3,29.0,3.2,6.4,28.8,27.9,196.0,116.0,WAS,109.0,1,240.0,44.0,90.0,0.489,6.0,21.0,0.286,20.0,28.0,0.714,13.0,38.0,51.0,24.0,8.0,6.0,15.0,15.0,0.557,0.522,0.233,0.311,26.0,73.1,50.0,54.5,7.8,11.5,12.8,100.0,111.4,106.5,6.0,12.0,0.714,2.0,3.0,1.000,7.0,8.0,1.0,3.0,9.0,12.0,6.0,2.0,2.0,4.0,3.0,20.0,10.0,0.689,0.800,0.667,0.727,22.8,35.3,24.0,34.1,4.5,7.8,40.0,27.3,136.0,117.0,HOU,114.0,0,2023,2023-04-09,False,2,119.400000,122.2,0.498901,0.339506,0.765217,0.207547,0.792453,-5.0,-92.0,34.246017,60.800000,35,81,43.209877

## Win Streak and Losing Streak: 
Include features that track the number of consecutive wins or losses for each team. Momentum can influence future game results.
To include features that track the number of consecutive wins and losses for each team, you can use a loop to iterate through the stats_df DataFrame and calculate these streaks for each team. You'll need to sort the DataFrame by team and game date to ensure that the games are ordered chronologically for each team.

In [17]:
# Step 1: Create boolean masks for rows where the team won or lost the game
mask_won = stats_df['won'] == 1
mask_lost = stats_df['won'] == 0

# Step 2: Calculate the win streak values using the cumulative sum of the win mask
stats_df['win_streak'] = mask_won.groupby((~mask_won).cumsum()).cumsum().astype(int)

# Step 3: Calculate the losing streak values using the cumulative sum of the lose mask
stats_df['losing_streak'] = mask_lost.groupby((~mask_lost).cumsum()).cumsum().astype(int)

stats_df

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,orb,drb,trb,ast,stl,blk,tov,pf,ts%,efg%,3par,ftr,orb%,drb%,trb%,ast%,stl%,blk%,tov%,usg%,ortg,drtg,fg_max,fga_max,fg%_max,3p_max,3pa_max,3p%_max,ft_max,fta_max,ft%_max,orb_max,drb_max,trb_max,ast_max,stl_max,blk_max,tov_max,pf_max,pts_max,+/-_max,ts%_max,efg%_max,3par_max,ftr_max,orb%_max,drb%_max,trb%_max,ast%_max,stl%_max,blk%_max,tov%_max,usg%_max,ortg_max,drtg_max,team,total,home,mp_opp,fg_opp,fga_opp,fg%_opp,3p_opp,3pa_opp,3p%_opp,ft_opp,fta_opp,ft%_opp,orb_opp,drb_opp,trb_opp,ast_opp,stl_opp,blk_opp,tov_opp,pf_opp,ts%_opp,efg%_opp,3par_opp,ftr_opp,orb%_opp,drb%_opp,trb%_opp,ast%_opp,stl%_opp,blk%_opp,tov%_opp,usg%_opp,ortg_opp,drtg_opp,fg_max_opp,fga_max_opp,fg%_max_opp,3p_max_opp,3pa_max_opp,3p%_max_opp,ft_max_opp,fta_max_opp,ft%_max_opp,orb_max_opp,drb_max_opp,trb_max_opp,ast_max_opp,stl_max_opp,blk_max_opp,tov_max_opp,pf_max_opp,pts_max_opp,+/-_max_opp,ts%_max_opp,efg%_max_opp,3par_max_opp,ftr_max_opp,orb%_max_opp,drb%_max_opp,trb%_max_opp,ast%_max_opp,stl%_max_opp,blk%_max_opp,tov%_max_opp,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won,target,avg_points_scored,avg_points_allowed,shooting_percentage,three_point_percentage,free_throw_percentage,offensive_rebound_rate,defensive_rebound_rate,point_differential,cumulative_point_differential,PER_Combined,PER_Combined_opp,cumulative_wins,cumulative_games_played,win_percent,win_streak,losing_streak
14,240.0,37.0,76.0,0.487,8.0,24.0,0.333,27.0,35.0,0.771,5.0,28.0,33.0,27.0,16.0,5.0,17.0,20.0,0.596,0.539,0.316,0.461,12.5,80.0,44.0,73.0,15.9,9.4,15.7,100.0,108.3,117.2,9.0,15.0,0.800,3.0,7.0,0.500,9.0,12.0,1.00,2.0,6.0,7.0,9.0,5.0,4.0,6.0,4.0,24.0,11.0,1.136,0.800,1.000,1.143,7.2,35.0,16.3,61.0,7.5,11.3,66.7,31.3,239.0,128.0,ATL,109.0,0,240.0,44.0,77.0,0.571,11.0,24.0,0.458,19.0,24.0,0.792,7.0,35.0,42.0,31.0,7.0,2.0,20.0,22.0,0.674,0.643,0.312,0.312,20.0,87.5,56.0,70.5,7.0,3.8,18.6,100.0,117.2,108.3,11.0,17.0,1.000,4.0,6.0,1.000,8.0,8.0,1.0,5.0,8.0,9.0,11.0,2.0,1.0,7.0,4.0,32.0,18.0,1.500,1.500,1.000,0.500,32.5,35.7,21.4,37.0,3.5,3.4,69.4,33.4,270.0,113.0,DAL,118.0,1,2014,2013-10-30,False,1,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,-9.0,-9.0,86.300000,69.300000,0,1,0.000000,0,1
48,240.0,36.0,77.0,0.468,10.0,23.0,0.435,20.0,31.0,0.645,7.0,30.0,37.0,24.0,7.0,3.0,13.0,12.0,0.563,0.532,0.299,0.403,17.9,75.0,46.8,66.7,7.5,4.6,12.5,100.0,108.9,101.4,9.0,14.0,0.643,5.0,8.0,0.667,8.0,9.0,1.00,3.0,13.0,16.0,12.0,3.0,1.0,3.0,2.0,22.0,20.0,0.708,0.750,0.750,1.000,17.2,50.2,33.9,51.7,4.6,10.3,33.3,25.7,124.0,111.0,ATL,102.0,1,240.0,40.0,88.0,0.455,7.0,23.0,0.304,8.0,14.0,0.571,10.0,32.0,42.0,15.0,5.0,6.0,12.0,25.0,0.504,0.494,0.261,0.159,25.0,82.1,53.2,37.5,5.3,11.1,11.3,100.0,101.4,108.9,14.0,23.0,0.714,3.0,5.0,1.000,3.0,6.0,1.0,3.0,6.0,9.0,4.0,2.0,2.0,4.0,4.0,31.0,14.0,0.830,0.929,1.000,0.857,15.5,31.8,23.6,47.9,3.1,10.0,50.0,37.6,157.0,117.0,TOR,95.0,0,2014,2013-11-01,True,0,109.000000,118.0,0.486842,0.333333,0.771429,0.151515,0.848485,7.0,-2.0,86.300000,82.000000,1,2,50.000000,1,0
81,240.0,40.0,90.0,0.444,9.0,22.0,0.409,14.0,26.0,0.538,10.0,42.0,52.0,26.0,9.0,3.0,11.0,22.0,0.508,0.494,0.244,0.289,17.5,87.5,49.5,65.0,8.7,4.7,9.8,100.0,99.6,101.6,8.0,18.0,0.800,6.0,6.0,1.000,6.0,10.0,0.75,3.0,13.0,16.0,4.0,2.0,1.0,4.0,4.0,22.0,12.0,1.100,1.100,0.857,1.111,19.4,39.1,23.9,28.6,6.1,2.6,22.5,31.1,206.0,109.0,ATL,103.0,0,240.0,38.0,89.0,0.427,9.0,25.0,0.360,20.0,24.0,0.833,6.0,47.0,53.0,27.0,5.0,7.0,13.0,24.0,0.527,0.478,0.281,0.270,12.5,82.5,50.5,71.1,4.8,10.3,11.5,100.0,101.6,99.6,5.0,18.0,1.000,2.0,4.0,0.500,6.0,8.0,1.0,3.0,13.0,13.0,7.0,2.0,3.0,4.0,6.0,18.0,4.0,1.042,1.000,0.800,1.000,14.3,39.5,21.5,34.9,4.9,10.1,33.3,37.1,158.0,108.0,LAL,105.0,1,2014,2013-11-03,False,1,105.500000,106.5,0.477124,0.382979,0.712121,0.171429,0.828571,-2.0,-4.0,86.300000,61.000000,1,3,33.333333,0,1
117,240.0,39.0,81.0,0.481,8.0,22.0,0.364,19.0,26.0,0.731,9.0,27.0,36.0,26.0,11.0,7.0,14.0,15.0,0.568,0.531,0.272,0.321,23.7,73.0,48.0,66.7,11.7,14.3,13.2,100.0,111.6,106.3,11.0,19.0,0.750,2.0,5.0,1.000,5.0,8.0,1.00,5.0,8.0,11.0,10.0,4.0,2.0,4.0,4.0,27.0,6.0,0.922,0.875,0.750,0.667,17.9,33.8,20.9,56.0,6.1,17.0,38.1,30.2,136.0,116.0,ATL,105.0,0,240.0,35.0,80.0,0.438,10.0,31.0,0.323,20.0,21.0,0.952,10.0,29.0,39.0,22.0,10.0,4.0,18.0,26.0,0.560,0.500,0.388,0.263,27.0,76.3,52.0,62.9,10.6,6.8,16.8,100.0,106.3,111.6,8.0,17.0,0.500,3.0,7.0,0.429,9.0,9.0,1.0,2.0,8.0,9.0,5.0,3.0,2.0,4.0,5.0,26.0,4.0,0.689,0.650,0.800,1.000,11.4,32.6,18.6,39.8,8.0,5.8,37.2,39.6,133.0,117.0,SAC,100.0,1,2014,2013-11-05,True,0,104.666667,106.0,0.465021,0.391304,0.663043,0.180328,0.819672,5.0,1.0,86.300000,54.300000,2,4,50.000000,1,0
142,240.0,43.0,94.0,0.457,8.0,26.0,0.308,13.0,19.0,0.684,13.0,33.0,46.0,31.0,11.0,9.0,11.0,23.0,0.523,0.500,0.277,0.202,27.1,76.7,50.5,72.1,11.2,14.8,9.7,100.0,109.4,111.4,10.0,21.0,0.667,2.0,5.0,0.667,7.0,11.0,1.00,3.0,8.0,10.0,11.0,3.0,4.0,4.0,4.0,29.0,13.0,0.735,0.733,1.000,0.733,16.1,53.9,33.9,46.2,6.4,9.0,21.6,30.7,155.0,123.0,ATL,107.0,0,240.0,42.0,86.0,0.488,14.0,25.0,0.560,11.0,17.0,0.647,10.0,35.0,45.0,28.0,4.0,8.0,16.0,18.0,0.583,0.570,0.291,0.198,23.3,72.9,49.5,66.7,4.1,11.8,14.6,100.0,111.4,109.4,9.0,16.0,0.750,4.0,6.0,1.000,4.0,5.0,0.8,4.0,7.0,9.0,8.0,1.0,2.0,3.0,3.0,23.0,17.0,0.806,0.786,0.714,1.250,17.0,31.5,19.0,46.4,2.4,13.3,29.1,33.1,150.0,114.0,DEN,109.0,1,2014,2013-11-07,False,1,104.750000,104.5,0.469136,0.384615,0.677966,0.196203,0.803797,-2.0,-1.0,86.300000,68.300000,2,5,40.000000,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25348,240.0,39.0,79.0,0.494,16.0,37.0,0.432,15.0,18.0,0.833,5.0,33.0,38.0,26.0,9.0,5.0,18.0,18.0,0.627,0.595,0.468,0.228,13.5,82.5,49.4,66.7,9.1,8.9,17.2,100.0,110.8,119.9,10.0,19.0,1.000,4.0,11.0,0.800,5.0,5.0,1.00,3.0,6.0,7.0,7.0,4.0,2.0,8.0,4.0,29.0,9.0,1.042,1.000,0.667,1.000,15.9,34.1,17.8,90.1,6.2,24.4,50.0,31.7,241.0,128.0,WAS,109.0,0,240.0,46.0,88.0,0.523,13.0,32.0,0.406,13.0,18.0,0.722,7.0,32.0,39.0,31.0,12.0,4.0,11.0,17.0,0.615,0.597,0.364,0.205,17.5,86.5,50.6,67.4,12.2,9.5,10.3,100.0,119.9,110.8,11.0,20.0,0.800,6.0,11.0,0.545,4.0,5.0,1.0,4.0,7.0,11.0,8.0,3.0,1.0,5.0,5.0,27.0,19.0,0.820,0.800,1.000,0.600,18.5,38.7,26.5,30.1,4.4,5.2,66.7,31.2,192.0,120.0,NYK,118.0,1,2023,2023-04-02,False,0,117.200000,117.8,0.520455,0.360248,0.714286,0.189055,0.810945,-9.0,-63.0,34.246017,70.500000,34,77,44.155844,0,1
25367,240.0,50.0,99.0,0.505,13.0,27.0,0.481,15.0,21.0,0.714,9.0,33.0,42.0,30.0,7.0,4.0,9.0,21.0,0.591,0.571,0.273,0.212,17.0,73.3,42.9,60.0,6.4,8.0,7.7,100.0,117.9,129.0,9.0,17.0,0.800,5.0,6.0,1.000,6.0,6.0,1.00,2.0,7.0,9.0,9.0,2.0,2.0,3.0,5.0,24.0,7.0,0.800,0.800,0.600,1.250,8.6,28.5,16.4,41.6,3.9,5.3,28.6,34.4,153.0,135.0,WAS,128.0,1,240.0,50.0,92.0,0.543,23.0,42.0,0.548,17.0,29.0,0.586,12.0,44.0,56.0,33.0,6.0,7.0,18.0,19.0,0.668,0.668,0.457,0.315,26.7,83.0,57.1,66.0,5.5,9.7,14.7,100.0,129.0,117.9,12.0,21.0,0.750,5.0,9.0,0.800,10.0,17.0,1.0,5.0,15.0,20.0,10.0,2.0,5.0,8.0,4.0,28.0,24.0,1.125,1.125,1.000,1.063,17.1,43.7,31.5,51.7,3.2,11.0,33.3,37.5,208.0,126.0,MIL,140.0,0,2023,2023-04-04,False,0,116.600000,117.0,0.518349,0.385542,0.720430,0.189320,0.810680,-12.0,-75.0,34.246017,81.200000,34,78,43.589744,0,2
25376,240.0,45.0,94.0,0.479,6.0,28.0,0.214,20.0,26.0,0.769,12.0,27.0,39.0,23.0,10.0,9.0,14.0,26.0,0.550,0.511,0.298,0.277,25.0,69.2,44.8,51.1,9.6,16.7,11.7,100.0,111.6,129.0,8.0,18.0,0.833,2.0,8.0,0.667,9.0,9.0,1.00,4.0,7.0,10.0,6.0,4.0,3.0,4.0,4.0,25.0,2.0,1.017,1.000,0.667,0.900,17.6,32.4,24.2,25.4,6.3,9.0,50.0,29.9,179.0,139.0,WAS,116.0,0,240.0,43.0,84.0,0.512,13.0,30.0,0.433,35.0,40.0,0.875,12.0,36.0,48.0,30.0,10.0,5.0,16.0,23.0,0.659,0.589,0.357,0.476,30.8,75.0,55.2,69.8,9.6,7.6,13.6,100.0,129.0,111.6,8.0,13.0,1.000,4.0,6.0,1.000,16.0,18.0,1.0,4.0,8.0,8.0,16.0,3.0,3.0,4.0,5.0,25.0,19.0,1.031,1.000,1.000,1.800,40.8,66.3,54.9,52.4,15.3,14.4,33.3,40.6,206.0,121.0,ATL,134.0,1,2023,2023-04-05,False,1,121.400000,121.4,0.517857,0.437126,0.714286,0.180095,0.819905,-18.0,-93.0,34.246017,72.300000,34,79,43.037975,0,3
25415,240.0,39.0,84.0,0.464,7.0,33.0,0.212,29.0,37.0,0.784,12.0,38.0,50.0,23.0,4.0,3.0,16.0,18.0,0.568,0.506,0.393,0.440,26.7,73.1,51.5,59.0,3.9,5.9,13.8,100.0,111.3,105.4,9.0,20.0,0.900,3.0,9.0,0.500,6.0,10.0,1.00,4.0,7.0,9.0,4.0,3.0,1.0,3.0,5.0,22.0,25.0,0.935,0.900,0.833,3.333,19.4,32.7,22.5,36.4,6.4,4.0,28.8,24.6,164.0,112.0,WAS,114.0,1,240.0,43.0,98.0,0.439,15.0,47.0,0.319,7.0,12.0,0.583,14.0,33.0,47.0,26.0,7.0,4.0,16.0,29.0,0.523,0.515,0.480,0.122,26.9,73.3,48.5,60.5,6.8,7.8,13.4,100.0,105.4,111.3,11.0,24.0,0.800,7.0,16.0,0.667,3.0,4.0,1.0,4.0,5.0,9.0,8.0,2.0,2.0,3.0,6.0,30.0,18.0,0.814,0.800,0.750,1.000,17.1,24.8,17.3,47.8,3.6,5.8,27.3,44.5,149.0,117.0,MIA,108.0,0,2023,2023-04-07,True,0,117.400000,123.4,0.494530,0.387879,0.724490,0.212560,0.787440,6.0,-87.0,34.246017,34.246017,35,80,43.750000,1,0
25459,240.0,41.0,97.0,0.423,14.0,45.0,0.311,13.0,21.0,0.619,14.0,37.0,51.0,28.0,11.0,5.0,12.0,21.0,0.513,0.495,0.464,0.216,26.9,74.0,50.0,68.3,10.7,7.2,10.1,100.0,106.5,111.4,9.0,20.0,0.750,5.0,15.0,0.714,3.0,4.0,1.00,7.0,10.0,14.0,8.0,2.0,2.0,4.0,4.0,22.0,4.0,1.066,1.063,0.875,0.500,16.9,21.1,17.3,29.0,3.2,6.4,28.8,27.9,196.0,116.0,WAS,109.0,1,240.0,44.0,90.0,0.489,6.0,21.0,0.286,20.0,28.0,0.714,13.0,38.0,51.0,24.0,8.0,6.0,15.0,15.0,0.557,0.522,0.233,0.311,26.0,73.1,50.0,54.5,7.8,11.5,12.8,100.0,111.4,106.5,6.0,12.0,0.714,2.0,3.0,1.000,7.0,8.0,1.0,3.0,9.0,12.0,6.0,2.0,2.0,4.0,3.0,20.0,10.0,0.689,0.800,0.667,0.727,22.8,35.3,24.0,34.1,4.5,7.8,40.0,27.3,136.0,117.0,HOU,114.0,0,2023,2023-04-09,False,2,119.400000,122.2,0.498901,0.339506,0.765217,0.207547,0.792453,-5.0,-92.0,34.246017,60.800000,35,81,43.209877,0,1

In this code, we first sort the DataFrame by team and game date to ensure that games are ordered chronologically for each team.

Next, we define the calculate_streaks function, which takes a row from the stats_df DataFrame and calculates the number of consecutive wins and losses for that team before the current game. The function finds all previous games for the team in the same season and iterates through them to determine the win streak and losing streak.

We then use apply to apply this function to each row in the DataFrame and create the new 'win_streak' and 'losing_streak' columns. These columns will represent the number of consecutive wins and losses for each team before each game, which can be used as input features to capture the team's momentum and potentially influence future game results.

Remember that the calculation of streaks can be sensitive to the sorting order, so it's crucial to sort the DataFrame correctly before calculating these features.

## Team Elo Rating & Schedule strength
The code you provided implements the Elo rating system to update the Elo ratings for each team and opponent in the stats_df DataFrame based on game outcomes. The new Elo ratings are stored in the elo_rating and elo_rating_opp columns.

Here's a breakdown of the code:

    The initial Elo rating is set to 1500, and a dictionary elo_ratings is created to store the Elo ratings for each 
    team. All teams are initialized with the initial Elo rating.

    The K-factor (a constant that determines the magnitude of Elo rating updates) is set to 32.

    A new column named 'elo_rating' is initialized in the stats_df dataframe with the initial Elo rating for all teams.

    The code then iterates through each row in the stats_df dataframe using the iterrows() method.

    For each row (corresponding to a match), it fetches the relevant data, including home and away team names, 
    Elo ratings, and match scores.

    The expected win probabilities for the home and away teams are calculated using the Elo rating formula.

    Based on the match outcome, the Elo ratings are updated for both the home and away teams.

    The updated Elo ratings are stored back in the elo_ratings dictionary.

    The stats_df dataframe is grouped by the 'team' column, and the Elo ratings are updated for each team using the 
    transform function.

In [18]:
# Define the initial Elo rating value
initial_elo_rating = 1500

# Create a dictionary to store the current Elo rating for each team
elo_ratings = {team: initial_elo_rating for team in stats_df['team'].unique()}

# Create a dictionary to store the current Elo rating for each opposing team
elo_ratings_opp = {team: initial_elo_rating for team in stats_df['team_opp'].unique()}

# Define K-factor for Elo rating update (you can adjust this value as needed)
k_factor = 32

# Function to calculate the expected win probability based on Elo ratings
def expected_win_probability(elo_a, elo_b):
    return 1 / (1 + 10 ** ((elo_b - elo_a) / 400))

# Function to update Elo ratings based on the game result
def update_elo_rating(elo_a, elo_b, outcome):
    expected_win = expected_win_probability(elo_a, elo_b)
    if outcome == 1:
        return elo_a + k_factor * (1 - expected_win)
    elif outcome == 0.5:
        return elo_a + k_factor * (0.5 - expected_win)
    else:
        return elo_a + k_factor * (0 - expected_win)

# Iterate through each row in the DataFrame to update Elo ratings
for index, row in stats_df.iterrows():
    team_a = row['team']
    team_b = row['team_opp']
    outcome = row['won']
    
    elo_a = elo_ratings[team_a]
    elo_b = elo_ratings_opp[team_b]
    
    elo_ratings[team_a] = update_elo_rating(elo_a, elo_b, outcome)
    elo_ratings_opp[team_b] = update_elo_rating(elo_b, elo_a, 1 - outcome)

    # Update the 'elo_rating' and 'elo_rating_opp' columns for the current row
    stats_df.at[index, 'elo_rating'] = elo_a
    stats_df.at[index, 'elo_rating_opp'] = elo_b

# Print the DataFrame to verify the 'elo_rating' and 'elo_rating_opp' columns
stats_df

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,orb,drb,trb,ast,stl,blk,tov,pf,ts%,efg%,3par,ftr,orb%,drb%,trb%,ast%,stl%,blk%,tov%,usg%,ortg,drtg,fg_max,fga_max,fg%_max,3p_max,3pa_max,3p%_max,ft_max,fta_max,ft%_max,orb_max,drb_max,trb_max,ast_max,stl_max,blk_max,tov_max,pf_max,pts_max,+/-_max,ts%_max,efg%_max,3par_max,ftr_max,orb%_max,drb%_max,trb%_max,ast%_max,stl%_max,blk%_max,tov%_max,usg%_max,ortg_max,drtg_max,team,total,home,mp_opp,fg_opp,fga_opp,fg%_opp,3p_opp,3pa_opp,3p%_opp,ft_opp,fta_opp,ft%_opp,orb_opp,drb_opp,trb_opp,ast_opp,stl_opp,blk_opp,tov_opp,pf_opp,ts%_opp,efg%_opp,3par_opp,ftr_opp,orb%_opp,drb%_opp,trb%_opp,ast%_opp,stl%_opp,blk%_opp,tov%_opp,usg%_opp,ortg_opp,drtg_opp,fg_max_opp,fga_max_opp,fg%_max_opp,3p_max_opp,3pa_max_opp,3p%_max_opp,ft_max_opp,fta_max_opp,ft%_max_opp,orb_max_opp,drb_max_opp,trb_max_opp,ast_max_opp,stl_max_opp,blk_max_opp,tov_max_opp,pf_max_opp,pts_max_opp,+/-_max_opp,ts%_max_opp,efg%_max_opp,3par_max_opp,ftr_max_opp,orb%_max_opp,drb%_max_opp,trb%_max_opp,ast%_max_opp,stl%_max_opp,blk%_max_opp,tov%_max_opp,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won,target,avg_points_scored,avg_points_allowed,shooting_percentage,three_point_percentage,free_throw_percentage,offensive_rebound_rate,defensive_rebound_rate,point_differential,cumulative_point_differential,PER_Combined,PER_Combined_opp,cumulative_wins,cumulative_games_played,win_percent,win_streak,losing_streak,elo_rating,elo_rating_opp
14,240.0,37.0,76.0,0.487,8.0,24.0,0.333,27.0,35.0,0.771,5.0,28.0,33.0,27.0,16.0,5.0,17.0,20.0,0.596,0.539,0.316,0.461,12.5,80.0,44.0,73.0,15.9,9.4,15.7,100.0,108.3,117.2,9.0,15.0,0.800,3.0,7.0,0.500,9.0,12.0,1.00,2.0,6.0,7.0,9.0,5.0,4.0,6.0,4.0,24.0,11.0,1.136,0.800,1.000,1.143,7.2,35.0,16.3,61.0,7.5,11.3,66.7,31.3,239.0,128.0,ATL,109.0,0,240.0,44.0,77.0,0.571,11.0,24.0,0.458,19.0,24.0,0.792,7.0,35.0,42.0,31.0,7.0,2.0,20.0,22.0,0.674,0.643,0.312,0.312,20.0,87.5,56.0,70.5,7.0,3.8,18.6,100.0,117.2,108.3,11.0,17.0,1.000,4.0,6.0,1.000,8.0,8.0,1.0,5.0,8.0,9.0,11.0,2.0,1.0,7.0,4.0,32.0,18.0,1.500,1.500,1.000,0.500,32.5,35.7,21.4,37.0,3.5,3.4,69.4,33.4,270.0,113.0,DAL,118.0,1,2014,2013-10-30,False,1,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,-9.0,-9.0,86.300000,69.300000,0,1,0.000000,0,1,1500.000000,1500.000000
48,240.0,36.0,77.0,0.468,10.0,23.0,0.435,20.0,31.0,0.645,7.0,30.0,37.0,24.0,7.0,3.0,13.0,12.0,0.563,0.532,0.299,0.403,17.9,75.0,46.8,66.7,7.5,4.6,12.5,100.0,108.9,101.4,9.0,14.0,0.643,5.0,8.0,0.667,8.0,9.0,1.00,3.0,13.0,16.0,12.0,3.0,1.0,3.0,2.0,22.0,20.0,0.708,0.750,0.750,1.000,17.2,50.2,33.9,51.7,4.6,10.3,33.3,25.7,124.0,111.0,ATL,102.0,1,240.0,40.0,88.0,0.455,7.0,23.0,0.304,8.0,14.0,0.571,10.0,32.0,42.0,15.0,5.0,6.0,12.0,25.0,0.504,0.494,0.261,0.159,25.0,82.1,53.2,37.5,5.3,11.1,11.3,100.0,101.4,108.9,14.0,23.0,0.714,3.0,5.0,1.000,3.0,6.0,1.0,3.0,6.0,9.0,4.0,2.0,2.0,4.0,4.0,31.0,14.0,0.830,0.929,1.000,0.857,15.5,31.8,23.6,47.9,3.1,10.0,50.0,37.6,157.0,117.0,TOR,95.0,0,2014,2013-11-01,True,0,109.000000,118.0,0.486842,0.333333,0.771429,0.151515,0.848485,7.0,-2.0,86.300000,82.000000,1,2,50.000000,1,0,1484.000000,1500.000000
81,240.0,40.0,90.0,0.444,9.0,22.0,0.409,14.0,26.0,0.538,10.0,42.0,52.0,26.0,9.0,3.0,11.0,22.0,0.508,0.494,0.244,0.289,17.5,87.5,49.5,65.0,8.7,4.7,9.8,100.0,99.6,101.6,8.0,18.0,0.800,6.0,6.0,1.000,6.0,10.0,0.75,3.0,13.0,16.0,4.0,2.0,1.0,4.0,4.0,22.0,12.0,1.100,1.100,0.857,1.111,19.4,39.1,23.9,28.6,6.1,2.6,22.5,31.1,206.0,109.0,ATL,103.0,0,240.0,38.0,89.0,0.427,9.0,25.0,0.360,20.0,24.0,0.833,6.0,47.0,53.0,27.0,5.0,7.0,13.0,24.0,0.527,0.478,0.281,0.270,12.5,82.5,50.5,71.1,4.8,10.3,11.5,100.0,101.6,99.6,5.0,18.0,1.000,2.0,4.0,0.500,6.0,8.0,1.0,3.0,13.0,13.0,7.0,2.0,3.0,4.0,6.0,18.0,4.0,1.042,1.000,0.800,1.000,14.3,39.5,21.5,34.9,4.9,10.1,33.3,37.1,158.0,108.0,LAL,105.0,1,2014,2013-11-03,False,1,105.500000,106.5,0.477124,0.382979,0.712121,0.171429,0.828571,-2.0,-4.0,86.300000,61.000000,1,3,33.333333,0,1,1500.736307,1500.000000
117,240.0,39.0,81.0,0.481,8.0,22.0,0.364,19.0,26.0,0.731,9.0,27.0,36.0,26.0,11.0,7.0,14.0,15.0,0.568,0.531,0.272,0.321,23.7,73.0,48.0,66.7,11.7,14.3,13.2,100.0,111.6,106.3,11.0,19.0,0.750,2.0,5.0,1.000,5.0,8.0,1.00,5.0,8.0,11.0,10.0,4.0,2.0,4.0,4.0,27.0,6.0,0.922,0.875,0.750,0.667,17.9,33.8,20.9,56.0,6.1,17.0,38.1,30.2,136.0,116.0,ATL,105.0,0,240.0,35.0,80.0,0.438,10.0,31.0,0.323,20.0,21.0,0.952,10.0,29.0,39.0,22.0,10.0,4.0,18.0,26.0,0.560,0.500,0.388,0.263,27.0,76.3,52.0,62.9,10.6,6.8,16.8,100.0,106.3,111.6,8.0,17.0,0.500,3.0,7.0,0.429,9.0,9.0,1.0,2.0,8.0,9.0,5.0,3.0,2.0,4.0,5.0,26.0,4.0,0.689,0.650,0.800,1.000,11.4,32.6,18.6,39.8,8.0,5.8,37.2,39.6,133.0,117.0,SAC,100.0,1,2014,2013-11-05,True,0,104.666667,106.0,0.465021,0.391304,0.663043,0.180328,0.819672,5.0,1.0,86.300000,54.300000,2,4,50.000000,1,0,1484.702399,1500.000000
142,240.0,43.0,94.0,0.457,8.0,26.0,0.308,13.0,19.0,0.684,13.0,33.0,46.0,31.0,11.0,9.0,11.0,23.0,0.523,0.500,0.277,0.202,27.1,76.7,50.5,72.1,11.2,14.8,9.7,100.0,109.4,111.4,10.0,21.0,0.667,2.0,5.0,0.667,7.0,11.0,1.00,3.0,8.0,10.0,11.0,3.0,4.0,4.0,4.0,29.0,13.0,0.735,0.733,1.000,0.733,16.1,53.9,33.9,46.2,6.4,9.0,21.6,30.7,155.0,123.0,ATL,107.0,0,240.0,42.0,86.0,0.488,14.0,25.0,0.560,11.0,17.0,0.647,10.0,35.0,45.0,28.0,4.0,8.0,16.0,18.0,0.583,0.570,0.291,0.198,23.3,72.9,49.5,66.7,4.1,11.8,14.6,100.0,111.4,109.4,9.0,16.0,0.750,4.0,6.0,1.000,4.0,5.0,0.8,4.0,7.0,9.0,8.0,1.0,2.0,3.0,3.0,23.0,17.0,0.806,0.786,0.714,1.250,17.0,31.5,19.0,46.4,2.4,13.3,29.1,33.1,150.0,114.0,DEN,109.0,1,2014,2013-11-07,False,1,104.750000,104.5,0.469136,0.384615,0.677966,0.196203,0.803797,-2.0,-1.0,86.300000,68.300000,2,5,40.000000,0,1,1501.406424,1500.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25348,240.0,39.0,79.0,0.494,16.0,37.0,0.432,15.0,18.0,0.833,5.0,33.0,38.0,26.0,9.0,5.0,18.0,18.0,0.627,0.595,0.468,0.228,13.5,82.5,49.4,66.7,9.1,8.9,17.2,100.0,110.8,119.9,10.0,19.0,1.000,4.0,11.0,0.800,5.0,5.0,1.00,3.0,6.0,7.0,7.0,4.0,2.0,8.0,4.0,29.0,9.0,1.042,1.000,0.667,1.000,15.9,34.1,17.8,90.1,6.2,24.4,50.0,31.7,241.0,128.0,WAS,109.0,0,240.0,46.0,88.0,0.523,13.0,32.0,0.406,13.0,18.0,0.722,7.0,32.0,39.0,31.0,12.0,4.0,11.0,17.0,0.615,0.597,0.364,0.205,17.5,86.5,50.6,67.4,12.2,9.5,10.3,100.0,119.9,110.8,11.0,20.0,0.800,6.0,11.0,0.545,4.0,5.0,1.0,4.0,7.0,11.0,8.0,3.0,1.0,5.0,5.0,27.0,19.0,0.820,0.800,1.000,0.600,18.5,38.7,26.5,30.1,4.4,5.2,66.7,31.2,192.0,120.0,NYK,118.0,1,2023,2023-04-02,False,0,117.200000,117.8,0.520455,0.360248,0.714286,0.189055,0.810945,-9.0,-63.0,34.246017,70.500000,34,77,44.155844,0,1,1451.572477,1411.746618
25367,240.0,50.0,99.0,0.505,13.0,27.0,0.481,15.0,21.0,0.714,9.0,33.0,42.0,30.0,7.0,4.0,9.0,21.0,0.591,0.571,0.273,0.212,17.0,73.3,42.9,60.0,6.4,8.0,7.7,100.0,117.9,129.0,9.0,17.0,0.800,5.0,6.0,1.000,6.0,6.0,1.00,2.0,7.0,9.0,9.0,2.0,2.0,3.0,5.0,24.0,7.0,0.800,0.800,0.600,1.250,8.6,28.5,16.4,41.6,3.9,5.3,28.6,34.4,153.0,135.0,WAS,128.0,1,240.0,50.0,92.0,0.543,23.0,42.0,0.548,17.0,29.0,0.586,12.0,44.0,56.0,33.0,6.0,7.0,18.0,19.0,0.668,0.668,0.457,0.315,26.7,83.0,57.1,66.0,5.5,9.7,14.7,100.0,129.0,117.9,12.0,21.0,0.750,5.0,9.0,0.800,10.0,17.0,1.0,5.0,15.0,20.0,10.0,2.0,5.0,8.0,4.0,28.0,24.0,1.125,1.125,1.000,1.063,17.1,43.7,31.5,51.7,3.2,11.0,33.3,37.5,208.0,126.0,MIL,140.0,0,2023,2023-04-04,False,0,116.600000,117.0,0.518349,0.385542,0.720430,0.189320,0.810680,-12.0,-75.0,34.246017,81.200000,34,78,43.589744,0,2,1433.746419,1555.672697
25376,240.0,45.0,94.0,0.479,6.0,28.0,0.214,20.0,26.0,0.769,12.0,27.0,39.0,23.0,10.0,9.0,14.0,26.0,0.550,0.511,0.298,0.277,25.0,69.2,44.8,51.1,9.6,16.7,11.7,100.0,111.6,129.0,8.0,18.0,0.833,2.0,8.0,0.667,9.0,9.0,1.00,4.0,7.0,10.0,6.0,4.0,3.0,4.0,4.0,25.0,2.0,1.017,1.000,0.667,0.900,17.6,32.4,24.2,25.4,6.3,9.0,50.0,29.9,179.0,139.0,WAS,116.0,0,240.0,43.0,84.0,0.512,13.0,30.0,0.433,35.0,40.0,0.875,12.0,36.0,48.0,30.0,10.0,5.0,16.0,23.0,0.659,0.589,0.357,0.476,30.8,75.0,55.2,69.8,9.6,7.6,13.6,100.0,129.0,111.6,8.0,13.0,1.000,4.0,6.0,1.000,16.0,18.0,1.0,4.0,8.0,8.0,16.0,3.0,3.0,4.0,5.0,25.0,19.0,1.031,1.000,1.000,1.800,40.8,66.3,54.9,52.4,15.3,14.4,33.3,40.6,206.0,121.0,ATL,134.0,1,2023,2023-04-05,False,1,121.400000,121.4,0.517857,0.437126,0.714286,0.180095,0.819905,-18.0,-93.0,34.246017,72.300000,34,79,43.037975,0,3,1423.141649,1559.124452
25415,240.0,39.0,84.0,0.464,7.0,33.0,0.212,29.0,37.0,0.784,12.0,38.0,50.0,23.0,4.0,3.0,16.0,18.0,0.568,0.506,0.393,0.440,26.7,73.1,51.5,59.0,3.9,5.9,13.8,100.0,111.3,105.4,9.0,20.0,0.900,3.0,9.0,0.500,6.0,10.0,1.00,4.0,7.0,9.0,4.0,3.0,1.0,3.0,5.0,22.0,25.0,0.935,0.900,0.833,3.333,19.4,32.7,22.5,36.4,6.4,4.0,28.8,24.6,164.0,112.0,WAS,114.0,1,240.0,43.0,98.0,0.439,15.0,47.0,0.319,7.0,12.0,0.583,14.0,33.0,47.0,26.0,7.0,4.0,16.0,29.0,0.523,0.515,0.480,0.122,26.9,73.3,48.5,60.5,6.8,7.8,13.4,100.0,105.4,111.3,11.0,24.0,0.800,7.0,16.0,0.667,3.0,4.0,1.0,4.0,5.0,9.0,8.0,2.0,2.0,3.0,6.0,30.0,18.0,0.814,0.800,0.750,1.000,17.1,24.8,17.3,47.8,3.6,5.8,27.3,44.5,149.0,117.0,MIA,108.0,0,2023,2023-04-07,True,0,117.400000,123.4,0.494530,0.387879,0.724490,0.212560,0.787440,6.0,-87.0,34.246017,34.246017,35,80,43.750000,1,0,1413.102575,1608.509611
25459,240.0,41.0,97.0,0.423,14.0,45.0,0.311,13.0,21.0,0.619,14.0,37.0,51.0,28.0,11.0,5.0,12.0,21.0,0.513,0.495,0.464,0.216,26.9,74.0,50.0,68.3,10.7,7.2,10.1,100.0,106.5,111.4,9.0,20.0,0.750,5.0,15.0,0.714,3.0,4.0,1.00,7.0,10.0,14.0,8.0,2.0,2.0,4.0,4.0,22.0,4.0,1.066,1.063,0.875,0.500,16.9,21.1,17.3,29.0,3.2,6.4,28.8,27.9,196.0,116.0,WAS,109.0,1,240.0,44.0,90.0,0.489,6.0,21.0,0.286,20.0,28.0,0.714,13.0,38.0,51.0,24.0,8.0,6.0,15.0,15.0,0.557,0.522,0.233,0.311,26.0,73.1,50.0,54.5,7.8,11.5,12.8,100.0,111.4,106.5,6.0,12.0,0.714,2.0,3.0,1.000,7.0,8.0,1.0,3.0,9.0,12.0,6.0,2.0,2.0,4.0,3.0,20.0,10.0,0.689,0.800,0.667,0.727,22.8,35.3,24.0,34.1,4.5,7.8,40.0,27.3,136.0,117.0,HOU,114.0,0,2023,2023-04-09,False,2,119.400000,122.2,0.498901,0.339506,0.765217,0.207547,0.792453,-5.0,-92.0,34.246017,60.800000,35,81,43.209877,0,1,1437.258986,1580.174693

## Head-to-Head Performance: 
Create features that capture the historical performance of each team against their upcoming opponent. This includes win ratios, average points scored, and average points allowed.

To create features that capture the historical performance of each team against their upcoming opponent, you'll need to calculate the win ratio, average points scored, and average points allowed for each team when facing their specific opponent in past games. These features can provide valuable insights into how teams have historically performed against each other and help your prediction model make more informed predictions.

In [19]:
# Function to calculate head-to-head performance metrics for each team
def calculate_head_to_head_stats(row, stats_df):
    team = row['team']
    team_opp = row['team_opp']
    season = row['season']

    # Get all past games where the current team faced the specific opponent in the same season
    head_to_head_games = stats_df[((stats_df['team'] == team) & (stats_df['team_opp'] == team_opp) & (stats_df['season'] == season))
                                 | ((stats_df['team'] == team_opp) & (stats_df['team_opp'] == team) & (stats_df['season'] == season))]

    # Calculate wins for the current team and the opponent
    num_wins_team = head_to_head_games[head_to_head_games['team'] == team]['won'].sum()
    num_wins_opp = head_to_head_games[head_to_head_games['team'] == team_opp]['won'].sum()

    # Calculate total games played
    total_games_played = head_to_head_games['won'].count()

    # Calculate win ratio against the specific opponent
    win_ratio = num_wins_team / total_games_played if total_games_played > 0 else 0.0

    # Calculate average points scored and allowed against the specific opponent
    average_points_scored = head_to_head_games[head_to_head_games['team'] == team]['total'].mean()
    average_points_allowed = head_to_head_games[head_to_head_games['team'] == team]['total_opp'].mean()

    return win_ratio, average_points_scored, average_points_allowed

# Calculate head-to-head performance metrics for each game and add them as new columns
stats_df[['head_to_head_win_ratio', 'average_points_scored', 'average_points_allowed']] = stats_df.apply(lambda row: pd.Series(calculate_head_to_head_stats(row, stats_df)), axis=1)

# Print the updated DataFrame with the new features
stats_df

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,orb,drb,trb,ast,stl,blk,tov,pf,ts%,efg%,3par,ftr,orb%,drb%,trb%,ast%,stl%,blk%,tov%,usg%,ortg,drtg,fg_max,fga_max,fg%_max,3p_max,3pa_max,3p%_max,ft_max,fta_max,ft%_max,orb_max,drb_max,trb_max,ast_max,stl_max,blk_max,tov_max,pf_max,pts_max,+/-_max,ts%_max,efg%_max,3par_max,ftr_max,orb%_max,drb%_max,trb%_max,ast%_max,stl%_max,blk%_max,tov%_max,usg%_max,ortg_max,drtg_max,team,total,home,mp_opp,fg_opp,fga_opp,fg%_opp,3p_opp,3pa_opp,3p%_opp,ft_opp,fta_opp,ft%_opp,orb_opp,drb_opp,trb_opp,ast_opp,stl_opp,blk_opp,tov_opp,pf_opp,ts%_opp,efg%_opp,3par_opp,ftr_opp,orb%_opp,drb%_opp,trb%_opp,ast%_opp,stl%_opp,blk%_opp,tov%_opp,usg%_opp,ortg_opp,drtg_opp,fg_max_opp,fga_max_opp,fg%_max_opp,3p_max_opp,3pa_max_opp,3p%_max_opp,ft_max_opp,fta_max_opp,ft%_max_opp,orb_max_opp,drb_max_opp,trb_max_opp,ast_max_opp,stl_max_opp,blk_max_opp,tov_max_opp,pf_max_opp,pts_max_opp,+/-_max_opp,ts%_max_opp,efg%_max_opp,3par_max_opp,ftr_max_opp,orb%_max_opp,drb%_max_opp,trb%_max_opp,ast%_max_opp,stl%_max_opp,blk%_max_opp,tov%_max_opp,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won,target,avg_points_scored,avg_points_allowed,shooting_percentage,three_point_percentage,free_throw_percentage,offensive_rebound_rate,defensive_rebound_rate,point_differential,cumulative_point_differential,PER_Combined,PER_Combined_opp,cumulative_wins,cumulative_games_played,win_percent,win_streak,losing_streak,elo_rating,elo_rating_opp,head_to_head_win_ratio,average_points_scored,average_points_allowed
14,240.0,37.0,76.0,0.487,8.0,24.0,0.333,27.0,35.0,0.771,5.0,28.0,33.0,27.0,16.0,5.0,17.0,20.0,0.596,0.539,0.316,0.461,12.5,80.0,44.0,73.0,15.9,9.4,15.7,100.0,108.3,117.2,9.0,15.0,0.800,3.0,7.0,0.500,9.0,12.0,1.00,2.0,6.0,7.0,9.0,5.0,4.0,6.0,4.0,24.0,11.0,1.136,0.800,1.000,1.143,7.2,35.0,16.3,61.0,7.5,11.3,66.7,31.3,239.0,128.0,ATL,109.0,0,240.0,44.0,77.0,0.571,11.0,24.0,0.458,19.0,24.0,0.792,7.0,35.0,42.0,31.0,7.0,2.0,20.0,22.0,0.674,0.643,0.312,0.312,20.0,87.5,56.0,70.5,7.0,3.8,18.6,100.0,117.2,108.3,11.0,17.0,1.000,4.0,6.0,1.000,8.0,8.0,1.0,5.0,8.0,9.0,11.0,2.0,1.0,7.0,4.0,32.0,18.0,1.500,1.500,1.000,0.500,32.5,35.7,21.4,37.0,3.5,3.4,69.4,33.4,270.0,113.0,DAL,118.0,1,2014,2013-10-30,False,1,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,-9.0,-9.0,86.300000,69.300000,0,1,0.000000,0,1,1500.000000,1500.000000,0.250,98.50,102.50
48,240.0,36.0,77.0,0.468,10.0,23.0,0.435,20.0,31.0,0.645,7.0,30.0,37.0,24.0,7.0,3.0,13.0,12.0,0.563,0.532,0.299,0.403,17.9,75.0,46.8,66.7,7.5,4.6,12.5,100.0,108.9,101.4,9.0,14.0,0.643,5.0,8.0,0.667,8.0,9.0,1.00,3.0,13.0,16.0,12.0,3.0,1.0,3.0,2.0,22.0,20.0,0.708,0.750,0.750,1.000,17.2,50.2,33.9,51.7,4.6,10.3,33.3,25.7,124.0,111.0,ATL,102.0,1,240.0,40.0,88.0,0.455,7.0,23.0,0.304,8.0,14.0,0.571,10.0,32.0,42.0,15.0,5.0,6.0,12.0,25.0,0.504,0.494,0.261,0.159,25.0,82.1,53.2,37.5,5.3,11.1,11.3,100.0,101.4,108.9,14.0,23.0,0.714,3.0,5.0,1.000,3.0,6.0,1.0,3.0,6.0,9.0,4.0,2.0,2.0,4.0,4.0,31.0,14.0,0.830,0.929,1.000,0.857,15.5,31.8,23.6,47.9,3.1,10.0,50.0,37.6,157.0,117.0,TOR,95.0,0,2014,2013-11-01,True,0,109.000000,118.0,0.486842,0.333333,0.771429,0.151515,0.848485,7.0,-2.0,86.300000,82.000000,1,2,50.000000,1,0,1484.000000,1500.000000,0.250,97.25,102.00
81,240.0,40.0,90.0,0.444,9.0,22.0,0.409,14.0,26.0,0.538,10.0,42.0,52.0,26.0,9.0,3.0,11.0,22.0,0.508,0.494,0.244,0.289,17.5,87.5,49.5,65.0,8.7,4.7,9.8,100.0,99.6,101.6,8.0,18.0,0.800,6.0,6.0,1.000,6.0,10.0,0.75,3.0,13.0,16.0,4.0,2.0,1.0,4.0,4.0,22.0,12.0,1.100,1.100,0.857,1.111,19.4,39.1,23.9,28.6,6.1,2.6,22.5,31.1,206.0,109.0,ATL,103.0,0,240.0,38.0,89.0,0.427,9.0,25.0,0.360,20.0,24.0,0.833,6.0,47.0,53.0,27.0,5.0,7.0,13.0,24.0,0.527,0.478,0.281,0.270,12.5,82.5,50.5,71.1,4.8,10.3,11.5,100.0,101.6,99.6,5.0,18.0,1.000,2.0,4.0,0.500,6.0,8.0,1.0,3.0,13.0,13.0,7.0,2.0,3.0,4.0,6.0,18.0,4.0,1.042,1.000,0.800,1.000,14.3,39.5,21.5,34.9,4.9,10.1,33.3,37.1,158.0,108.0,LAL,105.0,1,2014,2013-11-03,False,1,105.500000,106.5,0.477124,0.382979,0.712121,0.171429,0.828571,-2.0,-4.0,86.300000,61.000000,1,3,33.333333,0,1,1500.736307,1500.000000,0.250,108.50,102.50
117,240.0,39.0,81.0,0.481,8.0,22.0,0.364,19.0,26.0,0.731,9.0,27.0,36.0,26.0,11.0,7.0,14.0,15.0,0.568,0.531,0.272,0.321,23.7,73.0,48.0,66.7,11.7,14.3,13.2,100.0,111.6,106.3,11.0,19.0,0.750,2.0,5.0,1.000,5.0,8.0,1.00,5.0,8.0,11.0,10.0,4.0,2.0,4.0,4.0,27.0,6.0,0.922,0.875,0.750,0.667,17.9,33.8,20.9,56.0,6.1,17.0,38.1,30.2,136.0,116.0,ATL,105.0,0,240.0,35.0,80.0,0.438,10.0,31.0,0.323,20.0,21.0,0.952,10.0,29.0,39.0,22.0,10.0,4.0,18.0,26.0,0.560,0.500,0.388,0.263,27.0,76.3,52.0,62.9,10.6,6.8,16.8,100.0,106.3,111.6,8.0,17.0,0.500,3.0,7.0,0.429,9.0,9.0,1.0,2.0,8.0,9.0,5.0,3.0,2.0,4.0,5.0,26.0,4.0,0.689,0.650,0.800,1.000,11.4,32.6,18.6,39.8,8.0,5.8,37.2,39.6,133.0,117.0,SAC,100.0,1,2014,2013-11-05,True,0,104.666667,106.0,0.465021,0.391304,0.663043,0.180328,0.819672,5.0,1.0,86.300000,54.300000,2,4,50.000000,1,0,1484.702399,1500.000000,0.500,114.50,103.50
142,240.0,43.0,94.0,0.457,8.0,26.0,0.308,13.0,19.0,0.684,13.0,33.0,46.0,31.0,11.0,9.0,11.0,23.0,0.523,0.500,0.277,0.202,27.1,76.7,50.5,72.1,11.2,14.8,9.7,100.0,109.4,111.4,10.0,21.0,0.667,2.0,5.0,0.667,7.0,11.0,1.00,3.0,8.0,10.0,11.0,3.0,4.0,4.0,4.0,29.0,13.0,0.735,0.733,1.000,0.733,16.1,53.9,33.9,46.2,6.4,9.0,21.6,30.7,155.0,123.0,ATL,107.0,0,240.0,42.0,86.0,0.488,14.0,25.0,0.560,11.0,17.0,0.647,10.0,35.0,45.0,28.0,4.0,8.0,16.0,18.0,0.583,0.570,0.291,0.198,23.3,72.9,49.5,66.7,4.1,11.8,14.6,100.0,111.4,109.4,9.0,16.0,0.750,4.0,6.0,1.000,4.0,5.0,0.8,4.0,7.0,9.0,8.0,1.0,2.0,3.0,3.0,23.0,17.0,0.806,0.786,0.714,1.250,17.0,31.5,19.0,46.4,2.4,13.3,29.1,33.1,150.0,114.0,DEN,109.0,1,2014,2013-11-07,False,1,104.750000,104.5,0.469136,0.384615,0.677966,0.196203,0.803797,-2.0,-1.0,86.300000,68.300000,2,5,40.000000,0,1,1501.406424,1500.000000,0.250,102.00,100.50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25348,240.0,39.0,79.0,0.494,16.0,37.0,0.432,15.0,18.0,0.833,5.0,33.0,38.0,26.0,9.0,5.0,18.0,18.0,0.627,0.595,0.468,0.228,13.5,82.5,49.4,66.7,9.1,8.9,17.2,100.0,110.8,119.9,10.0,19.0,1.000,4.0,11.0,0.800,5.0,5.0,1.00,3.0,6.0,7.0,7.0,4.0,2.0,8.0,4.0,29.0,9.0,1.042,1.000,0.667,1.000,15.9,34.1,17.8,90.1,6.2,24.4,50.0,31.7,241.0,128.0,WAS,109.0,0,240.0,46.0,88.0,0.523,13.0,32.0,0.406,13.0,18.0,0.722,7.0,32.0,39.0,31.0,12.0,4.0,11.0,17.0,0.615,0.597,0.364,0.205,17.5,86.5,50.6,67.4,12.2,9.5,10.3,100.0,119.9,110.8,11.0,20.0,0.800,6.0,11.0,0.545,4.0,5.0,1.0,4.0,7.0,11.0,8.0,3.0,1.0,5.0,5.0,27.0,19.0,0.820,0.800,1.000,0.600,18.5,38.7,26.5,30.1,4.4,5.2,66.7,31.2,192.0,120.0,NYK,118.0,1,2023,2023-04-02,False,0,117.200000,117.8,0.520455,0.360248,0.714286,0.189055,0.810945,-9.0,-63.0,34.246017,70.500000,34,77,44.155844,0,1,1451.572477,1411.746618,0.125,110.50,112.50
25367,240.0,50.0,99.0,0.505,13.0,27.0,0.481,15.0,21.0,0.714,9.0,33.0,42.0,30.0,7.0,4.0,9.0,21.0,0.591,0.571,0.273,0.212,17.0,73.3,42.9,60.0,6.4,8.0,7.7,100.0,117.9,129.0,9.0,17.0,0.800,5.0,6.0,1.000,6.0,6.0,1.00,2.0,7.0,9.0,9.0,2.0,2.0,3.0,5.0,24.0,7.0,0.800,0.800,0.600,1.250,8.6,28.5,16.4,41.6,3.9,5.3,28.6,34.4,153.0,135.0,WAS,128.0,1,240.0,50.0,92.0,0.543,23.0,42.0,0.548,17.0,29.0,0.586,12.0,44.0,56.0,33.0,6.0,7.0,18.0,19.0,0.668,0.668,0.457,0.315,26.7,83.0,57.1,66.0,5.5,9.7,14.7,100.0,129.0,117.9,12.0,21.0,0.750,5.0,9.0,0.800,10.0,17.0,1.0,5.0,15.0,20.0,10.0,2.0,5.0,8.0,4.0,28.0,24.0,1.125,1.125,1.000,1.063,17.1,43.7,31.5,51.7,3.2,11.0,33.3,37.5,208.0,126.0,MIL,140.0,0,2023,2023-04-04,False,0,116.600000,117.0,0.518349,0.385542,0.720430,0.189320,0.810680,-12.0,-75.0,34.246017,81.200000,34,78,43.589744,0,2,1433.746419,1555.672697,0.125,117.50,118.75
25376,240.0,45.0,94.0,0.479,6.0,28.0,0.214,20.0,26.0,0.769,12.0,27.0,39.0,23.0,10.0,9.0,14.0,26.0,0.550,0.511,0.298,0.277,25.0,69.2,44.8,51.1,9.6,16.7,11.7,100.0,111.6,129.0,8.0,18.0,0.833,2.0,8.0,0.667,9.0,9.0,1.00,4.0,7.0,10.0,6.0,4.0,3.0,4.0,4.0,25.0,2.0,1.017,1.000,0.667,0.900,17.6,32.4,24.2,25.4,6.3,9.0,50.0,29.9,179.0,139.0,WAS,116.0,0,240.0,43.0,84.0,0.512,13.0,30.0,0.433,35.0,40.0,0.875,12.0,36.0,48.0,30.0,10.0,5.0,16.0,23.0,0.659,0.589,0.357,0.476,30.8,75.0,55.2,69.8,9.6,7.6,13.6,100.0,129.0,111.6,8.0,13.0,1.000,4.0,6.0,1.000,16.0,18.0,1.0,4.0,8.0,8.0,16.0,3.0,3.0,4.0,5.0,25.0,19.0,1.031,1.000,1.000,1.800,40.8,66.3,54.9,52.4,15.3,14.4,33.3,40.6,206.0,121.0,ATL,134.0,1,2023,2023-04-05,False,1,121.400000,121.4,0.517857,0.437126,0.714286,0.180095,0.819905,-18.0,-93.0,34.246017,72.300000,34,79,43.037975,0,3,1423.141649,1559.124452,0.125,115.50,121.50
25415,240.0,39.0,84.0,0.464,7.0,33.0,0.212,29.0,37.0,0.784,12.0,38.0,50.0,23.0,4.0,3.0,16.0,18.0,0.568,0.506,0.393,0.440,26.7,73.1,51.5,59.0,3.9,5.9,13.8,100.0,111.3,105.4,9.0,20.0,0.900,3.0,9.0,0.500,6.0,10.0,1.00,4.0,7.0,9.0,4.0,3.0,1.0,3.0,5.0,22.0,25.0,0.935,0.900,0.833,3.333,19.4,32.7,22.5,36.4,6.4,4.0,28.8,24.6,164.0,112.0,WAS,114.0,1,240.0,43.0,98.0,0.439,15.0,47.0,0.319,7.0,12.0,0.583,14.0,33.0,47.0,26.0,7.0,4.0,16.0,29.0,0.523,0.515,0.480,0.122,26.9,73.3,48.5,60.5,6.8,7.8,13.4,100.0,105.4,111.3,11.0,24.0,0.800,7.0,16.0,0.667,3.0,4.0,1.0,4.0,5.0,9.0,8.0,2.0,2.0,3.0,6.0,30.0,18.0,0.814,0.800,0.750,1.000,17.1,24.8,17.3,47.8,3.6,5.8,27.3,44.5,149.0,117.0,MIA,108.0,0,2023,2023-04-07,True,0,117.400000,123.4,0.494530,0.387879,0.724490,0.212560,0.787440,6.0,-87.0,34.246017,34.246017,35,80,43.750000,1,0,1413.102575,1608.509611,0.250,108.25,109.25
25459,240.0,41.0,97.0,0.423,14.0,45.0,0.311,13.0,21.0,0.619,14.0,37.0,51.0,28.0,11.0,5.0,12.0,21.0,0.513,0.495,0.464,0.216,26.9,74.0,50.0,68.3,10.7,7.2,10.1,100.0,106.5,111.4,9.0,20.0,0.750,5.0,15.0,0.714,3.0,4.0,1.00,7.0,10.0,14.0,8.0,2.0,2.0,4.0,4.0,22.0,4.0,1.066,1.063,0.875,0.500,16.9,21.1,17.3,29.0,3.2,6.4,28.8,27.9,196.0,116.0,WAS,109.0,1,240.0,44.0,90.0,0.489,6.0,21.0,0.286,20.0,28.0,0.714,13.0,38.0,51.0,24.0,8.0,6.0,15.0,15.0,0.557,0.522,0.233,0.311,26.0,73.1,50.0,54.5,7.8,11.5,12.8,100.0,111.4,106.5,6.0,12.0,0.714,2.0,3.0,1.000,7.0,8.0,1.0,3.0,9.0,12.0,6.0,2.0,2.0,4.0,3.0,20.0,10.0,0.689,0.800,0.667,0.727,22.8,35.3,24.0,34.1,4.5,7.8,40.0,27.3,136.0,117.0,HOU,114.0,0,2023,2023-04-09,False,2,119.400000,122.2,0.498901,0.339506,0.765217,0.207547,0.792453,-5.0,-92.0,34.246017,60.800000,35,81,43.209877,0,1,1437.258986,1580.174693,0.250,108.50,108.50

In this code, we first define the calculate_head_to_head_stats function, which takes a row from the stats_df DataFrame and calculates the win ratio, average points scored, and average points allowed for the team against the specific opponent in past games of the same season. The function finds all past games where the current team faced the specific opponent and iterates through them to calculate the metrics.

Next, we use apply to apply this function to each row in the DataFrame and create the new 'head_to_head_win_ratio', 'average_points_scored', and 'average_points_allowed' columns. These columns will represent the historical performance of each team against their upcoming opponent and can be used as input features in your prediction model.

The features derived from head-to-head performance can be particularly useful in capturing the historical dynamics and potential rivalries between teams, which may influence their future matchups and game outcomes.

## Rest Days: 
Incorporate the number of rest days for each team before a game. Fatigue can affect player performance.

To incorporate the number of rest days for each team before a game, you need to have a column in the stats_df DataFrame that represents the game date. Then, you can calculate the number of rest days for each team before each game by considering the time difference between the current game date and the date of the team's previous game.

Here's how you can implement this feature:

    Convert the game date column to a pandas datetime format if it's not already in that format.
    Sort the DataFrame by team and game date to ensure that the games are ordered chronologically for each team.
    Calculate the time difference (rest days) between consecutive game dates for each team.
    Create a new column in the stats_df DataFrame to store the rest days for each team.

In [20]:
# Convert the 'date' column to pandas datetime format
stats_df['date'] = pd.to_datetime(stats_df['date'])

# Sort the DataFrame by team and game date
stats_df = stats_df.sort_values(by=['team', 'date'])

# Function to calculate the rest days for each game
def calculate_rest_days(row, stats_df):
    team = row['team']
    season = row['season']
    previous_game_date = stats_df[(stats_df['team'] == team) & (stats_df['season'] == season) & (stats_df['date'] < row['date'])]['date'].max()
    if pd.notnull(previous_game_date):
        rest_days = (row['date'] - previous_game_date).days - 1
        return rest_days
    return 0

# Calculate rest days for each game and add it as a new column
stats_df['rest_days'] = stats_df.apply(lambda row: calculate_rest_days(row, stats_df), axis=1)

# Print the updated DataFrame with the new feature
stats_df

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,orb,drb,trb,ast,stl,blk,tov,pf,ts%,efg%,3par,ftr,orb%,drb%,trb%,ast%,stl%,blk%,tov%,usg%,ortg,drtg,fg_max,fga_max,fg%_max,3p_max,3pa_max,3p%_max,ft_max,fta_max,ft%_max,orb_max,drb_max,trb_max,ast_max,stl_max,blk_max,tov_max,pf_max,pts_max,+/-_max,ts%_max,efg%_max,3par_max,ftr_max,orb%_max,drb%_max,trb%_max,ast%_max,stl%_max,blk%_max,tov%_max,usg%_max,ortg_max,drtg_max,team,total,home,mp_opp,fg_opp,fga_opp,fg%_opp,3p_opp,3pa_opp,3p%_opp,ft_opp,fta_opp,ft%_opp,orb_opp,drb_opp,trb_opp,ast_opp,stl_opp,blk_opp,tov_opp,pf_opp,ts%_opp,efg%_opp,3par_opp,ftr_opp,orb%_opp,drb%_opp,trb%_opp,ast%_opp,stl%_opp,blk%_opp,tov%_opp,usg%_opp,ortg_opp,drtg_opp,fg_max_opp,fga_max_opp,fg%_max_opp,3p_max_opp,3pa_max_opp,3p%_max_opp,ft_max_opp,fta_max_opp,ft%_max_opp,orb_max_opp,drb_max_opp,trb_max_opp,ast_max_opp,stl_max_opp,blk_max_opp,tov_max_opp,pf_max_opp,pts_max_opp,+/-_max_opp,ts%_max_opp,efg%_max_opp,3par_max_opp,ftr_max_opp,orb%_max_opp,drb%_max_opp,trb%_max_opp,ast%_max_opp,stl%_max_opp,blk%_max_opp,tov%_max_opp,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won,target,avg_points_scored,avg_points_allowed,shooting_percentage,three_point_percentage,free_throw_percentage,offensive_rebound_rate,defensive_rebound_rate,point_differential,cumulative_point_differential,PER_Combined,PER_Combined_opp,cumulative_wins,cumulative_games_played,win_percent,win_streak,losing_streak,elo_rating,elo_rating_opp,head_to_head_win_ratio,average_points_scored,average_points_allowed,rest_days
14,240.0,37.0,76.0,0.487,8.0,24.0,0.333,27.0,35.0,0.771,5.0,28.0,33.0,27.0,16.0,5.0,17.0,20.0,0.596,0.539,0.316,0.461,12.5,80.0,44.0,73.0,15.9,9.4,15.7,100.0,108.3,117.2,9.0,15.0,0.800,3.0,7.0,0.500,9.0,12.0,1.00,2.0,6.0,7.0,9.0,5.0,4.0,6.0,4.0,24.0,11.0,1.136,0.800,1.000,1.143,7.2,35.0,16.3,61.0,7.5,11.3,66.7,31.3,239.0,128.0,ATL,109.0,0,240.0,44.0,77.0,0.571,11.0,24.0,0.458,19.0,24.0,0.792,7.0,35.0,42.0,31.0,7.0,2.0,20.0,22.0,0.674,0.643,0.312,0.312,20.0,87.5,56.0,70.5,7.0,3.8,18.6,100.0,117.2,108.3,11.0,17.0,1.000,4.0,6.0,1.000,8.0,8.0,1.0,5.0,8.0,9.0,11.0,2.0,1.0,7.0,4.0,32.0,18.0,1.500,1.500,1.000,0.500,32.5,35.7,21.4,37.0,3.5,3.4,69.4,33.4,270.0,113.0,DAL,118.0,1,2014,2013-10-30,False,1,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,-9.0,-9.0,86.300000,69.300000,0,1,0.000000,0,1,1500.000000,1500.000000,0.250,98.50,102.50,0
48,240.0,36.0,77.0,0.468,10.0,23.0,0.435,20.0,31.0,0.645,7.0,30.0,37.0,24.0,7.0,3.0,13.0,12.0,0.563,0.532,0.299,0.403,17.9,75.0,46.8,66.7,7.5,4.6,12.5,100.0,108.9,101.4,9.0,14.0,0.643,5.0,8.0,0.667,8.0,9.0,1.00,3.0,13.0,16.0,12.0,3.0,1.0,3.0,2.0,22.0,20.0,0.708,0.750,0.750,1.000,17.2,50.2,33.9,51.7,4.6,10.3,33.3,25.7,124.0,111.0,ATL,102.0,1,240.0,40.0,88.0,0.455,7.0,23.0,0.304,8.0,14.0,0.571,10.0,32.0,42.0,15.0,5.0,6.0,12.0,25.0,0.504,0.494,0.261,0.159,25.0,82.1,53.2,37.5,5.3,11.1,11.3,100.0,101.4,108.9,14.0,23.0,0.714,3.0,5.0,1.000,3.0,6.0,1.0,3.0,6.0,9.0,4.0,2.0,2.0,4.0,4.0,31.0,14.0,0.830,0.929,1.000,0.857,15.5,31.8,23.6,47.9,3.1,10.0,50.0,37.6,157.0,117.0,TOR,95.0,0,2014,2013-11-01,True,0,109.000000,118.0,0.486842,0.333333,0.771429,0.151515,0.848485,7.0,-2.0,86.300000,82.000000,1,2,50.000000,1,0,1484.000000,1500.000000,0.250,97.25,102.00,1
81,240.0,40.0,90.0,0.444,9.0,22.0,0.409,14.0,26.0,0.538,10.0,42.0,52.0,26.0,9.0,3.0,11.0,22.0,0.508,0.494,0.244,0.289,17.5,87.5,49.5,65.0,8.7,4.7,9.8,100.0,99.6,101.6,8.0,18.0,0.800,6.0,6.0,1.000,6.0,10.0,0.75,3.0,13.0,16.0,4.0,2.0,1.0,4.0,4.0,22.0,12.0,1.100,1.100,0.857,1.111,19.4,39.1,23.9,28.6,6.1,2.6,22.5,31.1,206.0,109.0,ATL,103.0,0,240.0,38.0,89.0,0.427,9.0,25.0,0.360,20.0,24.0,0.833,6.0,47.0,53.0,27.0,5.0,7.0,13.0,24.0,0.527,0.478,0.281,0.270,12.5,82.5,50.5,71.1,4.8,10.3,11.5,100.0,101.6,99.6,5.0,18.0,1.000,2.0,4.0,0.500,6.0,8.0,1.0,3.0,13.0,13.0,7.0,2.0,3.0,4.0,6.0,18.0,4.0,1.042,1.000,0.800,1.000,14.3,39.5,21.5,34.9,4.9,10.1,33.3,37.1,158.0,108.0,LAL,105.0,1,2014,2013-11-03,False,1,105.500000,106.5,0.477124,0.382979,0.712121,0.171429,0.828571,-2.0,-4.0,86.300000,61.000000,1,3,33.333333,0,1,1500.736307,1500.000000,0.250,108.50,102.50,1
117,240.0,39.0,81.0,0.481,8.0,22.0,0.364,19.0,26.0,0.731,9.0,27.0,36.0,26.0,11.0,7.0,14.0,15.0,0.568,0.531,0.272,0.321,23.7,73.0,48.0,66.7,11.7,14.3,13.2,100.0,111.6,106.3,11.0,19.0,0.750,2.0,5.0,1.000,5.0,8.0,1.00,5.0,8.0,11.0,10.0,4.0,2.0,4.0,4.0,27.0,6.0,0.922,0.875,0.750,0.667,17.9,33.8,20.9,56.0,6.1,17.0,38.1,30.2,136.0,116.0,ATL,105.0,0,240.0,35.0,80.0,0.438,10.0,31.0,0.323,20.0,21.0,0.952,10.0,29.0,39.0,22.0,10.0,4.0,18.0,26.0,0.560,0.500,0.388,0.263,27.0,76.3,52.0,62.9,10.6,6.8,16.8,100.0,106.3,111.6,8.0,17.0,0.500,3.0,7.0,0.429,9.0,9.0,1.0,2.0,8.0,9.0,5.0,3.0,2.0,4.0,5.0,26.0,4.0,0.689,0.650,0.800,1.000,11.4,32.6,18.6,39.8,8.0,5.8,37.2,39.6,133.0,117.0,SAC,100.0,1,2014,2013-11-05,True,0,104.666667,106.0,0.465021,0.391304,0.663043,0.180328,0.819672,5.0,1.0,86.300000,54.300000,2,4,50.000000,1,0,1484.702399,1500.000000,0.500,114.50,103.50,1
142,240.0,43.0,94.0,0.457,8.0,26.0,0.308,13.0,19.0,0.684,13.0,33.0,46.0,31.0,11.0,9.0,11.0,23.0,0.523,0.500,0.277,0.202,27.1,76.7,50.5,72.1,11.2,14.8,9.7,100.0,109.4,111.4,10.0,21.0,0.667,2.0,5.0,0.667,7.0,11.0,1.00,3.0,8.0,10.0,11.0,3.0,4.0,4.0,4.0,29.0,13.0,0.735,0.733,1.000,0.733,16.1,53.9,33.9,46.2,6.4,9.0,21.6,30.7,155.0,123.0,ATL,107.0,0,240.0,42.0,86.0,0.488,14.0,25.0,0.560,11.0,17.0,0.647,10.0,35.0,45.0,28.0,4.0,8.0,16.0,18.0,0.583,0.570,0.291,0.198,23.3,72.9,49.5,66.7,4.1,11.8,14.6,100.0,111.4,109.4,9.0,16.0,0.750,4.0,6.0,1.000,4.0,5.0,0.8,4.0,7.0,9.0,8.0,1.0,2.0,3.0,3.0,23.0,17.0,0.806,0.786,0.714,1.250,17.0,31.5,19.0,46.4,2.4,13.3,29.1,33.1,150.0,114.0,DEN,109.0,1,2014,2013-11-07,False,1,104.750000,104.5,0.469136,0.384615,0.677966,0.196203,0.803797,-2.0,-1.0,86.300000,68.300000,2,5,40.000000,0,1,1501.406424,1500.000000,0.250,102.00,100.50,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25348,240.0,39.0,79.0,0.494,16.0,37.0,0.432,15.0,18.0,0.833,5.0,33.0,38.0,26.0,9.0,5.0,18.0,18.0,0.627,0.595,0.468,0.228,13.5,82.5,49.4,66.7,9.1,8.9,17.2,100.0,110.8,119.9,10.0,19.0,1.000,4.0,11.0,0.800,5.0,5.0,1.00,3.0,6.0,7.0,7.0,4.0,2.0,8.0,4.0,29.0,9.0,1.042,1.000,0.667,1.000,15.9,34.1,17.8,90.1,6.2,24.4,50.0,31.7,241.0,128.0,WAS,109.0,0,240.0,46.0,88.0,0.523,13.0,32.0,0.406,13.0,18.0,0.722,7.0,32.0,39.0,31.0,12.0,4.0,11.0,17.0,0.615,0.597,0.364,0.205,17.5,86.5,50.6,67.4,12.2,9.5,10.3,100.0,119.9,110.8,11.0,20.0,0.800,6.0,11.0,0.545,4.0,5.0,1.0,4.0,7.0,11.0,8.0,3.0,1.0,5.0,5.0,27.0,19.0,0.820,0.800,1.000,0.600,18.5,38.7,26.5,30.1,4.4,5.2,66.7,31.2,192.0,120.0,NYK,118.0,1,2023,2023-04-02,False,0,117.200000,117.8,0.520455,0.360248,0.714286,0.189055,0.810945,-9.0,-63.0,34.246017,70.500000,34,77,44.155844,0,1,1451.572477,1411.746618,0.125,110.50,112.50,4
25367,240.0,50.0,99.0,0.505,13.0,27.0,0.481,15.0,21.0,0.714,9.0,33.0,42.0,30.0,7.0,4.0,9.0,21.0,0.591,0.571,0.273,0.212,17.0,73.3,42.9,60.0,6.4,8.0,7.7,100.0,117.9,129.0,9.0,17.0,0.800,5.0,6.0,1.000,6.0,6.0,1.00,2.0,7.0,9.0,9.0,2.0,2.0,3.0,5.0,24.0,7.0,0.800,0.800,0.600,1.250,8.6,28.5,16.4,41.6,3.9,5.3,28.6,34.4,153.0,135.0,WAS,128.0,1,240.0,50.0,92.0,0.543,23.0,42.0,0.548,17.0,29.0,0.586,12.0,44.0,56.0,33.0,6.0,7.0,18.0,19.0,0.668,0.668,0.457,0.315,26.7,83.0,57.1,66.0,5.5,9.7,14.7,100.0,129.0,117.9,12.0,21.0,0.750,5.0,9.0,0.800,10.0,17.0,1.0,5.0,15.0,20.0,10.0,2.0,5.0,8.0,4.0,28.0,24.0,1.125,1.125,1.000,1.063,17.1,43.7,31.5,51.7,3.2,11.0,33.3,37.5,208.0,126.0,MIL,140.0,0,2023,2023-04-04,False,0,116.600000,117.0,0.518349,0.385542,0.720430,0.189320,0.810680,-12.0,-75.0,34.246017,81.200000,34,78,43.589744,0,2,1433.746419,1555.672697,0.125,117.50,118.75,1
25376,240.0,45.0,94.0,0.479,6.0,28.0,0.214,20.0,26.0,0.769,12.0,27.0,39.0,23.0,10.0,9.0,14.0,26.0,0.550,0.511,0.298,0.277,25.0,69.2,44.8,51.1,9.6,16.7,11.7,100.0,111.6,129.0,8.0,18.0,0.833,2.0,8.0,0.667,9.0,9.0,1.00,4.0,7.0,10.0,6.0,4.0,3.0,4.0,4.0,25.0,2.0,1.017,1.000,0.667,0.900,17.6,32.4,24.2,25.4,6.3,9.0,50.0,29.9,179.0,139.0,WAS,116.0,0,240.0,43.0,84.0,0.512,13.0,30.0,0.433,35.0,40.0,0.875,12.0,36.0,48.0,30.0,10.0,5.0,16.0,23.0,0.659,0.589,0.357,0.476,30.8,75.0,55.2,69.8,9.6,7.6,13.6,100.0,129.0,111.6,8.0,13.0,1.000,4.0,6.0,1.000,16.0,18.0,1.0,4.0,8.0,8.0,16.0,3.0,3.0,4.0,5.0,25.0,19.0,1.031,1.000,1.000,1.800,40.8,66.3,54.9,52.4,15.3,14.4,33.3,40.6,206.0,121.0,ATL,134.0,1,2023,2023-04-05,False,1,121.400000,121.4,0.517857,0.437126,0.714286,0.180095,0.819905,-18.0,-93.0,34.246017,72.300000,34,79,43.037975,0,3,1423.141649,1559.124452,0.125,115.50,121.50,0
25415,240.0,39.0,84.0,0.464,7.0,33.0,0.212,29.0,37.0,0.784,12.0,38.0,50.0,23.0,4.0,3.0,16.0,18.0,0.568,0.506,0.393,0.440,26.7,73.1,51.5,59.0,3.9,5.9,13.8,100.0,111.3,105.4,9.0,20.0,0.900,3.0,9.0,0.500,6.0,10.0,1.00,4.0,7.0,9.0,4.0,3.0,1.0,3.0,5.0,22.0,25.0,0.935,0.900,0.833,3.333,19.4,32.7,22.5,36.4,6.4,4.0,28.8,24.6,164.0,112.0,WAS,114.0,1,240.0,43.0,98.0,0.439,15.0,47.0,0.319,7.0,12.0,0.583,14.0,33.0,47.0,26.0,7.0,4.0,16.0,29.0,0.523,0.515,0.480,0.122,26.9,73.3,48.5,60.5,6.8,7.8,13.4,100.0,105.4,111.3,11.0,24.0,0.800,7.0,16.0,0.667,3.0,4.0,1.0,4.0,5.0,9.0,8.0,2.0,2.0,3.0,6.0,30.0,18.0,0.814,0.800,0.750,1.000,17.1,24.8,17.3,47.8,3.6,5.8,27.3,44.5,149.0,117.0,MIA,108.0,0,2023,2023-04-07,True,0,117.400000,123.4,0.494530,0.387879,0.724490,0.212560,0.787440,6.0,-87.0,34.246017,34.246017,35,80,43.750000,1,0,1413.102575,1608.509611,0.250,108.25,109.25,1
25459,240.0,41.0,97.0,0.423,14.0,45.0,0.311,13.0,21.0,0.619,14.0,37.0,51.0,28.0,11.0,5.0,12.0,21.0,0.513,0.495,0.464,0.216,26.9,74.0,50.0,68.3,10.7,7.2,10.1,100.0,106.5,111.4,9.0,20.0,0.750,5.0,15.0,0.714,3.0,4.0,1.00,7.0,10.0,14.0,8.0,2.0,2.0,4.0,4.0,22.0,4.0,1.066,1.063,0.875,0.500,16.9,21.1,17.3,29.0,3.2,6.4,28.8,27.9,196.0,116.0,WAS,109.0,1,240.0,44.0,90.0,0.489,6.0,21.0,0.286,20.0,28.0,0.714,13.0,38.0,51.0,24.0,8.0,6.0,15.0,15.0,0.557,0.522,0.233,0.311,26.0,73.1,50.0,54.5,7.8,11.5,12.8,100.0,111.4,106.5,6.0,12.0,0.714,2.0,3.0,1.000,7.0,8.0,1.0,3.0,9.0,12.0,6.0,2.0,2.0,4.0,3.0,20.0,10.0,0.689,0.800,0.667,0.727,22.8,35.3,24.0,34.1,4.5,7.8,40.0,27.3,136.0,117.0,HOU,114.0,0,2023,2023-04-09,False,2,119.400000,122.2,0.498901,0.339506,0.765217,0.207547,0.792453,-5.0,-92.0,34.246017,60.800000,35,81,43.209877,0,1,1437.258986,1580.174693,0.250,108.50,108.50,1

In this code, we first convert the 'date' column to pandas datetime format using pd.to_datetime(). Then, we sort the DataFrame by team and game date to ensure that games are ordered chronologically for each team.

Next, we define the calculate_rest_days function, which takes a row from the stats_df DataFrame and calculates the number of rest days for that team before the current game. The function finds the date of the team's previous game and calculates the time difference between the current game date and the previous game date to get the rest days.

We then use apply to apply this function to each row in the DataFrame and create the new 'rest_days' column. The 'rest_days' column will represent the number of rest days for each team before each game, which can be used as an input to your prediction model to account for the potential impact of fatigue on player performance.

## Introducing the rolling average after 4 games for each team - With Engineered data and Rolling Engineered data
Currently we make our predictions based on the last game played by a team. However, in this implementation, it is possible that a team had a random performance in their last game which might not be truely reflective of the teams performance. Thus it might be useful to evaluate the result from a couple of games back, say 4 or 10 previous games and compute a rolling average.

In [21]:
# Select the featured columns from stats_df
selected_headers = stats_df[["date", "season", 'mp', 'team', 'total', 'team_opp', 'total_opp', "won", 'home', 'home_opp', "target"]]

# Add the selected featured columns to stats_df_filtered
featured_columns = ['avg_points_scored', 'avg_points_allowed', 'shooting_percentage', 'three_point_percentage', 
                    'free_throw_percentage', 'offensive_rebound_rate', 'defensive_rebound_rate', 'point_differential', 
                    'cumulative_point_differential', 'PER_Combined', 'PER_Combined_opp', 'win_percent', 'win_streak', 'losing_streak', 
                    'elo_rating', 'elo_rating_opp', 'head_to_head_win_ratio', 'average_points_scored', 'average_points_allowed', 
                    'rest_days', 'cumulative_wins', 'cumulative_games_played']

stats_df_filtered = pd.concat([selected_headers, stats_df[featured_columns]], axis=1)

# Display the updated stats_df_filtered
stats_df_filtered

,date,season,mp,team,total,team_opp,total_opp,won,home,home_opp,target,avg_points_scored,avg_points_allowed,shooting_percentage,three_point_percentage,free_throw_percentage,offensive_rebound_rate,defensive_rebound_rate,point_differential,cumulative_point_differential,PER_Combined,PER_Combined_opp,win_percent,win_streak,losing_streak,elo_rating,elo_rating_opp,head_to_head_win_ratio,average_points_scored,average_points_allowed,rest_days,cumulative_wins,cumulative_games_played
14,2013-10-30,2014,240.0,ATL,109.0,DAL,118.0,False,0,1,1,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,-9.0,-9.0,86.300000,69.300000,0.000000,0,1,1500.000000,1500.000000,0.250,98.50,102.50,0,0,1
48,2013-11-01,2014,240.0,ATL,102.0,TOR,95.0,True,1,0,0,109.000000,118.0,0.486842,0.333333,0.771429,0.151515,0.848485,7.0,-2.0,86.300000,82.000000,50.000000,1,0,1484.000000,1500.000000,0.250,97.25,102.00,1,1,2
81,2013-11-03,2014,240.0,ATL,103.0,LAL,105.0,False,0,1,1,105.500000,106.5,0.477124,0.382979,0.712121,0.171429,0.828571,-2.0,-4.0,86.300000,61.000000,33.333333,0,1,1500.736307,1500.000000,0.250,108.50,102.50,1,1,3
117,2013-11-05,2014,240.0,ATL,105.0,SAC,100.0,True,0,1,0,104.666667,106.0,0.465021,0.391304,0.663043,0.180328,0.819672,5.0,1.0,86.300000,54.300000,50.000000,1,0,1484.702399,1500.000000,0.500,114.50,103.50,1,2,4
142,2013-11-07,2014,240.0,ATL,107.0,DEN,109.0,False,0,1,1,104.750000,104.5,0.469136,0.384615,0.677966,0.196203,0.803797,-2.0,-1.0,86.300000,68.300000,40.000000,0,1,1501.406424,1500.000000,0.250,102.00,100.50,1,2,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25348,2023-04-02,2023,240.0,WAS,109.0,NYK,118.0,False,0,1,0,117.200000,117.8,0.520455,0.360248,0.714286,0.189055,0.810945,-9.0,-63.0,34.246017,70.500000,44.155844,0,1,1451.572477,1411.746618,0.125,110.50,112.50,4,34,77
25367,2023-04-04,2023,240.0,WAS,128.0,MIL,140.0,False,1,0,0,116.600000,117.0,0.518349,0.385542,0.720430,0.189320,0.810680,-12.0,-75.0,34.246017,81.200000,43.589744,0,2,1433.746419,1555.672697,0.125,117.50,118.75,1,34,78
25376,2023-04-05,2023,240.0,WAS,116.0,ATL,134.0,False,0,1,1,121.400000,121.4,0.517857,0.437126,0.714286,0.180095,0.819905,-18.0,-93.0,34.246017,72.300000,43.037975,0,3,1423.141649,1559.124452,0.125,115.50,121.50,0,34,79
25415,2023-04-07,2023,240.0,WAS,114.0,MIA,108.0,True,1,0,0,117.400000,123.4,0.494530,0.387879,0.724490,0.212560,0.787440,6.0,-87.0,34.246017,34.246017,43.750000,1,0,1413.102575,1608.509611,0.250,108.25,109.25,1,35,80
25459,2023-04-09,2023,240.0,WAS,109.0,HOU,114.0,False,1,0,2,119.400000,122.2,0.498901,0.339506,0.765217,0.207547,0.792453,-5.0,-92.0,34.246017,60.800000,43.209877,0,1,1437.258986,1580.174693,0.250,108.50,108.50,1,35,81

In [22]:
df_rolling_filtered = stats_df_filtered[list(featured_columns) + ["won", "team", "season"]]
# List of numeric columns for rolling mean calculation
numeric_columns = df_rolling_filtered.select_dtypes(include='number').columns

def find_team_averages(team):
    rolling = team[numeric_columns].rolling(4).mean()
    return rolling

df_rolling_filtered = df_rolling_filtered.groupby(["team", "season"], group_keys=False).apply(find_team_averages)

df_rolling_filtered

,avg_points_scored,avg_points_allowed,shooting_percentage,three_point_percentage,free_throw_percentage,offensive_rebound_rate,defensive_rebound_rate,point_differential,cumulative_point_differential,PER_Combined,PER_Combined_opp,win_percent,win_streak,losing_streak,elo_rating,elo_rating_opp,head_to_head_win_ratio,average_points_scored,average_points_allowed,rest_days,cumulative_wins,cumulative_games_played,season
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
81,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
117,79.791667,82.625,0.357247,0.276904,0.536648,0.125818,0.624182,0.25,-3.50,86.300000,66.650000,33.333333,0.50,0.5,1492.359676,1500.000000,0.312500,104.687500,102.625000,0.75,1.00,2.5,2014.0
142,105.979167,108.750,0.474531,0.373058,0.706140,0.174869,0.825131,2.00,-1.50,86.300000,66.400000,43.333333,0.50,0.5,1492.711282,1500.000000,0.312500,105.562500,102.125000,1.00,1.50,3.5,2014.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25348,113.450000,119.900,0.503336,0.336191,0.773148,0.201389,0.798611,3.00,-63.25,50.411504,69.350000,44.371820,0.50,0.5,1432.406156,1561.724226,0.239583,116.916667,114.458333,1.75,33.50,75.5,2023.0
25367,115.350000,119.850,0.510886,0.362107,0.742608,0.196739,0.803261,-3.00,-66.25,43.773009,78.700000,44.120607,0.25,1.0,1437.783645,1547.604222,0.145833,113.416667,115.395833,1.75,33.75,76.5,2023.0
25376,117.500000,119.550,0.514165,0.386354,0.724750,0.193539,0.806461,-5.00,-71.25,40.884513,78.550000,43.880101,0.25,1.5,1434.432669,1525.121863,0.135417,114.625000,117.604167,1.50,34.00,77.5,2023.0
25415,118.150000,119.900,0.512797,0.392699,0.718373,0.192758,0.807242,-8.25,-79.50,34.246017,64.561504,43.633391,0.25,1.5,1430.390780,1533.763345,0.156250,112.937500,115.500000,1.50,34.25,78.5,2023.0
25459,118.700000,121.000,0.507409,0.387513,0.731106,0.197381,0.802619,-7.25,-86.75,34.246017,62.136504,43.396899,0.25,1.5,1426.812408,1575.870363,0.187500,112.437500,114.500000,0.75,34.50,79.5,2023.0

In [23]:
"""
Renaming the rolling columns
"""
rolling_cols = [f"{col}_4" for col in df_rolling_filtered.columns]
df_rolling_filtered.columns = rolling_cols

stats_df_Eng_and_Rolling = pd.concat([stats_df_filtered, df_rolling_filtered], axis=1)
stats_df_Eng_and_Rolling = stats_df_Eng_and_Rolling.dropna()
stats_df_Eng_and_Rolling

,date,season,mp,team,total,team_opp,total_opp,won,home,home_opp,target,avg_points_scored,avg_points_allowed,shooting_percentage,three_point_percentage,free_throw_percentage,offensive_rebound_rate,defensive_rebound_rate,point_differential,cumulative_point_differential,PER_Combined,PER_Combined_opp,win_percent,win_streak,losing_streak,elo_rating,elo_rating_opp,head_to_head_win_ratio,average_points_scored,average_points_allowed,rest_days,cumulative_wins,cumulative_games_played,avg_points_scored_4,avg_points_allowed_4,shooting_percentage_4,three_point_percentage_4,free_throw_percentage_4,offensive_rebound_rate_4,defensive_rebound_rate_4,point_differential_4,cumulative_point_differential_4,PER_Combined_4,PER_Combined_opp_4,win_percent_4,win_streak_4,losing_streak_4,elo_rating_4,elo_rating_opp_4,head_to_head_win_ratio_4,average_points_scored_4,average_points_allowed_4,rest_days_4,cumulative_wins_4,cumulative_games_played_4,season_4
117,2013-11-05,2014,240.0,ATL,105.0,SAC,100.0,True,0,1,0,104.666667,106.0,0.465021,0.391304,0.663043,0.180328,0.819672,5.0,1.0,86.300000,54.300000,50.000000,1,0,1484.702399,1500.000000,0.500,114.50,103.50,1,2,4,79.791667,82.625,0.357247,0.276904,0.536648,0.125818,0.624182,0.25,-3.50,86.300000,66.650000,33.333333,0.50,0.50,1492.359676,1500.000000,0.312500,104.687500,102.625000,0.75,1.00,2.5,2014.0
142,2013-11-07,2014,240.0,ATL,107.0,DEN,109.0,False,0,1,1,104.750000,104.5,0.469136,0.384615,0.677966,0.196203,0.803797,-2.0,-1.0,86.300000,68.300000,40.000000,0,1,1501.406424,1500.000000,0.250,102.00,100.50,1,2,5,105.979167,108.750,0.474531,0.373058,0.706140,0.174869,0.825131,2.00,-1.50,86.300000,66.400000,43.333333,0.50,0.50,1492.711282,1500.000000,0.312500,105.562500,102.125000,1.00,1.50,3.5,2014.0
170,2013-11-09,2014,240.0,ATL,104.0,ORL,94.0,True,1,0,1,105.200000,105.4,0.466507,0.367521,0.678832,0.215686,0.784314,10.0,9.0,86.300000,62.300000,50.000000,1,0,1485.341656,1500.000000,0.250,102.50,105.25,1,3,6,105.029167,105.600,0.469447,0.381605,0.682991,0.190911,0.809089,2.75,1.25,86.300000,61.475000,43.333333,0.50,0.50,1493.046697,1500.000000,0.312500,106.875000,102.937500,1.00,2.00,4.5,2014.0
197,2013-11-11,2014,240.0,ATL,103.0,CHA,94.0,True,0,1,0,104.200000,100.6,0.465278,0.366071,0.655462,0.219048,0.780952,9.0,18.0,86.300000,77.400000,57.142857,2,0,1502.016298,1500.000000,0.375,102.75,97.00,1,4,7,104.704167,104.125,0.466485,0.377378,0.668826,0.202816,0.797184,5.50,6.75,86.300000,65.575000,49.285714,1.00,0.25,1493.366694,1500.000000,0.343750,105.437500,101.562500,1.00,2.75,5.5,2014.0
223,2013-11-13,2014,240.0,ATL,91.0,NYK,95.0,False,1,0,1,104.400000,100.4,0.464037,0.353448,0.698276,0.210280,0.789720,-4.0,14.0,86.300000,65.700000,50.000000,0,1,1517.923445,1500.000000,0.250,103.50,98.50,1,4,8,104.637500,102.725,0.466239,0.367914,0.677634,0.210304,0.789696,3.25,10.00,86.300000,68.425000,49.285714,0.75,0.50,1501.671956,1500.000000,0.281250,102.687500,100.312500,1.00,3.25,6.5,2014.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25348,2023-04-02,2023,240.0,WAS,109.0,NYK,118.0,False,0,1,0,117.200000,117.8,0.520455,0.360248,0.714286,0.189055,0.810945,-9.0,-63.0,34.246017,70.500000,44.155844,0,1,1451.572477,1411.746618,0.125,110.50,112.50,4,34,77,113.450000,119.900,0.503336,0.336191,0.773148,0.201389,0.798611,3.00,-63.25,50.411504,69.350000,44.371820,0.50,0.50,1432.406156,1561.724226,0.239583,116.916667,114.458333,1.75,33.50,75.5,2023.0
25367,2023-04-04,2023,240.0,WAS,128.0,MIL,140.0,False,1,0,0,116.600000,117.0,0.518349,0.385542,0.720430,0.189320,0.810680,-12.0,-75.0,34.246017,81.200000,43.589744,0,2,1433.746419,1555.672697,0.125,117.50,118.75,1,34,78,115.350000,119.850,0.510886,0.362107,0.742608,0.196739,0.803261,-3.00,-66.25,43.773009,78.700000,44.120607,0.25,1.00,1437.783645,1547.604222,0.145833,113.416667,115.395833,1.75,33.75,76.5,2023.0
25376,2023-04-05,2023,240.0,WAS,116.0,ATL,134.0,False,0,1,1,121.400000,121.4,0.517857,0.437126,0.714286,0.180095,0.819905,-18.0,-93.0,34.246017,72.300000,43.037975,0,3,1423.141649,1559.124452,0.125,115.50,121.50,0,34,79,117.500000,119.550,0.514165,0.386354,0.724750,0.193539,0.806461,-5.00,-71.25,40.884513,78.550000,43.880101,0.25,1.50,1434.432669,1525.121863,0.135417,114.625000,117.604167,1.50,34.00,77.5,2023.0
25415,2023-04-07,2023,240.0,WAS,114.0,MIA,108.0,True,1,0,0,117.400000,123.4,0.494530,0.387879,0.724490,0.212560,0.787440,6.0,-87.0,34.246017,34.246017,43.750000,1,0,1413.102575,1608.509611,0.250,108.25,109.25,1,35,80,118.150000,119.900,0.512797,0.392699,0.718373,0.192758,0.807242,-8.25,-79.50,34.246017,64.561504,43.633391,0.25,1.50,1430.390780,1533.763345,0.156250,112.937500,115.500000,1.50,34.25,78.5,2023.0
25459,2023-04-09,2023,240.0,WAS,109.0,HOU,114.0,False,1,0,2,119.400000,122.2,0.498901,0.339506,0.765217,0.207547,0.792453,-5.0,-92.0,34.246017,60.800000,43.209877,0,1,1437.258986,1580.174693,0.250,108.50,108.50,1,35,81,118.700000,121.000,0.507409,0.387513,0.731106,0.197381,0.802619,-7.25,-86.75,34.246017,62.136504,43.396899,0.25,1.50,1426.812408,1575.870363,0.187500,112.437500,114.500000,0.75,34.50,79.5,2023.0

In [ ]:
# def shift_col(team, col_name):
#     next_col = team[col_name].shift(-1)
#     return next_col

# def add_col(df, col_name):
#     return df.groupby("team", group_keys=False).apply(lambda x: shift_col(x, col_name))

# # Add col stating if the next game will be at home
# stats_df_Eng_and_Rolling["home_next"] = add_col(stats_df_Eng_and_Rolling, "home")

# # Add col stating who the next opponent would be
# stats_df_Eng_and_Rolling["team_opp_next"] = add_col(stats_df_Eng_and_Rolling, "team_opp")

# # Add a col stating the date of the next game
# stats_df_Eng_and_Rolling["date_next"] = add_col(stats_df_Eng_and_Rolling, "date")

# # Add a col stating the PER_Combined_opp of the next game
# stats_df_Eng_and_Rolling["PER_Combined_opp_next"] = add_col(stats_df_Eng_and_Rolling, "PER_Combined_opp")

# # Add a col stating the elo_rating_opp of the next game
# stats_df_Eng_and_Rolling["elo_rating_opp_next"] = add_col(stats_df_Eng_and_Rolling, "elo_rating_opp")

# # Add a col stating the head_to_head_win_ratio of the next game
# stats_df_Eng_and_Rolling["head_to_head_win_ratio_next"] = add_col(stats_df_Eng_and_Rolling, "head_to_head_win_ratio")

# stats_df_Eng_and_Rolling

In [ ]:
# stats_df_Eng_and_Rolling.to_csv('C:/Users/User/Dropbox/RU45-Sussex OneDrive/NBA Games Prediction Model/data/feature_engineered_csv/scoring_new.csv')

In [24]:
stats_df_Eng_and_Rolling = pd.read_csv('C:/Users/User/Dropbox/RU45-Sussex OneDrive/NBA Games Prediction Model/data/feature_engineered_csv/scoring_new.csv', index_col=0)
stats_df_Eng_and_Rolling

,date,season,mp,team,total,team_opp,total_opp,won,home,home_opp,target,avg_points_scored,avg_points_allowed,shooting_percentage,three_point_percentage,free_throw_percentage,offensive_rebound_rate,defensive_rebound_rate,point_differential,cumulative_point_differential,PER_Combined,PER_Combined_opp,win_percent,win_streak,losing_streak,elo_rating,elo_rating_opp,head_to_head_win_ratio,average_points_scored,average_points_allowed,rest_days,cumulative_wins,cumulative_games_played,avg_points_scored_4,avg_points_allowed_4,shooting_percentage_4,three_point_percentage_4,free_throw_percentage_4,offensive_rebound_rate_4,defensive_rebound_rate_4,point_differential_4,cumulative_point_differential_4,PER_Combined_4,PER_Combined_opp_4,win_percent_4,win_streak_4,losing_streak_4,elo_rating_4,elo_rating_opp_4,head_to_head_win_ratio_4,average_points_scored_4,average_points_allowed_4,rest_days_4,cumulative_wins_4,cumulative_games_played_4,season_4,home_next,team_opp_next,date_next,PER_Combined_opp_next,elo_rating_opp_next,head_to_head_win_ratio_next
117,05/11/2013,2014,240,ATL,105,SAC,100,True,0,1,0,104.666667,106.0,0.465021,0.391304,0.663043,0.180328,0.819672,5,1,86.300000,54.300000,50.000000,1,0,1484.702399,1500.000000,0.500,114.50,103.50,1,2,4,79.791667,82.625,0.357247,0.276904,0.536648,0.125818,0.624182,0.25,-3.50,86.300000,66.650000,33.333333,0.50,0.50,1492.359676,1500.000000,0.312500,104.687500,102.625000,0.75,1.00,2.5,2014,0,DEN,07/11/2013,68.300000,1500.000000,0.250
142,07/11/2013,2014,240,ATL,107,DEN,109,False,0,1,1,104.750000,104.5,0.469136,0.384615,0.677966,0.196203,0.803797,-2,-1,86.300000,68.300000,40.000000,0,1,1501.406424,1500.000000,0.250,102.00,100.50,1,2,5,105.979167,108.750,0.474531,0.373058,0.706140,0.174869,0.825131,2.00,-1.50,86.300000,66.400000,43.333333,0.50,0.50,1492.711282,1500.000000,0.312500,105.562500,102.125000,1.00,1.50,3.5,2014,1,ORL,09/11/2013,62.300000,1500.000000,0.250
170,09/11/2013,2014,240,ATL,104,ORL,94,True,1,0,1,105.200000,105.4,0.466507,0.367521,0.678832,0.215686,0.784314,10,9,86.300000,62.300000,50.000000,1,0,1485.341656,1500.000000,0.250,102.50,105.25,1,3,6,105.029167,105.600,0.469447,0.381605,0.682991,0.190911,0.809089,2.75,1.25,86.300000,61.475000,43.333333,0.50,0.50,1493.046697,1500.000000,0.312500,106.875000,102.937500,1.00,2.00,4.5,2014,0,CHA,11/11/2013,77.400000,1500.000000,0.375
197,11/11/2013,2014,240,ATL,103,CHA,94,True,0,1,0,104.200000,100.6,0.465278,0.366071,0.655462,0.219048,0.780952,9,18,86.300000,77.400000,57.142857,2,0,1502.016298,1500.000000,0.375,102.75,97.00,1,4,7,104.704167,104.125,0.466485,0.377378,0.668826,0.202816,0.797184,5.50,6.75,86.300000,65.575000,49.285714,1.00,0.25,1493.366694,1500.000000,0.343750,105.437500,101.562500,1.00,2.75,5.5,2014,1,NYK,13/11/2013,65.700000,1500.000000,0.250
223,13/11/2013,2014,240,ATL,91,NYK,95,False,1,0,1,104.400000,100.4,0.464037,0.353448,0.698276,0.210280,0.789720,-4,14,86.300000,65.700000,50.000000,0,1,1517.923445,1500.000000,0.250,103.50,98.50,1,4,8,104.637500,102.725,0.466239,0.367914,0.677634,0.210304,0.789696,3.25,10.00,86.300000,68.425000,49.285714,0.75,0.50,1501.671956,1500.000000,0.281250,102.687500,100.312500,1.00,3.25,6.5,2014,1,PHI,15/11/2013,37.000000,1500.000000,0.500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25348,02/04/2023,2023,240,WAS,109,NYK,118,False,0,1,0,117.200000,117.8,0.520455,0.360248,0.714286,0.189055,0.810945,-9,-63,34.246017,70.500000,44.155844,0,1,1451.572477,1411.746618,0.125,110.50,112.50,4,34,77,113.450000,119.900,0.503336,0.336191,0.773148,0.201389,0.798611,3.00,-63.25,50.411504,69.350000,44.371820,0.50,0.50,1432.406156,1561.724226,0.239583,116.916667,114.458333,1.75,33.50,75.5,2023,1,MIL,04/04/2023,81.200000,1555.672697,0.125
25367,04/04/2023,2023,240,WAS,128,MIL,140,False,1,0,0,116.600000,117.0,0.518349,0.385542,0.720430,0.189320,0.810680,-12,-75,34.246017,81.200000,43.589744,0,2,1433.746419,1555.672697,0.125,117.50,118.75,1,34,78,115.350000,119.850,0.510886,0.362107,0.742608,0.196739,0.803261,-3.00,-66.25,43.773009,78.700000,44.120607,0.25,1.00,1437.783645,1547.604222,0.145833,113.416667,115.395833,1.75,33.75,76.5,2023,0,ATL,05/04/2023,72.300000,1559.124452,0.125
25376,05/04/2023,2023,240,WAS,116,ATL,134,False,0,1,1,121.400000,121.4,0.517857,0.437126,0.714286,0.180095,0.819905,-18,-93,34.246017,72.300000,43.037975,0,3,1423.141649,1559.124452,0.125,115.50,121.50,0,34,79,117.500000,119.550,0.514165,0.386354,0.724750,0.193539,0.806461,-5.00,-71.25,40.884513,78.550000,43.880101,0.25,1.50,1434.432669,1525.121863,0.135417,114.625000,117.604167,1.50,34.00,77.5,2023,1,MIA,07/04/2023,34.246017,1608.509611,0.250
25415,07/04/2023,2023,240,WAS,114,MIA,108,True,1,0,0,117.400000,123.4,0.494530,0.387879,0.724490,0.212560,0.787440,6,-87,34.246017,34.246017,43.750000,1,0,1413.102575,1608.509611,0.250,108.25,109.25,1,35,80,118.150000,119.900,0.512797,0.392699,0.718373,0.192758,0.807242,-8.25,-79.50,34.246017,64.561504,43.633391,0.25,1.50,1430.390780,1533.763345,0.156250,112.937500,115.500000,1.50,34.25,78.5,2023,1,HOU,09/04/2023,60.800000,1580.174693,0.250
25459,09/04/2023,2023,240,WAS,109,HOU,114,False,1,0,2,119.400000,122.2,0.498901,0.339506,0.765217,0.207547,0.792453,-5,-92,34.246017,60.800000,43.209877,0,1,1437.258986,1580.174693,0.250,108.50,108.50,1,35,81,118.700000,121.000,0.507409,0.387513,0.731106,0.197381,0.802619,-7.25,-86.75,34.246017,62.136504,43.396899,0.25,1.50,1426.812408,1575.870363,0.187500,112.437500,114.500000,0.75,34.50,79.5,2023,0,IND,26/10/2023,NaN,NaN,NaN

In [18]:
# """
# This are the last games for each team where the next games are not known
# """
# target_2_rows = stats_df_Eng_and_Rolling[stats_df_Eng_and_Rolling["target"] == 2]
# target_2_rows

In [25]:
%%time
# Define a function to calculate the PER_Combined_opp_next based on the opponent in the last game
def calculate_PER_Combined_opp_next(row, stats_df):
    team = row['team']
    last_opponent = row['team_opp']
    
    # Find the most recent PER_Combined_opp for the last opponent
    last_opponent_data = stats_df[(stats_df['team'] == last_opponent)]
    last_PER_Combined_opp = last_opponent_data['PER_Combined_opp'].iloc[-1]
    
    return last_PER_Combined_opp

# Calculate PER_Combined_opp_next only for rows where target is 2
stats_df_Eng_and_Rolling.loc[stats_df_Eng_and_Rolling['target'] == 2, 'PER_Combined_opp_next'] = stats_df_Eng_and_Rolling[stats_df_Eng_and_Rolling['target'] == 2].apply(lambda row: calculate_PER_Combined_opp_next(row, stats_df_Eng_and_Rolling), axis=1)

# Define a function to calculate the elo_rating_opp_next based on the opponent in the last game
def calculate_elo_rating_opp_next(row, stats_df):
    team = row['team']
    last_opponent = row['team_opp']
    
    # Find the most recent elo_rating_opp for the last opponent
    last_opponent_data = stats_df[(stats_df['team'] == last_opponent)]
    last_elo_rating_opp = last_opponent_data['elo_rating_opp'].iloc[-1]
    
    return last_elo_rating_opp

# Calculate elo_rating_opp_next only for rows where target is 2
stats_df_Eng_and_Rolling.loc[stats_df_Eng_and_Rolling['target'] == 2, 'elo_rating_opp_next'] = stats_df_Eng_and_Rolling[stats_df_Eng_and_Rolling['target'] == 2].apply(lambda row: calculate_elo_rating_opp_next(row, stats_df_Eng_and_Rolling), axis=1)

# Define a function to calculate the head_to_head_win_ratio_next based on historical games against the opponent
def calculate_head_to_head_win_ratio_next(row, stats_df):
    team = row['team']
    last_opponent = row['team_opp']
    
    # Find all previous games between the team and the last opponent
    historical_games = stats_df[((stats_df['team'] == team) & (stats_df['team_opp'] == last_opponent)) | ((stats_df['team'] == last_opponent) & (stats_df['team_opp'] == team))]
    
    # Calculate the win ratio based on historical games
    total_games = len(historical_games)
    if total_games > 0:
        wins = historical_games[team == historical_games['team']]['won'].sum()
        win_ratio = wins / total_games
    else:
        win_ratio = 0.0
    
    return win_ratio

# Calculate head_to_head_win_ratio_next only for rows where target is 2
stats_df_Eng_and_Rolling.loc[stats_df_Eng_and_Rolling['target'] == 2, 'head_to_head_win_ratio_next'] = stats_df_Eng_and_Rolling[stats_df_Eng_and_Rolling['target'] == 2].apply(lambda row: calculate_head_to_head_win_ratio_next(row, stats_df_Eng_and_Rolling), axis=1)

# Display the updated DataFrame with the populated columns
stats_df_Eng_and_Rolling

CPU times: total: 391 ms
Wall time: 415 ms

,date,season,mp,team,total,team_opp,total_opp,won,home,home_opp,target,avg_points_scored,avg_points_allowed,shooting_percentage,three_point_percentage,free_throw_percentage,offensive_rebound_rate,defensive_rebound_rate,point_differential,cumulative_point_differential,PER_Combined,PER_Combined_opp,win_percent,win_streak,losing_streak,elo_rating,elo_rating_opp,head_to_head_win_ratio,average_points_scored,average_points_allowed,rest_days,cumulative_wins,cumulative_games_played,avg_points_scored_4,avg_points_allowed_4,shooting_percentage_4,three_point_percentage_4,free_throw_percentage_4,offensive_rebound_rate_4,defensive_rebound_rate_4,point_differential_4,cumulative_point_differential_4,PER_Combined_4,PER_Combined_opp_4,win_percent_4,win_streak_4,losing_streak_4,elo_rating_4,elo_rating_opp_4,head_to_head_win_ratio_4,average_points_scored_4,average_points_allowed_4,rest_days_4,cumulative_wins_4,cumulative_games_played_4,season_4,home_next,team_opp_next,date_next,PER_Combined_opp_next,elo_rating_opp_next,head_to_head_win_ratio_next
117,05/11/2013,2014,240,ATL,105,SAC,100,True,0,1,0,104.666667,106.0,0.465021,0.391304,0.663043,0.180328,0.819672,5,1,86.300000,54.300000,50.000000,1,0,1484.702399,1500.000000,0.500,114.50,103.50,1,2,4,79.791667,82.625,0.357247,0.276904,0.536648,0.125818,0.624182,0.25,-3.50,86.300000,66.650000,33.333333,0.50,0.50,1492.359676,1500.000000,0.312500,104.687500,102.625000,0.75,1.00,2.5,2014,0,DEN,07/11/2013,68.300000,1500.000000,0.250000
142,07/11/2013,2014,240,ATL,107,DEN,109,False,0,1,1,104.750000,104.5,0.469136,0.384615,0.677966,0.196203,0.803797,-2,-1,86.300000,68.300000,40.000000,0,1,1501.406424,1500.000000,0.250,102.00,100.50,1,2,5,105.979167,108.750,0.474531,0.373058,0.706140,0.174869,0.825131,2.00,-1.50,86.300000,66.400000,43.333333,0.50,0.50,1492.711282,1500.000000,0.312500,105.562500,102.125000,1.00,1.50,3.5,2014,1,ORL,09/11/2013,62.300000,1500.000000,0.250000
170,09/11/2013,2014,240,ATL,104,ORL,94,True,1,0,1,105.200000,105.4,0.466507,0.367521,0.678832,0.215686,0.784314,10,9,86.300000,62.300000,50.000000,1,0,1485.341656,1500.000000,0.250,102.50,105.25,1,3,6,105.029167,105.600,0.469447,0.381605,0.682991,0.190911,0.809089,2.75,1.25,86.300000,61.475000,43.333333,0.50,0.50,1493.046697,1500.000000,0.312500,106.875000,102.937500,1.00,2.00,4.5,2014,0,CHA,11/11/2013,77.400000,1500.000000,0.375000
197,11/11/2013,2014,240,ATL,103,CHA,94,True,0,1,0,104.200000,100.6,0.465278,0.366071,0.655462,0.219048,0.780952,9,18,86.300000,77.400000,57.142857,2,0,1502.016298,1500.000000,0.375,102.75,97.00,1,4,7,104.704167,104.125,0.466485,0.377378,0.668826,0.202816,0.797184,5.50,6.75,86.300000,65.575000,49.285714,1.00,0.25,1493.366694,1500.000000,0.343750,105.437500,101.562500,1.00,2.75,5.5,2014,1,NYK,13/11/2013,65.700000,1500.000000,0.250000
223,13/11/2013,2014,240,ATL,91,NYK,95,False,1,0,1,104.400000,100.4,0.464037,0.353448,0.698276,0.210280,0.789720,-4,14,86.300000,65.700000,50.000000,0,1,1517.923445,1500.000000,0.250,103.50,98.50,1,4,8,104.637500,102.725,0.466239,0.367914,0.677634,0.210304,0.789696,3.25,10.00,86.300000,68.425000,49.285714,0.75,0.50,1501.671956,1500.000000,0.281250,102.687500,100.312500,1.00,3.25,6.5,2014,1,PHI,15/11/2013,37.000000,1500.000000,0.500000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25348,02/04/2023,2023,240,WAS,109,NYK,118,False,0,1,0,117.200000,117.8,0.520455,0.360248,0.714286,0.189055,0.810945,-9,-63,34.246017,70.500000,44.155844,0,1,1451.572477,1411.746618,0.125,110.50,112.50,4,34,77,113.450000,119.900,0.503336,0.336191,0.773148,0.201389,0.798611,3.00,-63.25,50.411504,69.350000,44.371820,0.50,0.50,1432.406156,1561.724226,0.239583,116.916667,114.458333,1.75,33.50,75.5,2023,1,MIL,04/04/2023,81.200000,1555.672697,0.125000
25367,04/04/2023,2023,240,WAS,128,MIL,140,False,1,0,0,116.600000,117.0,0.518349,0.385542,0.720430,0.189320,0.810680,-12,-75,34.246017,81.200000,43.589744,0,2,1433.746419,1555.672697,0.125,117.50,118.75,1,34,78,115.350000,119.850,0.510886,0.362107,0.742608,0.196739,0.803261,-3.00,-66.25,43.773009,78.700000,44.120607,0.25,1.00,1437.783645,1547.604222,0.145833,113.416667,115.395833,1.75,33.75,76.5,2023,0,ATL,05/04/2023,72.300000,1559.124452,0.125000
25376,05/04/2023,2023,240,WAS,116,ATL,134,False,0,1,1,121.400000,121.4,0.517857,0.437126,0.714286,0.180095,0.819905,-18,-93,34.246017,72.300000,43.037975,0,3,1423.141649,1559.124452,0.125,115.50,121.50,0,34,79,117.500000,119.550,0.514165,0.386354,0.724750,0.193539,0.806461,-5.00,-71.25,40.884513,78.550000,43.880101,0.25,1.50,1434.432669,1525.121863,0.135417,114.625000,117.604167,1.50,34.00,77.5,2023,1,MIA,07/04/2023,34.246017,1608.509611,0.250000
25415,07/04/2023,2023,240,WAS,114,MIA,108,True,1,0,0,117.400000,123.4,0.494530,0.387879,0.724490,0.212560,0.787440,6,-87,34.246017,34.246017,43.750000,1,0,1413.102575,1608.509611,0.250,108.25,109.25,1,35,80,118.150000,119.900,0.512797,0.392699,0.718373,0.192758,0.807242,-8.25,-79.50,34.246017,64.561504,43.633391,0.25,1.50,1430.390780,1533.763345,0.156250,112.937500,115.500000,1.50,34.25,78.5,2023,1,HOU,09/04/2023,60.800000,1580.174693,0.250000
25459,09/04/2023,2023,240,WAS,109,HOU,114,False,1,0,2,119.400000,122.2,0.498901,0.339506,0.765217,0.207547,0.792453,-5,-92,34.246017,60.800000,43.209877,0,1,1437.258986,1580.174693,0.250,108.50,108.50,1,35,81,118.700000,121.000,0.507409,0.387513,0.731106,0.197381,0.802619,-7.25,-86.75,34.246017,62.136504,43.396899,0.25,1.50,1426.812408,1575.870363,0.187500,112.437500,114.500000,0.75,34.50,79.5,2023,0,IND,26/10/2023,34.246017,1453.308257,0.157895

In [26]:
"""
This are the last games for each team where the next games are not known
"""
target_2_rows = stats_df_Eng_and_Rolling[stats_df_Eng_and_Rolling["target"] == 2]
target_2_rows

,date,season,mp,team,total,team_opp,total_opp,won,home,home_opp,target,avg_points_scored,avg_points_allowed,shooting_percentage,three_point_percentage,free_throw_percentage,offensive_rebound_rate,defensive_rebound_rate,point_differential,cumulative_point_differential,PER_Combined,PER_Combined_opp,win_percent,win_streak,losing_streak,elo_rating,elo_rating_opp,head_to_head_win_ratio,average_points_scored,average_points_allowed,rest_days,cumulative_wins,cumulative_games_played,avg_points_scored_4,avg_points_allowed_4,shooting_percentage_4,three_point_percentage_4,free_throw_percentage_4,offensive_rebound_rate_4,defensive_rebound_rate_4,point_differential_4,cumulative_point_differential_4,PER_Combined_4,PER_Combined_opp_4,win_percent_4,win_streak_4,losing_streak_4,elo_rating_4,elo_rating_opp_4,head_to_head_win_ratio_4,average_points_scored_4,average_points_allowed_4,rest_days_4,cumulative_wins_4,cumulative_games_played_4,season_4,home_next,team_opp_next,date_next,PER_Combined_opp_next,elo_rating_opp_next,head_to_head_win_ratio_next
25551,27/04/2023,2023,240,ATL,120,BOS,128,False,1,0,2,115.0,119.8,0.454545,0.365079,0.825000,0.279817,0.720183,-8,3,86.500000,90.200000,49.438202,0,1,1517.763929,1560.664522,0.111111,115.000000,123.000000,1,44,89,113.90,117.80,0.455815,0.313663,0.744242,0.304812,0.695188,-1.50,10.00,86.500000,90.200000,49.715872,0.50,0.50,1504.628515,1573.799936,0.111111,115.000000,123.000000,1.25,43.50,87.5,2023,0,CHA,26/10/2023,71.700000,1564.340759,0.212766
25629,29/05/2023,2023,240,BOS,84,MIA,103,False,1,0,2,107.4,107.6,0.461722,0.316327,0.794643,0.269767,0.730233,-19,602,90.200000,71.700000,66.666667,0,1,1608.248197,1564.340759,0.227273,108.454545,109.727273,1,68,102,108.35,109.05,0.465980,0.339208,0.790331,0.251543,0.748457,3.00,612.50,85.650000,71.700000,66.915016,1.50,0.25,1583.559877,1589.029078,0.227273,108.454545,109.727273,1.00,67.25,100.5,2023,0,NYK,26/10/2023,97.300000,1662.330020,0.273585
25516,22/04/2023,2023,240,BRK,88,PHI,96,False,1,0,2,97.6,107.4,0.431421,0.325714,0.794393,0.201058,0.798942,-8,25,70.700000,53.400000,52.325581,0,5,1462.697001,1623.251445,0.000000,101.500000,112.750000,1,45,86,103.80,108.85,0.446630,0.336454,0.781232,0.212001,0.787999,-11.25,36.50,70.700000,76.950000,53.263763,0.00,3.50,1478.356233,1607.592214,0.000000,101.500000,112.750000,2.25,45.00,84.5,2023,1,CLE,26/10/2023,90.200000,1629.487892,0.180851
25444,09/04/2023,2023,240,CHA,106,CLE,95,True,0,1,2,109.0,123.0,0.482185,0.388571,0.717172,0.201923,0.798077,11,-512,34.246017,37.800000,32.926829,1,0,1403.926676,1569.328725,0.125000,110.000000,115.250000,1,27,82,110.25,120.05,0.483581,0.393390,0.724384,0.206486,0.793514,-8.00,-513.75,34.246017,65.150000,32.609247,0.25,2.25,1420.285225,1551.700738,0.093750,111.625000,120.437500,1.25,26.25,80.5,2023,1,ATL,26/10/2023,90.800000,1482.047706,0.171875
25469,14/04/2023,2023,240,CHI,91,MIA,102,False,0,1,2,104.8,105.2,0.464853,0.278146,0.774194,0.186275,0.813725,-11,99,78.800000,87.000000,48.809524,0,1,1529.803261,1552.358085,0.375000,108.250000,103.000000,1,41,84,109.20,106.95,0.480851,0.298303,0.796096,0.170306,0.829694,4.50,99.75,67.661504,65.261504,48.783938,1.50,0.25,1511.597898,1449.046837,0.406250,115.687500,106.687500,1.25,40.25,82.5,2023,1,OKC,26/10/2023,97.300000,1662.330020,0.171875
25548,26/04/2023,2023,240,CLE,95,NYK,106,False,1,0,2,94.2,99.6,0.433498,0.299363,0.765957,0.265000,0.735000,-11,414,91.900000,90.800000,59.770115,0,3,1518.260160,1482.047706,0.111111,99.111111,103.666667,2,52,87,102.15,100.55,0.453804,0.355399,0.795799,0.253867,0.746133,-5.75,431.75,91.900000,90.800000,60.829116,0.25,1.50,1540.472535,1459.835331,0.111111,99.111111,103.666667,1.75,52.00,85.5,2023,0,BRK,26/10/2023,71.700000,1561.309875,0.294872
25442,09/04/2023,2023,240,DAL,117,SAS,138,False,1,0,2,119.0,122.2,0.503432,0.368664,0.773196,0.165000,0.835000,-21,6,34.246017,34.246017,46.341463,0,2,1426.923259,1486.807005,0.375000,130.500000,126.750000,1,38,82,118.30,118.90,0.508472,0.386017,0.807421,0.146212,0.853788,-5.50,22.25,64.736504,60.473009,46.897622,0.25,1.50,1428.937487,1519.965593,0.177083,123.583333,127.312500,1.00,37.75,80.5,2023,0,SAS,26/10/2023,34.246017,1553.831969,0.211111
25639,12/06/2023,2023,240,DEN,94,MIA,89,True,1,0,2,108.4,100.8,0.502513,0.373134,0.821429,0.204651,0.795349,5,446,97.300000,71.700000,68.316832,3,0,1661.132883,1481.944569,0.428571,108.428571,101.285714,2,69,101,111.15,104.40,0.497387,0.372725,0.820794,0.205471,0.794529,7.50,432.00,97.300000,71.700000,67.835135,1.50,0.25,1655.401775,1487.675677,0.428571,108.428571,101.285714,1.75,67.50,99.5,2023,1,LAL,25/10/2023,97.300000,1662.330020,0.340000
25443,09/04/2023,2023,240,DET,81,CHI,103,False,0,1,2,108.6,118.2,0.476543,0.405229,0.811966,0.230366,0.769634,-22,-668,34.246017,78.800000,20.987654,0,1,1239.130115,1542.610636,0.000000,105.500000,119.500000,1,17,81,106.85,119.90,0.462485,0.365120,0.796012,0.239463,0.760537,-10.75,-651.25,34.246017,68.750000,20.750910,0.25,5.00,1224.329426,1489.682869,0.145833,112.354167,116.354167,0.75,16.50,79.5,2023,0,MIA,26/10/2023,87.000000,1552.358085,0.185714
25604,12/05/2023,2023,240,GSW,101,LAL,122,False,0,1,2,111.6,110.8,0.455319,0.372093,0.757576,0.252137,0.747863,-21,146,78.500000,94.400000,52.631579,0,1,1544.370586,1570.272836,0.150000,110.100000,113.100000,1,50,95,112.55,110.75,0.441112,0.368314,0.697273,0.274238,0.725762,-9.75,155.00,78.500000,94.400000,52.943027,0.25,1.00,1541.356618,1573.286804,0.150000,110.100000,113.100000,1.00,49.50,93.5,2023,1,PHO,25/10/2023,97.300000,1601.742340,0.265060
25458,09/04/2023,2023,240,HOU,114,WAS,109,True,0,1,2,114.8,121.2,0.462343,0.338028,0.750000,0.347280,0.652720,5,-650,60.800000,34.246017,25.925926,3,0,1340.532442,1453.308257,0.250000,108.500000,108.500000,1,21,81,111.45,125.65,0.469972,0.315891,0.746056,0.348168,0.651832,1.00,-660.50,72.950000,65.048009,24.513370,1.50,2.00,1311.347179,1512.009084,0.197917,113.395833,118.312500,1.75,19.50,79.5,2023,0,ORL,26/10/2023,60.800000,1580.174693,0.342105
25453,09/04/2023,2023,240,IND,141,NYK,136,True,0,1,2,117.8,130.2,0.478747,0.398601,0.787879,0.276923,0.723077,5,-265,38.500000,49.300000,41.975309,1,0,1365.000435,1487.416315,0.125000,122.250000,125.500000,1,34,81,117.30,131.50,0.487050,0.374593,0.783993,0.274132,0.725868,-5.25,-263.00,38.500000,56.186504,41.826288,0.25,4.50,1384.128034,1477.474168,0.156250,118.125000,122.125000,1.75,33.25,79.5,2023,1,WAS,26/10/2023,71.700000,1561.309875,0.308824
25540,25/04/2023,2023,240,LAC,130,PHO,136,False,0,1,2,113.4,117.6,0.468750,0.339744,0.789916,0.270531,0.729469,-6,23,53.400000,98.800000,52.325581,0,4,1541.417263,1547.255690,0.166667,111.444444,117.111111,2,45,86,119.15,118.40,0.483839,0.345734,0.805719,0.264040,0.735960,-9.25,34.75,59.375000,98.800000,53.263763,0.00,2.50,1569.142508,1519.530444,0.166667,111.444444,117.111111,1.25,45.00,84.5,2023,1,POR,26/10/2023,97.300000,1561.658650,0.322581
25621,22/05/2023,2023,240,LAL,111,DEN,113,False,1,0,2,113.0,116.2,0.487864,0.374101,0.804348,0.165829,0.834171,-2,79,94.400000,97.300000,52.040816,0,4,1580.197407,1601.742340,0.125000,112.875000,115.250000,1,51,98,113.50,112.15,0.489829,0.382223,0.808647,0.162580,0.837420,-6.00,87.25,94.400000,97.300000,52.856837,0.00,2.50,1606.681037,1575.258711,0.125000,112.875000,115.250000,1.50,51.00,96.5,2023,0,DEN,25/10/2023,71.700000,1481.944569,0.204545
25555,28/04/2023,2023,240,MEM,85,LAL,125,False,0,1,2,108.6,109.6,0.422269,0.310881,0.852632,0.277778,0.722222,-40,264,64.000000,94.400000,59.770115,0,1,1565.020610,1520.384139,0.166667,108.111111,112.888889,1,52,87,110.30,113.05,0.443992,0.315892,0.819006,0.264750,0.735250,-9.75,287.00,64.000000,94.400000,60.237379,0.25,1.00,1567.677876,1517.726873,0.166667,108.111111,112.888889,1.25,51.50,85.5,2023,1,NOP,26/10/2023,97.300000,1601.742340,0.268293
25638,12/06/2023,2023,240,MIA,89,DEN,94,False,0,1,2,99.2,102.6,0.437209,0.388889,0.850746,0.236559,0.763441,-5,9,71.700000,97.300000,54.205607,0,3,1569.666234,1662.330020,0.071429,101.285714,108.428571,2,58,107,100.10,102.50,0.434214,0.403975,0.832212,0.260542,0.739458,-7.50,23.00,71.700000,97.300000,54.982479,0.25,1.50,1581.637197,1650.359057,0.071429,101.285714,108.428571,1.75,58.00,105.5,2023,1,DET,26/10/2023,71.700000,1481.944569,0.160000
25543,26/04/2023,2023,265,MIL,126,MIA,128,False,1,0,2,114.6,122.6,0.475771,0.367150,0.783133,0.235294,0.764706,-2,272,78.900000,71.700000,67.816092,0,3,1616.954602,1602.492648,0.166667,115.777778,117.000000,1,59,87,115.30,122.70,0.477333,0.384923,0.767832,0.227449,0.772551,-3.25,281.50,71.700000,71.700000,69.017651,0.25,1.50,1637.507940,1581.939310,0.166667,115.777778,117.000000,1.50,59.00,85.5,2023,1,PHI,27/10/2023,97.300000,1662.330020,0.247312
25538,25/04/2023,2023,240,MIN,109,DEN,112,False,0,1,2,107.6,110.8,0.460241,0.381250,0.778689,0.211823,0.788177,-3,-16,52.400000,97.300000,50.000000,0,1,1520.720680,1595.119146,0.166667,112.111111,116.444444,1,44,88,107.90,110.05,0.463059,0.388685,0.771893,0.184835,0.815165,-3.75,-14.50,63.500000,97.300000,50.290737,0.25,1.50,1513.973360,1601.866466,0.166667,112.111111,116.444444,1.25,43.50,86.5,2023,0,TOR,26/10/2023,71.700000,1481.944569,0.162791
25465,12/04/2023,2023,240,NOP,118,OKC,123,False,1,0,2,116.8,116.8,0.480094,0.384000,0.840000,0.215962,0.784038,-5,150,62.100000,71.200000,50.602410,0,2,1507.219556,1488.515443,0.300000,110.000000,111.800000,2,42,83,115.55,112.50,0.482367,0.429214,0.837290,0.222881,0.777119,1.25,154.25,62.100000,56.336504,51.230943,0.75,0.75,1510.519371,1481.471761,0.241667,111.229167,115.637500,1.00,41.75,81.5,2023,0,MEM,26/10/2023,67.200000,1511.043460,0.208333
25603,12/05/2023,2023,240,NYK,92,MIA,96,False,0,1,2,102.2,106.0,0.445813,0.301136,0.705882,0.255411,0.744589,-4,244,74.500000,71.700000,56.989247,0,1,1572.397124,1561.309875,0.250000,105.200000,106.900000,1,53,93,102.05,101.90,0.442144,0.292447,0.700889,0.276618,0.723382,-5.50,244.50,78.575000,71.700000,57.379644,0.25,1.00,1572.357887,1561.349112,0.250000,105.200000,106.900000,1.50,52.50,91.5,2023,1,BOS,26/10/2023,97.300000,1662.330020,0.166667
25468,14/04/2023,2023,240,OKC,95,MIN,120,False,0,1,2,119.0,116.0,0.447826,0.329670,0.820000,0.296296,0.703704,-25,73,71.200000,67.200000,49.397590,0,1,1541.102749,1511.043460,0.100000,110.800000,118.200000,1,41,83,118.70,118.60,0.450922,0.340523,0.803968,0.288199,0.711801,2.75,85.50,61.961504,49.448009,49.382577,1.50,0.25,1519.374311,1496.180022,0.231250,114.025000,112.862500,1.50,40.25,81.5,2023,0,CHI,26/10/2023,97.300000,1595.119146,0.300000
25439,09/04/2023,2023,240,ORL,110,MIA,123,False,0,1,2,105.4,110.2,0.444700,0.335165,0.740741,0.225108,0.774892,-13,-217,49.800000,59.400000,40.740741,0,4,1446.276570,1514.766517,0.125000,111.000000,113.500000,1,33,81,112.80,109.50,0.477795,0.368196,0.749645,0.202631,0.797369,-14.50,-192.75,50.098009,64.061504,41.517646,0.00,2.50,1471.603324,1473.755483,0.072917,102.541667,110.333333,0.75,33.00,79.5,2023,1,HOU,26/10/2023,97.300000,1662.330020,0.159420
25606,14/05/2023,2023,240,PHI,88,BOS,112,False,0,1,2,101.2,109.6,0.424390,0.333333,0.872881,0.196262,0.803738,-24,330,84.800000,90.200000,65.217391,0,2,1650.616271,1629.487892,0.181818,103.545455,110.727273,2,60,92,103.55,110.20,0.436929,0.366879,0.876222,0.220852,0.779148,-5.00,349.50,84.800000,90.200000,66.027565,0.75,0.75,1653.249810,1626.854352,0.181818,103.545455,110.727273,1.25,59.75,90.5,2023,0,MIL,27/10/2023,71.700000,1564.340759,0.180000
25598,11/05/2023,2023,240,PHO,100,DEN,125,False,1,0,2,109.2,115.6,0.480813,0.318841,0.817204,0.233503,0.766497,-25,138,47.900000,97.300000,54.347826,0,2,1575.944715,1561.658650,0.166667,109.666667,119.111111,1,50,92,113.00,115.50,0.489059,0.339126,0.832574,0.249884,0.750116,-7.25,163.50,72.800000,97.300000,54.976154,0.75,0.75,1578.030482,1559.572882,0.166667,109.666667,119.111111,1.50,49.75,90.5,2023,0,GSW,25/10/2023,71.700000,1481.944569,0.238095
25455,09/04/2023,2023,240,POR,101,GSW,157,False,1,0,2,109.6,121.8,0.455128,0.327485,0.733333,0.228155,0.771845,-56,-305,34.246017,63.800000,40.740741,0,4,1356.406246,1668.138649,0.125000,110.750000,130.000000,0,33,81,102.20,119.15,0.428375,0.296558,0.752076,0.226890,0.773110,-19.75,-257.00,34.246017,59.836504,41.517646,0.00,2.50,1367.684056,1586.358740,0.166667,116.458333,121.791667,0.75,33.00,79.5,2023,0,LAC,26/10/2023,94.400000,1570.272836,0.138298
25561,30/04/2023,2023,240,SAC,100,GSW,120,False,1,0,2,114.0,113.6,0.435789,0.306533,0.785124,0.285106,0.714894,-20,178,86.900000,78.500000,56.818182,0,1,1571.347138,1640.166413,0.181818,113.909091,117.363636,1,50,88,111.70,115.45,0.435419,0.292818,0.756978,0.294745,0.705255,-2.25,185.25,86.900000,78.500000,57.228312,0.25,1.50,1565.013801,1646.499749,0.181818,113.909091,117.363636,1.50,49.50,86.5,2023,0,UTA,26/10/2023,94.400000,1570.272836,0.134146
25436,09/04/2023,2023,240,SAS,138,DAL,117,True,0,1,2,122.2,131.4,0.470833,0.363636,0.805085,0.285088,0.714912,21,-823,34.246017,34.246017,26.829268,1,0,1312.112015,1553.831969,0.125000,126.750000,130.500000,0,22,82,118.00,130.00,0.461497,0.336793,0.789536,0.259884,0.740116,-4.50,-829.25,34.246017,61.623009,26.080412,0.50,0.50,1308.243071,1514.507898,0.125000,116.833333,126.958333,0.75,21.00,80.5,2023,1,DAL,26/10/2023,34.246017,1486.807005,0.288889
25467,12/04/2023,2023,240,TOR,105,CHI,109,False,1,0,2,112.8,106.2,0.474468,0.310127,0.802326,0.263889,0.736111,-4,124,87.900000,78.800000,50.000000,0,1,1555.851251,1524.790234,0.250000,104.750000,105.500000,2,41,82,113.00,102.55,0.475586,0.306828,0.804649,0.294389,0.705611,-2.75,123.75,74.925000,54.661504,50.312549,0.25,1.00,1553.727775,1582.213176,0.093750,105.750000,109.937500,1.00,40.50,80.5,2023,1,MIN,26/10/2023,87.000000,1552.358085,0.214286
25438,09/04/2023,2023,240,UTA,117,LAL,128,False,0,1,2,114.6,119.2,0.473913,0.300000,0.780702,0.216867,0.783133,-11,-77,34.246017,82.900000,45.121951,0,1,1432.070272,1486.826344,0.250000,129.750000,123.750000,0,37,82,115.60,119.25,0.484925,0.311144,0.777298,0.207701,0.792299,-6.25,-66.75,34.246017,82.375000,45.342646,0.25,2.00,1424.835588,1511.345363,0.218750,120.625000,120.625000,0.75,36.50,80.5,2023,1,SAC,26/10/2023,97.300000,1601.742340,0.303030
25459,09/04/2023,2023,240,WAS,109,HOU,114,False,1,0,2,119.4,122.2,0.498901,0.339506,0.765217,0.207547,0.792453,-5,-92,34.246017,60.800000,43.209877,0,1,1437.258986,1580.174693,0.250000,108.500000,108.500000,1,35,81,118.70,121.00,0.507409,0.387513,0.731106,0.197381,0.802619,-7.25,-86.75,34.246017,62.136504,43.396899,0.25,1.50,1426.812408,1575.870363,0.187500,112.437500,114.500000,0.75,34.50,79.5,2023,0,IND,26/10/2023,34.246017,1453.308257,0.157895

In [31]:
# Get the indices of the rows where the "target" column is equal to 2
target_2_indices = target_2_rows.index

# Display the indices
print(target_2_indices)

Int64Index([25551, 25629, 25516, 25444, 25469, 25548, 25442, 25639, 25443,
            25604, 25458, 25453, 25540, 25621, 25555, 25638, 25543, 25538,
            25465, 25603, 25468, 25439, 25606, 25598, 25455, 25561, 25436,
            25467, 25438, 25459],
           dtype='int64')

In [27]:
"""
Now we will pull in the same information about the oponent team
"""

# Merge the original DataFrame with the new DataFrame based on team and date_next
full_eng = stats_df_Eng_and_Rolling.merge(
    stats_df_Eng_and_Rolling[rolling_cols + ["team_opp_next", "date_next", "team"]],
    left_on=["team", "date_next"],
    right_on=["team_opp_next", "date_next"]
)

# Print or display the merged DataFrame
full_eng

,date,season,mp,team_x,total,team_opp,total_opp,won,home,home_opp,target,avg_points_scored,avg_points_allowed,shooting_percentage,three_point_percentage,free_throw_percentage,offensive_rebound_rate,defensive_rebound_rate,point_differential,cumulative_point_differential,PER_Combined,PER_Combined_opp,win_percent,win_streak,losing_streak,elo_rating,elo_rating_opp,head_to_head_win_ratio,average_points_scored,average_points_allowed,rest_days,cumulative_wins,cumulative_games_played,avg_points_scored_4_x,avg_points_allowed_4_x,shooting_percentage_4_x,three_point_percentage_4_x,free_throw_percentage_4_x,offensive_rebound_rate_4_x,defensive_rebound_rate_4_x,point_differential_4_x,cumulative_point_differential_4_x,PER_Combined_4_x,PER_Combined_opp_4_x,win_percent_4_x,win_streak_4_x,losing_streak_4_x,elo_rating_4_x,elo_rating_opp_4_x,head_to_head_win_ratio_4_x,average_points_scored_4_x,average_points_allowed_4_x,rest_days_4_x,cumulative_wins_4_x,cumulative_games_played_4_x,season_4_x,home_next,team_opp_next_x,date_next,PER_Combined_opp_next,elo_rating_opp_next,head_to_head_win_ratio_next,avg_points_scored_4_y,avg_points_allowed_4_y,shooting_percentage_4_y,three_point_percentage_4_y,free_throw_percentage_4_y,offensive_rebound_rate_4_y,defensive_rebound_rate_4_y,point_differential_4_y,cumulative_point_differential_4_y,PER_Combined_4_y,PER_Combined_opp_4_y,win_percent_4_y,win_streak_4_y,losing_streak_4_y,elo_rating_4_y,elo_rating_opp_4_y,head_to_head_win_ratio_4_y,average_points_scored_4_y,average_points_allowed_4_y,rest_days_4_y,cumulative_wins_4_y,cumulative_games_played_4_y,season_4_y,team_opp_next_y,team_y
0,07/11/2013,2014,240,ATL,107,DEN,109,False,0,1,1,104.75,104.5,0.469136,0.384615,0.677966,0.196203,0.803797,-2,-1,86.300000,68.300000,40.000000,0,1,1501.406424,1500.000000,0.250,102.000000,100.50,1,2,5,105.979167,108.750,0.474531,0.373058,0.706140,0.174869,0.825131,2.00,-1.50,86.300000,66.400000,43.333333,0.50,0.50,1492.711282,1500.000000,0.312500,105.562500,102.125000,1.00,1.50,3.5,2014,1,ORL,09/11/2013,62.300000,1500.000000,0.250000,103.287500,101.420833,0.457471,0.426339,0.678029,0.243594,0.756406,11.75,24.25,62.300,82.575000,48.333333,1.50,0.25,1493.461336,1484.439709,0.218750,96.125000,97.187500,1.25,2.25,4.5,2014,ATL,ORL
1,09/11/2013,2014,240,ATL,104,ORL,94,True,1,0,1,105.20,105.4,0.466507,0.367521,0.678832,0.215686,0.784314,10,9,86.300000,62.300000,50.000000,1,0,1485.341656,1500.000000,0.250,102.500000,105.25,1,3,6,105.029167,105.600,0.469447,0.381605,0.682991,0.190911,0.809089,2.75,1.25,86.300000,61.475000,43.333333,0.50,0.50,1493.046697,1500.000000,0.312500,106.875000,102.937500,1.00,2.00,4.5,2014,0,CHA,11/11/2013,77.400000,1500.000000,0.375000,88.029167,93.725000,0.404962,0.274453,0.642326,0.265804,0.734196,-6.00,-25.75,51.950,69.725000,48.333333,0.75,0.50,1497.009463,1443.153083,0.312500,96.041667,100.541667,0.75,2.25,4.5,2014,ATL,CHA
2,11/11/2013,2014,240,ATL,103,CHA,94,True,0,1,0,104.20,100.6,0.465278,0.366071,0.655462,0.219048,0.780952,9,18,86.300000,77.400000,57.142857,2,0,1502.016298,1500.000000,0.375,102.750000,97.00,1,4,7,104.704167,104.125,0.466485,0.377378,0.668826,0.202816,0.797184,5.50,6.75,86.300000,65.575000,49.285714,1.00,0.25,1493.366694,1500.000000,0.343750,105.437500,101.562500,1.00,2.75,5.5,2014,1,NYK,13/11/2013,65.700000,1500.000000,0.250000,90.408333,90.308333,0.433707,0.315244,0.808751,0.269915,0.730085,-8.75,-9.50,63.475,74.925000,32.916667,0.25,1.50,1480.756401,1481.559748,0.250000,104.125000,104.125000,1.50,1.50,4.5,2014,ATL,NYK
3,13/11/2013,2014,240,ATL,91,NYK,95,False,1,0,1,104.40,100.4,0.464037,0.353448,0.698276,0.210280,0.789720,-4,14,86.300000,65.700000,50.000000,0,1,1517.923445,1500.000000,0.250,103.500000,98.50,1,4,8,104.637500,102.725,0.466239,0.367914,0.677634,0.210304,0.789696,3.25,10.00,86.300000,68.425000,49.285714,0.75,0.50,1501.671956,1500.000000,0.281250,102.687500,100.312500,1.00,3.25,6.5,2014,1,PHI,15/11/2013,37.000000,1500.000000,0.500000,101.900000,106.500000,0.455278,0.328612,0.686296,0.238601,0.761399,-1.25,-17.00,46.250,62.425000,57.341270,0.50,0.75,1511.046361,1510.299421,0.125000,99.250000,111.250000,0.75,4.25,7.5,2014,ATL,PHI
4,15/11/2013,2014,240,ATL,113,PHI,103,True,1,0,1,102.00,98.4,0.466507,0.313559,0.747748,0.205742,0.794258,10,24,86.300000,37.000000,55.555556,1,0,1501.098771,1500.000000,0.500,113.666667,99.00,1,5,9,103.950000,101.200,0.465582,0.350150,0.695079,0.212689,0.787311,6.25,16.25,86.300000,60.600000,53.174603,1.00,0.25,1501.595043,1500.000000,0.343750,105.604167,99.937500,1.00,4.00,7.5,2014,0,NYK,16/11/2013,65.700000,1516.824674,0.250000,93.950000,97.700000,0.429900,0.324155,0.776874,0.288875,0.711125,-5.00,-20.00,62.225,82.875000,38.422619,0.50,0.50,1473.801230,1498.604017,0.187500,100.937500,104.687500,1.25,2.50,6.5,2014,ATL,NYK
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24677,02/04/2023,2023,240,WAS,109,NYK,118,False,0,1,0,117.20,117.8,0.520455,0.360248,0.714286,0.189055,0.810945,-9,-63,34.246017,70.500000,44.155844,0,1,1451.572477,1411.746618,0.125,110.500000,112.50,4,34,77,113.450000,119.900,0.503336,0.336191,0.773148,0.201389,0.798611,3.00,-63.25,50.411504,69.350000,44.371820,0.50,0.50,1432.406156,1561.724226,0.239583,116.916667,114.458333,1.75,33.50,75.5,2023,1,MIL,04/04/2023,81.200000,1555.672697,0.125000,126.200000,119.300000,0.509423,0.349973,0.761013,0.201889,0.798111,-1.50,319.50,77.800,60.873009,71.897966,1.00,0.25,1695.550355,1460.188367,0.322917,121.875000,121.541667,1.00,55.00,76.5,2023,WAS,MIL
24678,04/04/2023,2023,240,WAS,128,MIL,140,False,1,0,0,116.60,117.0,0.518349,0.385542,0.720430,0.189320,0.810680,-12,-75,34.246017,81.200000,43.589744,0,2,1433.746419,1555.672697,0.125,117.500000,118.75,1,34,78,115.350000,119.850,0.510886,0.362107,0.742608,0.196739,0.803261,-3.00,-66.25,43.773009,78.700000,44.120607,0.25,1.00,1437.783645,1547.604222,0.145833,113.416667,115.395833,1.75,33.75,76.5,2023,0,ATL,05/04/2023,72.300000,1559.124452,0.125000,125.100000,122.950000,0.487030,0.362599,0.838761,0.309065,0.690935,1.25,6.75,81.000,76.975000,49.995890,1.00,0.25,1493.173161,1500.887319,0.302083,119.645833,118.687500,1.25,38.75,77.5,2023,WAS,ATL
24679,05/04/2023,2023,240,WAS,116,ATL,134,False,0,1,1,121.40,121.4,0.517857,0.437126,0.714286,0.180095,0.819905,-18,-93,34.246017,72.300000,43.037975,0,3,1423.141649,1559.124452,0.125,115.500000,121.50,0,34,79,117.500000,119.550,0.514165,0.386354,0.724750,0.193539,0.806461,-5.00,-71.25,40.884513,78.550000,43.880101,0.25,1.50,1434.432669,1525.121863,0.135417,114.625000,117.604167,1.50,34.00,77.5,2023,1,MIA,07/04/2023,34.246017,1608.509611,0.250000,106.200000,113.250000,0.474457,0.368943,0.853483,0.220731,0.779269,9.75,-62.25,78.825,69.811504,52.856678,1.50,0.75,1505.540471,1471.936220,0.291667,108.433333,109.258333,1.25,41.50,78.5,2023,WAS,MIA
24680,07/04/2023,2023,240,WAS,114,MIA,108,True,1,0,0,117.40,123.4,0.494530,0.387879,0.724490,0.212560,0.787440,6,-87,34.246017,34.246017,43.750000,1,0,1413.102575,1608.509611,0.250,108.250000,109.25,1,35,80,118.150000,119.900,0.512797,0.392699,0.718373,0.192758,0.807242,-8.25,-79.50,34.246017,64.561504,43.633391,0.25,1.50,1430.390780,1533.763345,0.156250,112.937500,115.500000,1.50,34.25,78.5,2023,1,HOU,09/04/2023,60.800000,1580.174693,0.250000,110.400000,127.700000,0.474272,0.304810,0.752034,0.345092,0.654908,-2.50,-661.50,77.000,74.161504,23.876045,0.75,3.75,1302.156678,1532.082908,0.135417,112.520833,121.312500,1.75,18.75,78.5,2023,WAS,HOU
24681,09/04/2023,2023,240,WAS,109,HOU,114,False,1,0,2,119.40,122.2,0.498901,0.339506,0.765217,0.207547,0.792453,-5,-92,34.246017,60.800000,43.209877,0,1,1437.258986,1580.174693,0.250,108.500000,108.50,1,35,81,118.700000,121.000,0.507409,0.387513,0.731106,0.197381,0.802619,-7.25,-86.75,34.246017,62.136504,43.396899,0.25,1.50,1426.812408,1575.870363,0.187500,112.437500,114.500000,0.75,34.50,79.5,2023,0,IND,26/10/2023,34.246017,1453.308257,0.157895,117.300000,131.500000,0.487050,0.374593,0.783993,0.274132,0.725868,-5.25,-263.00,38.500,56.186504,41.826288,0.25,4.50,1384.128034,1477.474168,0.156250,118.125000,122.125000,1.75,33.25,79.5,2023,WAS,IND

In [28]:
# """
# This are the last games for each team where the next games are not known
# """
# target_2_rows = full_eng[full_eng["target"] == 2]
# target_2_rows

In [29]:
full_eng[["team_x", "team_opp_next_x", "team_y", "team_opp_next_y", "date_next"]]

      team_x team_opp_next_x team_y team_opp_next_y   date_next
0        ATL             ORL    ORL             ATL  09/11/2013
1        ATL             CHA    CHA             ATL  11/11/2013
2        ATL             NYK    NYK             ATL  13/11/2013
3        ATL             PHI    PHI             ATL  15/11/2013
4        ATL             NYK    NYK             ATL  16/11/2013
...      ...             ...    ...             ...         ...
24677    WAS             MIL    MIL             WAS  04/04/2023
24678    WAS             ATL    ATL             WAS  05/04/2023
24679    WAS             MIA    MIA             WAS  07/04/2023
24680    WAS             HOU    HOU             WAS  09/04/2023
24681    WAS             IND    IND             WAS  26/10/2023

[24682 rows x 5 columns]

In [30]:
data_dir = 'C:/Users/User/Dropbox/RU45-Sussex OneDrive/NBA Games Prediction Model/data'
subfolder_name = 'feature_engineered_csv'
subfolder_path = os.path.join(data_dir, subfolder_name)

if not os.path.exists(subfolder_path):
    os.makedirs(subfolder_path)
    print(f'{subfolder_name} created')
else:
    print(f'{subfolder_name} already exist')
    
full_eng.to_csv('C:/Users/User/Dropbox/RU45-Sussex OneDrive/NBA Games Prediction Model/data/feature_engineered_csv/engDF_final_new.csv')

feature_engineered_csv already exist